<?php echo $this->doctype(); 
?>
<html>
    <body >
        <style>

        </style>
        <div style=" background-image: url('img/UCBhome.jpg'); background-position: center; height: 500px; ">
            <br/>
           
            <div class="pager" style=" color: white;">
              <h4  >Bem Vindo(a) </h4>
                <h3  style=" color: #fff194"><?php 
                    foreach ( $this->identityComum as $l){
                        echo $l[0]->getNome()      
                       ;
                    }?>
                </h3>
              <br/>
              
             
            </div>
            <div style=" color: white; " class=" pager">
                  <div style=" background: #0089cd; width: 200px"  class=" img-thumbnail img-rounded  ">
                    <br/>
                     <a style=" color:white; " href="<?php echo $this->url('paginator', ['controller'=>'administrador', 'action' =>'todosalunospresencial']) ?>">
                   
                        <span><p><i style=" font-size: 50px " class="fa fa-mortar-board" aria-hidden="true"></i></p></span></a>
                        <h5 style=" color: #fff194"><i class=" fa fa-cogs" style=" color: white"></i> Controle de alunos</h5>
                        
            
                 </div>
                 
                <div style=" background: #0089cd; width: 200px"  class=" img-thumbnail img-rounded  ">
                    <br/>
                      <a style=" color:white" href="<?php echo $this->url('paginator', ['controller'=>'administrador', 'action' =>'empresa']) ?>">
                    <span><p><i style=" font-size: 50px " class="fa fa-briefcase" aria-hidden="true"></i></p></span></a>
                        <h5 style=" color: #fff194"><i class=" fa fa-cogs" style=" color: white"></i> Controle de empresas</h5>
            
                 </div>
                <div style=" background: #0089cd; width: 200px"  class=" img-thumbnail img-rounded  ">
                    <br/> <a style=" color:white" href="<?php echo $this->url('documentos') ?>">
                         <span><p><i style=" font-size: 50px " class="fa fa-archive" aria-hidden="true"></i></p></span></a>
                        <h5 style=" color: #fff194"><i class=" fa fa-cogs" style=" color: white"></i> Controle de documentos</h5>
          
                </div>
                <div style=" background: #0089cd; width: 200px"  class=" img-thumbnail img-rounded  ">
                    <br/> <a style=" color:white" href="<?php echo $this->url('usuarios') ?>">
                         <span><p><i style=" font-size: 50px " class="fa fa-users" aria-hidden="true"></i></p></span></a>
                        <h5 style=" color: #fff194"><i class=" fa fa-cogs" style=" color: white"></i> Controle de acessos</h5>
          
                </div>
                
                  <div style=" background: #0089cd; width: 200px"  class=" img-thumbnail img-rounded  ">
                    <br/> <a style=" color:white" href="<?php echo $this->url('dadosPresencial') ?>">
                         <span><p><i style=" font-size: 50px " class="fa fa-refresh" aria-hidden="true"></i></p></span></a>
                        <h5 style=" color: #fff194"> Atualizar dados</h5>
          
                </div>
      
       
            </div>   </div>
    
    </body>
</html>