<?php $fetchRow = $this->fetchRow;
       $row = $this->row;
       $curso = $this->curso;
       $recisaoRow = $this->recisaoRow;
       $rowEmpresa = $this->rowEmpresa;
       ?>
 <body><?php
   /* <br/>
    <form method="post" class="table-striped">   
        <select name="curso" class="btn-default">
            <option></option>
            <option>EAD - ADMINISTRAÇÃO</option>
            <option>EAD - PEDAGOGIA</option>
            <option>EAD - GESTAO DE RECURSOS HUMANOS</option>
            <option>EAD - TURISMO</option>
            <option>EAD - GESTÃO DA TECNOLOGIA DA INFORMAÇÃO</option>
            <option>EAD - ANÁLISE E DESENV. DE SISTEMAS</option>
            <option>EAD - CIÊNCIAS CONTÁBEIS</option>
            <option>EAD - CIENCIAS ECONÔMICAS</option>
            <option>EAD - FILOSOFIA</option>
            <option>EAD - GESTÃO PÚBLICA</option>
            <option>EAD - GESTÃO DO COMÉRCIO EXTERIOR</option>
            <option>EAD - GESTÃO FINANCEIRA</option>
            <option>EAD - LETRAS PORTUGUÊS</option>
            <option>EAD - PROFORM</option>
            <option>EAD - SEGURANÇA DA INFORMAÇÃO</option>
            <option>EAD - SEGURANÇA PÚBLICA</option>
                
        </select><br/><br/><input type="submit" value="OK" class="btn-default"/>  <br/><br/>
 
    </form>*/?>
    <form>
        <div><h3 class="navbar-brand"><i class="glyphicon glyphicon-globe   "></i>&nbsp;&nbsp;Geral</h3></div>
    <br/>  
    <br/>
    <br/>
   
        <br/><br/>
       
        <table class="table">
            <tr>
            <th> Alunos cadastrados </th>
            <th>Alunos em estágios</th>
            <th>Empresas Cadastradas</th>
            
            </tr>
        <tr>
            <td style="font-size: 80px; color: #3373ea"><?php echo $row;?></td>
            <td style="font-size: 80px; color:  #33cd6d"><?php echo $recisaoRow;?></td>
            <td style="font-size: 80px; color:  #33cd6d"><?php echo $rowEmpresa;?></td>
        </tr>
        </table>
        
        
    </form>
    
</body>