<?php
    echo $this->doctype();
    $lista = $this->lista;
    $listaVaga = $this->listaVaga;
    $listaEncaminhamento = $this->listaEncaminhamento;
?>
<html lang="pt-br">
    <head>
        <title>Perfil</title>
        <meta charset="utf-8">
    </head>
<body>
    <div class="navbar-collapse">
              <h2 style=" color: #989597; text-align: center"> Perfil do Aluno</h2>
            </div>
 <div >
  <div>
    <div class="thumbnail">
      <div class="caption">
         <?php if($lista):
            foreach ($lista as $l): 
             $getidaluno = $l->getidAluno();
          ?>
            
    <div class="navbar">
        <h3 class="pager"> <i class=" glyphicon glyphicon-user" style="color: #3333ff"></i> <?php echo $l->getNome(); ?></h3>
        <p class="pager" style=""><i class="glyphicon glyphicon-book"></i>&nbsp;&nbsp;<?php echo $l->getCurso(); ?> &nbsp;&nbsp; <i class="glyphicon glyphicon-bookmark"></i>  <?php echo $l->getMatricula(); ?></p>
       
        <br/>
    </div>
        <?php endforeach; endif;?>
      </div>
    </div>
  </div>
 </div>

 <div >
  <div>
    <div class="thumbnail">
      <div class="caption">
          <div>
            <h4 style="text-align: center; " ><?php echo $this->translate('Vagas Cadastradas')?><br/>
            <a style="color:   #2f950c; " class="btn" href="<?php echo $this->url('vaga/default', array('controller' => 'index', 'action' => 'index', 'idVaga'=>$getidaluno)); ?>"><i class="glyphicon glyphicon-plus"></i> </a></h4>
        </div>
    
<?php if ($listaVaga){?>
    <div class="navbar-default">
      <form method="post" >
    <table class="table navbar-default" >
       
        <tr >
          <th>ID</th>
          <th>EMPRESA</th>
          <th>AGENTE</th>
          <th>CONTRATOS</th>
          <th>EXCLUIR</th>
        </tr>
            <?php foreach ($listaVaga as $l):?>
            <?php  if($l->getRecisao() !=(null)){ ?>
        <tr class="table" style="background: #ab1c1c; color: white">
            <?php } ?>
            
            <?php  if($l->getRecisao() ==('')){ ?>
        <tr class="table" style="background: #8fee8f; ">
            <?php } ?>
            <td><?php echo $l->getidvaga();?></td>
            <td><?php echo $l->getEmpresa(); ?></td>
            <td><?php echo $l->getAgente(); ?></td>
            <td><a href="<?php echo $this->url('vaga/default',  array('controller' => 'index', 'action' => 'lancarcontratos','id'=>$getidaluno, 'idVaga'=>$l->getidvaga())); ?>" class="btn"><i class="glyphicon glyphicon-ok"></i></a></td>     
            <td><a  class="btn" href="<?php echo $this->url('delete', array( 'action' => 'excluirvaga', 'iddelete' => $l->getidvaga())) ?>"><i class=" glyphicon glyphicon-remove" ></i></a></td> 
        </tr> 
            <?php endforeach;?>
    </table>      
</form>
            <?php }
            else{?>        
<div class="alert-danger" style="margin: initial">
           <br/>
           <h4 style="text-align: center">Nenhum estágio lançado</h4><br/>      
</div>
        <?php };?> 
</div>
      </div>
    </div>
  </div>
  </div>
 
<?php echo $this->resp; ?>
</body>
</html>