<!DOCTYPE html>
<html lang="pt-br">  
    <title>Info</title>
    <meta charset="utf-8">
     <body>
<?php foreach ($this->curso as $l){
    $curso =  $l->getCurso();
    $idCurso = $l->getIddados();
}
?><div class=" nav row" style=" background-color: #1989f1">
   
     <h4 style="color: white; text-align: center"><?php echo $curso?></h4>
  
 </div>
    
     <div class="nav">
      <div class="caption ">
          <div class="row " >
            <div>
                <div class="" style=" ">
                <div class="caption ">
                    <ul class="nav  nav-tabs ">
                        <li  role="presentation"><a href="<?php echo $this->url('relatorioEAD/default', ['controller'=>'relatorioead','action'=>'infoead','curso'=>$idCurso])?>">Todas as vagas  <span class="label label-primary"> <?php echo $this->countListaTotalVaga?></span> </a></li>
                        <li class="  active" role="presentation" ><a href="#"><label>Estagiando</label> <span class="label label-success"> <?php echo $this->countListaEstagiando?></span></a></li>
                        <li role="presentation" ><a href="<?php echo $this->url('relatorioEAD/default', ['controller'=>'relatorioead','action'=>'infoeadencerrado','curso'=>$idCurso])?>">Encerrados <span class="label label-danger"> <?php echo $this->countListaEncerrado?></span></a></li>
                    </ul> 
                </div>
              </div>
            </div>
        </div>
        <br/><div class="pager"><i style="color:   #c4ffc2" class=" glyphicon glyphicon-stop"></i>Todas vagas ativas</div>
          <br/>
          <br/>
         <table class="table "> 
   
             <tr>
                 <th>Perfil</th>
                 <th>Empresa</th>
                 <th>Agente de Integração</th>
                 <th>Recisão</th>  
             </tr>
      <?php
    
        foreach ($this->pagination as $f){
            if($f->getRecisao()== ''){ ?> 
            <tr style="background-color: #c4ffc2;">
                    <td><a href="<?php echo $this->url('perfilPresencial/default', 
                         array('controller' => 'alunoPresencial', 'action' => 'perfil', 'id'=>$f->getIdalunovaga(),)); ?>"><i class=" glyphicon glyphicon-user"></i></a></td>
                    <td><?php echo  $f->getEmpresa();?></td>
                    <td><?php echo  $f->getAgente();?></td>  
                    <td><?php echo  $f->getRecisao();?></td> 
                
                 </tr>   

    <?php  } ?><?php };?>
          
         </table>
                  <?php
    if($this->listaVaga == null ){
        echo $this->mensagem;}?>
      </div></div>
<nav aria-label="Page navigation">
         <ul  class="pager">
             <li  <?php if ($this->pageNumber == 1|| $this->pageNumber == 0 ){
     echo "class='disabled'". "style='pointer-events: none'";
    }
    ?>>
      <a href="<?php if ($this->pageNumber > 1){echo $this->pageNumber - 1; }?>" aria-label="Previous">
          <span aria-hidden="true"><i class="glyphicon glyphicon-chevron-left"> </i></span>
      </a>
    </li>
    <li  <?php if ($this->pageNumber >= $this->count){ echo "class='disabled'". "style='pointer-events: none'";}?>>
      <a href="<?php echo $this->pageNumber + 1?>" aria-label="Next">
          <span aria-hidden="true"><i class="glyphicon glyphicon-chevron-right"></i></span>
      </a>
    </li> 
  </ul>
          
</nav><div class="pager"><?php echo $this->pageNumber.' de '.$this->count;?></div> 

         <div ><br/>
            <ul class="pager">
                
                <li><a href="<?php echo $this->url('relatorioEAD') ?>"><span class="btn btn-default" >Voltar</span></a></li> 
            </ul>
            </div> 
     
    </body>
</html>