<?=  $this->doctype(); ?>
<html lang="pt-br">
<head>
    <meta charset="utf-8">
<?= $this->headTitle('UCB -  '. $this->translate('Projem'))->setSeparator(' - ')->setAutoEscape(false) ?>
<?= $this->headMeta()
    ->appendName('viewport', 'width=device-width, initial-scale=1.0')
    ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
?>
<?= $this->headLink(['rel' => 'shortcut icon', 'type' => '', 'href' => $this->basePath() . ''])
                ->prependStylesheet($this->basePath('css/bootstrap.css'))
                ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
                ->prependStylesheet($this->basePath('css/bootstrap-datepicker.min.css'))
                ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                ->prependStylesheet($this->basePath('fonts/FontAwesome.otf'))
                ->prependStylesheet($this->basePath('css/font-awesome.min.css'))
                ->prependStylesheet($this->basePath('css/bootstrap-toggle.min.css'))
                ->prependStylesheet($this->basePath('css/style.css'))
?>
<?= $this->headScript()
                ->prependFile($this->basePath('js/jquery.validate.js'))
                ->prependFile($this->basePath('js/jquery.tablesorter.min.js'))
                ->prependFile($this->basePath('js/jquery.jquery-latest.js'))
                ->prependFile($this->basePath('js/bootstrap.min.js'))
                ->prependFile($this->basePath('js/bootstrap-toggle.min.js'))
                ->prependFile($this->basePath('js/locales/bootstrap-datepicker.pt-BR.js'))
                ->prependFile($this->basePath('js/bootstrap-datepicker.js'))
                ->prependFile($this->basePath('js/bootstrap-datepicker-globalize.js'))
                ->prependFile($this->basePath('js/jquery.min.js'))
                ->prependFile($this->basePath('js/pace.js'))
                ->prependFile($this->basePath('js/Chart.min.js'))

;?>
</head>
    <body style="  background-color: #f2f2f2">
       <?=  $this->partial('base/layout/nav-bar');?>
        <div class=" container" >
        <?= 
            $this->content;
            $this->inlineScript(); 
        ?>
        </div>
        <div style=" background-color:white; height: 270px; color: #0089cd">
                <hr>
                <?='&copy; Romário Macedo - '. date('Y'); ?>
                <?='&copy; Romário Macedo - '. date('Y'); ?>
                <hr>
        </div>
</html>
