<?php echo $this->doctype(); ?>
<html lang="pt-br">
<meta charset="utf-8">
<body>
    <div class="navbar-collapse">
        <h3><i class=" glyphicon glyphicon-briefcase "></i> Agentes de Integração</h3>
    </div>
    <div class="thumbnail">
      <div class="caption">
        <table class="table">
            <tr>
                <th>Emrpesa</th>
                <th>Editar</th>
                <th>Excluir</th>
                
            </tr>
                <?php foreach ($this->pagination as $l):?>
            <tr style=" background-color: #b6fffd">
                <td><?php echo $l->getAgente()?></td>
                <td><a href="<?php echo $this->url('empresa/default', array('controller'=>'administrador', 'action'=>'editarAgente', 'id'=>$l->getIdagente()))?>"><i class=" glyphicon glyphicon-edit"></i></a></td>
                <td><a onclick="return confirm('Tem certeza que deseja deletar este registro?')" style="color: #c81616" href="<?php echo $this->url('excluirAgente',['action'=>'excluirAgente', 'deleteAgente'=>$l->getIdagente(),'page'=>$this->pageNumber] )?>"><i  class=" glyphicon glyphicon-remove"></i></a></td>
            </tr><?php    endforeach;?>

        </table>     
      </div>
    </div>
    
    <nav aria-label="Page navigation">
         <ul  class="pager">
             <li  <?php if ($this->pageNumber == 1|| $this->pageNumber == 0 ){
     echo "class='disabled'". "style='pointer-events: none'";
    }
    ?>>
      <a href="<?php if ($this->pageNumber > 1){echo $this->pageNumber - 1; }?>" aria-label="Previous">
          <span aria-hidden="true"><i class="glyphicon glyphicon-chevron-left"> </i></span>
      </a>
    </li>
    <li  <?php if ($this->pageNumber >= $this->count){ echo "class='disabled'". "style='pointer-events: none'";}?>>
      <a href="<?php echo $this->pageNumber + 1?>" aria-label="Next">
          <span aria-hidden="true"><i class="glyphicon glyphicon-chevron-right"></i></span>
      </a>
    </li> 
  </ul>
          
</nav><div class="pager"><?php echo $this->pageNumber.' de '.$this->count;?></div> 
<?php echo $this->resp; ?>
</body>
</html>