<html lang="pt-br">
<meta charset="utf-8">
<body>
<div class="navbar-collapse">
        <h3><i class=" glyphicon glyphicon-user"></i> Cadastro de aluno</h3>
</div>
<div style="height: 300px" class="thumbnail">
      <div class="caption">
<form class="navbar-collapse" method="post">
    <div class="col-lg-4">
        <div>
    <?php echo $this->translate('Nome')?><br/><input name="nome" type="text" class="form-control " required="" /><br/>
        <?php echo $this->translate('Matricula UCB')?><br/><input name="matricula" type="text" class="form-control" required=""/><br/>
            <?php echo $this->translate('Curso')?><br/>
            <select name="curso" class="form-control">
            <option></option>
            <?php
            foreach ($this->listaDadosPresencial as $l):?>
            <option><?php echo $l->getCurso()?></option>
            <?php endforeach;?>
            <?php
            foreach ($this->listaDados as $l):?>
            <option><?php echo $l->getCurso()?></option>
            <?php endforeach;?>
            
                   
            </select><br/>
            <input type="submit" class="btn btn-default" name="cadastrar" value="Cadastrar" />
        </div>
    </div>          
</form></div></div>
<nav>
        <div style="">
            <ul class="pager">

                <li ><a href="<?php echo $this->url('perfil') ?>"><span class="btn btn-default" >&larr;&nbsp;&nbsp;Voltar</span></a></li> 
            </ul>
        </div> 
    </nav>
<?php echo $this->resp; ?>
</body></html>