<html lang="pt-br">
<meta charset="utf-8">
<body>
          
  <?php   $success = $this-> success ?>
    <h3 class="navbar-brand"><i class="glyphicon glyphicon-edit"></i>&nbsp;&nbsp;Editar Agente</h3>
<br/>
<br/><br/>

<br/>
<br/>
<div class="thumbnail">
      <div class="caption">
        <div class="navbar-collapse">

            <form class="navbar-default" method="post">
                <?php foreach ($this->listaAgente as $l):?>
                <div class="col-lg-4">
                <?php echo $this->translate('Agente')?><br/><input value="<?php echo $l->getAgente()?>" name="agente" type="text" class="form-control" required=""/><br/>
                    <?php echo $this->translate('CNPJ')?><br/><input value="<?php echo $l->getCnpj()?>"  name="cnpj" type="text" class="form-control" required=""/><br/>
                        <?php echo $this->translate('Telefone')?><br/><input value="<?php echo $l->getTelefone()?>"  name="telefone" type="text" class="form-control" required=""/><br/>
                        <input type="submit" class="btn btn-default" name="cadastrar" value="Salvar" />
                </div>
                <?php endforeach;?>
            </form>

        </div>
      </div>
</div>
<div style="">
            <ul class="pager">

                <li ><a href="<?php echo $this->url('paginator', ['controller'=>'administrador', 'action' =>'agente']) ?>"><span class="btn btn-default" >&larr;&nbsp;&nbsp;Voltar</span></a></li> 
            </ul>
        </div> 

<?php echo $this->resp; ?>
</body>
</html>