<?=  $this->doctype(); ?>
<html lang="pt-br">
<head>
<meta charset="utf-8">

<?= $this->headTitle('UCB -  '. $this->translate('Projem'))->setSeparator(' - ')->setAutoEscape(false) ?>
<?= $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0')->appendHttpEquiv('X-UA-Compatible', 'IE=edge')?>
<?= $this->headLink(['rel' => 'shortcut icon', 'type' => '', 'href' => $this->basePath() . ''])
                ->prependStylesheet($this->basePath('css/bootstrap.css'))
                ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
                ->prependStylesheet($this->basePath('fonts/FontAwesome.otf'))
                ->prependStylesheet($this->basePath('css/font-awesome.min.css'))
                ->prependStylesheet($this->basePath('css/style.css'))
                ->prependStylesheet($this->basePath('css/home.css'))
?>
<?= $this->headScript()
                ->prependFile($this->basePath('js/bootstrap.min.js'))
                ->prependFile($this->basePath('js/jquery.min.js'))
;?>
</head>
<body style="  background-color: #f2f2f2"> 
   <?=  $this->partial('base/layout/nav-bar');?>
    <div class="container" >
        <?= $this->content.
        $this->inlineScript(); 
        ?>
    </div>
        <div class="well pager">
                <i class=" well-lg fa fa-github fa-3x" aria-hidden="true"></i>
                <i class="well-lg fa fa-facebook-official fa-3x" aria-hidden="true"></i>
                <i class="well-lg fa fa-youtube fa-3x" aria-hidden="true"></i>
                <hr>
                <?= '&copy Romário Macedo - 2017' ?>
                
        </div>
