<body>
    
    <script>
    function validar(){
        var login = document.getElementById('login');
        var senha = document.getElementById('senha');
        if (login === '' && senha === '' ){
            alert "Preencha login e senha";
        }
        if (login === ''){
            alert "Preencha login!"
        }
        if (senha === ''){
            alert "Preencha senha!"
        }
            return false;
    }
 
    </script>
        
<br/>
<br/>
<br/>
<br/>
<div class="navbar-collapse" id="aluno" style="margin-left: 40%;">
     <h3 style=" color: #c2c2c2"><i class="glyphicon glyphicon-log-in"></i></h3>
<form class="col-lg-4" method="post">
    <input name="login" type="text" class="form-control " placeholder="Login"/>
    <br/><input name="senha" type="password" class=" form-control" placeholder="Senha"/><br/>
            
            <input type="submit" class="btn btn-default" name="Entrar" value="Entrar"/>
            <?php
    echo $this->flashMessenger()
        ->setMessageOpenFormat("<div %s>")
        ->setMessageSeparatorString('<p></p>')
        ->setMessageCloseString('<button type="button" class="close" data-dismiss="alert">x</button></div>')
        ->render('error', array('alert alert-danger'));?>
</form>
</div>
<br/><br/>
<?php echo $this->resp; ?>
</body>