
<body>
 

    <div class=" nav row" style=" background-color: #07485b">
        <h4 style=" color: white;text-align: center"><i class=" glyphicon glyphicon-log-in"></i> Acesso</h4>
    </div>
    <?php
            if($this->mensagem){ ?> 
    <div class=" nav row alert-danger" style=" text-align: center"><?php
            echo $this->mensagem ;                     
                ?>
    </div>
    <?php  }?><br/>
    <div class="navbar-collapse" >
        <form class="col-lg-12 pager" method="post" id="loginForm">
            <div> 
                <input id="login" name="login" type="text" class=" form-control" placeholder="Login" required=""/><br/>   
                <input id="senha" name="senha" type="password" class="  form-control" placeholder="Senha" required=""/><br/>   
                <input style=" background-color:  #07485b; color: white"  type="submit" class="btn  btn-block default  " name="Entrar" value="Entrar"/>   
            </div>
        </form>
    </div>
<?php echo $this->resp; ?>
</body></html>