<?= $this->doctype(); ?>
<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('UCB -  '. $this->translate('Projem'))->setSeparator(' - ')->setAutoEscape(false) ?>
        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        <?= $this->headLink(array('rel' => 'shortcut icon', 'type' => '', 'href' => $this->basePath() . '')) 
                        ->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
                        ->prependStylesheet($this->basePath('css/jquery.rateyo.css'))
                        ?>
        <?= $this->headScript()
            ->prependFile($this->basePath('js/jquery.validate.js'))
            ->prependFile($this->basePath('js/Chart.min.js'))
            ->prependFile($this->basePath('js/Mascaras.js'))
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery.rateyo.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
        
        ; ?>

    </head><br/><br/><br/>
    <body  style=" background-color: #f6f6f6; background-position: center; background-position: top">
        <div class="container" style=" width: 335px; background-color:white; ">
            <?= $this->content; ?>
            <footer><hr>
                <p style="text-align: center ">&copy; <?php echo date('Y') ?> <a href="http://www.ucb.br/Cursos/58ProjetoDeEmpregabilidadeProjem/">PROJEM - UCB</a>. </p>  
            </footer>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>
