<?php echo $this->doctype(); 
?>

<html lang="pt-br">
    <!--
    Autor: Romário Macedo Portela
    Estudante de Análise e Desenv. de Sistemas
    Framework utilizado: Zend 2
    -->
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('UCB -  '. $this->translate('Projem'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => '', 'href' => $this->basePath() . ''))
                                
                        ->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
                        ?>
                         

        <!-- Scripts -->
        <?php echo $this->headScript()
             
            ->prependFile($this->basePath('js/Chart.min.js'))
            ->prependFile($this->basePath('js/Mascaras.js'))
            ->prependFile($this->basePath('js/jquery.maskedinput.js'))
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body  style=" background-image: url('img/UCB.jpg'); background-position: center; background-position: top">
        <br/><br/><br/><br/>
        <div class="container" style=" width: 335px; background-color:white; ">
            <?php echo $this->content; ?>
            
            <footer><hr>
                <p style="text-align: center ">&copy; <?php echo date('Y') ?> <a href="http://www.ucb.br/Cursos/58ProjetoDeEmpregabilidadeProjem/">PROJEM - UCB</a>. </p>
              
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
    
</html>
