<?php
$lista = $this->lista;
?>

<script>
   function noenter() {
      return !(window.event && window.event.keyCode === 13);
    };
</script>
 <div class=" panel panel-primary">
        <div class="panel-heading">
              <?= 'Cadastro de empresa'?>
        </div>
<div>
    <div> 
         <br/><br/>
        <form  method="post" onKeyPress="return noenter()">
            <div class="navbar-collapse"  >
                        
                <div class="row">
                    <div class="col-lg-6">
                      <div class="input-group">
                       
                          <input id="cnpj" name="porCnpj" type="text" class="form-control" placeholder="Procurar por CNPJ">
                         <span class="input-group-btn">
                            <button class="btn btn-primary" name="buscar" value="buscarPorCnpj" type="submit"><i class=" glyphicon glyphicon-search"></i></button>
                        </span>
                      </div>
                    </div>
                    <div class="col-lg-6">
                      <div class="input-group">
                         <input name="porNome" type="text" class="form-control" placeholder="Procurar por nome">
                        <span class="input-group-btn">
                          <button class="btn btn-primary" name="buscar" value="buscarPorNome" type="submit"><i class=" glyphicon glyphicon-search"></i></button>
                        </span>
                      </div>
                    </div>
                  </div>
            <?php if($lista):?>
                 <br/><br/><br/><br/>
        <table class="table">
                 <tr>
                  <th><i class="glyphicon glyphicon-user"></i>EMPRESA</th>
                  <th>CNPJ</th>
                  <th></th>
                </tr>
                   <?php foreach ($lista as $f): ?>   
                <tr  style="background: #cdffff">
                  <td><?php echo $f[0]->getEmpresa(); ?></td>
                  <td><?php echo $f[0]->getCnpj(); ?></td>
                  <td><a href="<?php echo $this->url('perfilEmpresa/default', 
                          array('controller' => 'empresa', 'action' => 'perfilempresa', 'id'=>$f[0]->getEmpresa(),)); ?>" class="btn"><i class="glyphicon glyphicon-ok-sign"></i></a></td>
                </tr><?php endforeach; endif;?>
            </table></div>
        </form>
          <div class="well-lg">
             <a href="<?= $this->url('paginator', ['controller'=>'administrador', 'action' =>'empresa']) ?>" class="btn btn-primary"><i class="fa fa-briefcase fa-2x pull-left"></i>Lista de <br/>  Empresas</a>
           
         </div>
    </div>
</div></div>
        <?php echo $this->resp; ?>
