<?php
    echo $this->doctype();
?>
<html lang="pt-br">
    <head>
        <title>Perfil</title>
        <meta charset="utf-8">
        
    </head>
<body>
  
 <div class=" nav row" style=" background-color: #1989f1">
   
     <h4 style="color: white; text-align: center"><i class=" glyphicon glyphicon-user"  style=" color: #fff194"></i> Perfil da empresa</h4>
  
 </div>
      <div class="row" >
            <div>
                <div class="" style=" ">
                <div class="caption">
                    <ul class="nav  nav-tabs" style=" background-color: #f4f4f4">
                        <li class="  active" role="presentation"><a><label>Modalidade Presencial</label></a></li>
                       
                    </ul> 
                </div>
              </div>
            </div>
        </div>
 <div >
     <div class="row">
    <div class="">
      <div class="caption">
         <?php if($this->empresaSelect):
            foreach ($this->empresaSelect as $f): 
             
          ?>
            
    <div class="navbar">
        <h3 class="pager"> <?php echo $f[0]->getEmpresa(); ?></h3>
        <p class="pager" style=""><label>CNPJ: </label> <?php echo $f[0]->getCnpj(); ?> <br/><label>Responável: </label>  <?php echo $f[0]->getResponsavel(); ?> <label>Telefone: </label>  <?php echo $f[0]->getTelefone(); ?><br/>
        

    </div>     
        <?php endforeach; endif;?>
      </div>
    </div>
  </div>
 </div>
 <div >
  <div >
    <div class="">
      <div class="caption">
        
    <div class="row" >
            <div>
                <div class="" style=" ">
                <div class="caption">
                    <ul class="nav  nav-tabs" style=" background-color: #f4f4f4">
                        <li  role="presentation"><a href="<?php echo $this->url('perfilEmpresa/default', ['controller'=>'empresa','action'=>'perfilempresa','id'=>$this->empresa])?>">Todas as vagas  <span class="label label-primary"> <?php echo count($this->listaVaga) ?></span> </a></li>
                        <li role="presentation" ><a href="<?php echo $this->url('perfilEmpresa/default', ['controller'=>'empresa','action'=>'perfilempresaestagiando','id'=>$this->empresa])?>">Estagiando <span class="label label-success"> <?php echo count($this->listaVagaEstagiando)?></span></a></li>
                        <li class="  active" role="presentation" ><a href=""><label>Encerrado</label><span class="label label-danger"> <?php echo count($this->listaVaga) - count($this->listaVagaEstagiando) ;?></span></a></li>
                    </ul> 
                </div>
              </div>
            </div>
        </div>
<?php if ($this->listaVaga){?>
     
      <form method="post" >
    <table class="table navbar-default" >
      
        <tr >
          <th>Perfil Aluno</th>
          <th>Empresa</th>
          <th>Agente de Integração</th>
      
        </tr>
            
      <?php foreach ($this->pagination   as $f):?>
            <?php  if($f->getRecisao() !=(null)){ ?>     
         
        <tr class="table" style="background: #ab1c1c; color: white">
            <td><a href="<?php echo $this->url('perfilPresencial/default',['controller'=>'alunoPresencial', 'action'=>'perfil', 'id'=>$f->getIdalunovaga()])?>"><i class="glyphicon glyphicon-user"></i></a> <?php echo $f->getAluno()?></td>
            <td><?php echo $f->getEmpresa(); ?></td>
            <td><?php echo $f->getAgente(); ?></td>
           
         </tr>   <?php } ?>
            
           
            <?php endforeach;?>
    </table>    
          <br/>
       
          
          
          
</form>
          
          <nav aria-label="Page navigation">
         <ul  class="pager">
             <li  <?php if ($this->pageNumber == 1|| $this->pageNumber == 0 ){
     echo "class='disabled'". "style='pointer-events: none'";
    }
    ?>>
      <a href="<?php if ($this->pageNumber > 1){echo $this->pageNumber - 1; }?>" aria-label="Previous">
          <span aria-hidden="true"><i class="glyphicon glyphicon-chevron-left"> </i></span>
      </a>
    </li>
    <li  <?php if ($this->pageNumber >= $this->count){ echo "class='disabled'". "style='pointer-events: none'";}?>>
      <a href="<?php echo $this->pageNumber + 1?>" aria-label="Next">
          <span aria-hidden="true"><i class="glyphicon glyphicon-chevron-right"></i></span>
      </a>
    </li> 
  </ul>
          
</nav><div class="pager"><?php echo $this->pageNumber.' de '.$this->count;?></div> 
            <?php }
            if( count($this->listaVaga) - count($this->listaVagaEstagiando)==0){?>        
    <div class=" thumbnail row">  
        <div class="alert-danger" style="margin: initial">
                <br/>
                <h4 style="text-align: center">Nenhum estágio lançado</h4><br/>      
        </div>
    </div>
        <?php };?>     
    
</div>
       
      </div>
    </div>
  </div>
    
<?php echo $this->resp; ?>
</body>
</html>