<html lang="pt-br">
<meta charset="utf-8">
<body>
<div class="navbar-collapse">
        <h3><i class=" glyphicon glyphicon-user"></i> Cadastro de aluno</h3>
</div>
<div style="height: 600px" class="thumbnail">
      <div class="caption">
          
          <div class="row" >
            <div>
                <div class="" style=" ">
                <div class="caption">
                    <ul class="nav  nav-tabs">
                        <li class="  active" role="presentation"><a>Modalidade Presencial</a></li>
                        <li role="presentation" ><a href="<?php echo $this->url('aluno/default',['controller'=>'aluno', 'action'=>'cadastrar','id'=>'0'])?>">Modalidade EAD</a></li>
                      
                    </ul> 
                </div>
              </div>
            </div>
        </div>  
<form class="navbar-collapse" method="post">
    <div class="col-lg-4">
        <div>
    <?php echo $this->translate('Nome')?><br/><input name="nome" type="text" class="form-control " required="" /><br/>
        <?php echo $this->translate('Matricula UCB')?><br/><input name="matricula" type="text" class="form-control" required=""/><br/>
        <?php echo $this->translate('CPF')?><br/><input name="cpf" type="text" class="form-control" required=""/><br/>
        <?php echo $this->translate('E-mail')?><br/><input name="email" type="text" class="form-control" required=""/><br/>
            <?php echo $this->translate('Curso')?><br/>
            <select name="curso" class="form-control">
            <option></option>
            <?php
            foreach ($this->listaDadosPresencial as $l):?>
            <option><?php echo $l->getCurso()?></option>
            <?php endforeach;?>
            <?php
            foreach ($this->listaDados as $l):?>
            <option><?php echo $l->getCurso()?></option>
            <?php endforeach;?>
            
                   
            </select><br/>
            <?php echo $this->translate('Modalidade')?><br/>
            <select  name="modalidade" class="form-control" required="">
                <option></option>
                <option>
                    Presencial
                </option>
                 <option>
                    EAD
                </option>
            </select>
              <br/><br/>
            <input type="submit" class="btn btn-default" name="cadastrar" value="Cadastrar" />
        </div>
    </div>          
</form></div></div>

<?php echo $this->resp; ?>
</body></html>