<?php

namespace Empresa\Entity;

/**
 * LoginRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmpresaRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function findByEmpresa($empresa) {
   
        $userLogin = $this->createQueryBuilder('m')
                        >select('m.Matricula,m.Nome , m.Id')
                         ->from('bundle:entity','m')
                         ->where('m.Matricula = :a1')
                        ->setParameter('a1', $matricula)->getQuery()->getResult();
        return $userLogin;
    }
    public function findByPerfil($matricula) {
   
        $userLogin = $this->createQueryBuilder('m')
                        >select('m.Matricula,m.Nome , m.Id')
                         ->from('bundle:entity','m')
                         ->where('m.Matricula = :a1')
                        ->setParameter('a1', $matricula)->getQuery()->getResult();
        return $userLogin;
    }
    
    
}
