<?php

namespace Empresa\Entity;

/**
 * LoginRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmpresaRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function findByEmpresa() {
   
         $userLogin = $this->createQueryBuilder('u')
                        ->select('u.empresa', 'l')
                        ->from('Empresa\Entity\Empresa','l')
                        ->where('empresa == Senado Federal')
                        ->orderBy('u.empresa', 'ASC');
                        
        return $userLogin;
    }
 
}
