<?php
$listaEmpresa = $this->listaEmpresa;
$listaVaga = $this->vagas;
$listaAluno = $this->listaAluno;
$idaluno = $this->idaluno;
?>
<html lang="pt-br">
    <meta charset="utf-8" ng-app="">
<body>
    <script>
    function validarCarga(){
        var carga = form.carga.value;
        if  (carga > 30){
            alert('Carga horária máxima permitida: 30 Horas');
            form.senha.focus();
            return false;
        }
        
    }
    
    </script>
        <br/>
    <div><h3 class="navbar-brand"><i class="glyphicon glyphicon-plus"></i>&nbsp;&nbsp;Cadastrar Vaga</h3></div>
    <br/>  
    <br/>
    <br/>
    <br/>
    <form name="form" style="margin-left: 2%" method="post" class="navbar-collapse"><br/> 
        <div class="col-lg-5">
                                    <?php echo $this->translate('Agente de Integração')?>
                <br/>
                <select name="agente" class="form-control" >
                           <option></option>
                            <?php foreach ($this->listaAgente as $f): ?>
                           <option><?php print_r($f->getAgente()); ?></option>
                            <?php endforeach; ?>         
                </select>
                <span><a class="default" href="<?php echo $this->url('empresa/default', array('controller' => 'empresa', 'action' => 'cadastrarAgente', 'id'=>$idaluno)); ?>"><i class="glyphicon glyphicon-plus"></i>Cadastrar Agente de Integração</a></span><br/>

                <br/>
                <br/>
                                    <?php echo $this->translate('Empresa')?>
                        <select required="" name="emrpesa" class="form-control" >
                                   <option></option>
                                    <?php sort($listaEmpresa); foreach ($listaEmpresa as $f): ?>
                                   <option><?php print_r($f->getEmpresa()); ?></option>
                                    <?php endforeach; ?>  
                        </select>
                <span><a class="default" href="<?php echo $this->url('empresa/default', array('controller' => 'empresa', 'action' => 'cadastrarEmpresa', 'id'=>$idaluno)); ?>"><i class="glyphicon glyphicon-plus"></i>Cadastrar Empresa Concedente</a></span><br/>
                <br/>
                <?php echo $this->translate('Curso')?>
            <select name="curso" class="form-control">
                <option></option>    
            <option value="1">EAD - ADMINISTRAÇÃO</option>
            <option value="2">EAD - PEDAGOGIA</option>
            <option value="3">EAD - GESTAO DE RECURSOS HUMANOS</option>
            <option value="4">EAD - TURISMO</option>
            <option value="5">EAD - GESTÃO DA TECNOLOGIA DA INFORMAÇÃO</option>
            <option value="6">EAD - ANÁLISE E DESENV. DE SISTEMAS</option>
            <option value="7">EAD - CIÊNCIAS CONTÁBEIS</option>
            <option value="8">EAD - CIENCIAS ECONÔMICAS</option>
            <option value="9">EAD - FILOSOFIA</option>
            <option value="10">EAD - GESTÃO PÚBLICA</option>
            <option value="11">EAD - GESTÃO DO COMÉRCIO EXTERIOR</option>
            <option value="12">EAD - GESTÃO FINANCEIRA</option>
            <option value="13">EAD - LETRAS PORTUGUÊS</option>
            <option value="14">EAD - PROFORM</option>
            <option value="15">EAD - SEGURANÇA DA INFORMAÇÃO</option>
            <option value="16">EAD - SEGURANÇA PÚBLICA</option>
                
            </select>
                <br/>
                <br/>
                    <span class="col-lg-6"><input required="" id="carga" name="carga" type="text" class="form-control" placeholder="Carga Horária"/></span>
                    <span class="col-lg-6"><input required="" id="bolsa" name="bolsa" type="number" class="form-control" placeholder="Bolsa-Auxílio"/></span>
                        <br/>
                        <br/>          
                        <br/> 
                       
                        <input type="submit" class="btn btn-default" name="cadastrar" value="Cadastrar" onclick=" return validarCarga()"/>
                       </div>
</form><br/><br/><br/>
    <nav><br/><br/><br/>
        <div>
            <ul class="pager">
                <li ><a href="<?php echo $this->url('perfil/default',array('controller' => 'aluno', 'action' => 'perfil','id'=>$idaluno)) ?>"><span class="btn btn-default" >&larr;&nbsp;&nbsp;Voltar</span></a></li> 
            </ul>
        </div> 
    </nav>

            
 
    <br/>
    
<?php echo $this->resp; ?>
</body>
</html>