<html lang="pt-br">
<meta charset="utf-8">
<body> 
  <?php   $success = $this-> success ?>
   
<div class="navbar-collapse">
        <h3>Cadastro de Agente de Integração</h3>
    </div> 
<div class="thumbnail">
      <div class="caption">
<div class="navbar-collapse">
  
<form class="navbar-default" method="post">
    <div class="col-lg-4">
    <?php echo $this->translate('Agente de Integração')?><br/><input name="agente" type="text" class="form-control" required=""/><br/>
        <?php echo $this->translate('CNPJ')?><br/><input id="cnpj" name="cnpj" type="text" class="form-control" required=""/><br/>
            <?php echo $this->translate('Telefone')?><br/><input id="telefone" name="telefone" type="text" class="form-control" required=""/><br/>
            <input type="submit" class="btn btn-default" name="cadastrar" value="Cadastrar" />
    </div>
</form>

</div></div></div>

     <nav>
        <div>
            <ul class="pager">

                <li ><a href="<?php echo $this->url('vaga/default',array('controller' => 'index', 'action' => 'index','id'=>$this->idaluno)) ?>"><span class="btn btn-default" >&larr;&nbsp;&nbsp;Voltar</span></a></li> 
            </ul>
        </div> 
    </nav>
<?php echo $this->resp; ?>
</body>
</html>