<script>

$(document).ready(function(){
 $("#cadastrarEmpresaForm").validate({
        highlight: function(element) {
        $(element.form).find("." + element.id )
            .addClass("has-error")
            .removeClass("has-succes");
        $("em").css("color","red");
        $("."+element.id+"-valid").css("display","none");
        },
        unhighlight: function(element) {
        $(element.form).find("." + element.id)
            .removeClass("has-error")
            .addClass("has-success"); 
        $("."+element.id+"-valid").css({
            display: "inline",
            color: "green"
        });
        },
        errorElement: "em",
        messages: {
        empresa: 'Campo Obrigatório',
        cnpj: 'cnpj inválido',
        telefone: 'Telefone inválido',
        endereco: 'Campo Obrigatório',
        email:'Email inválido',
        responsavel:'Campo Obrigatório',
        tamanho: 'Campo Obrigatório',
        senha:'Campo Obrigatório',
        confirmarSenha: 'As senhas devem ser iguais (min. 6 carácteres)'
        },
        rules:{
        empresa: {
           required: true
        },
        cnpj: {
           required: true,
          rangelength: [14, 14],
          max: 99999999999999
        },
        telefone:{
            required: true,
            max: 99999999999999,
            min: 111111111
        },
        endereco:{
            required: true
        },
        email:{
            required: true,
            email: true
        },
        responsavel:{
            required: true
        },
        tamanho:{
            required: true
        },
           senha:{
            required: true,
             minlength : 6
        },
        confirmarSenha:{
            required: true,
            minlength : 6,
            equalTo : "#senha"
        }
        }
    });
});

</script>
<div class=" panel panel-primary">
    <div class="panel-heading">
        <?= 'Cadastro de Empresa'?>
    </div>
    <?php if($this->alerta): ?>
<div class="alert-danger" style=" text-align: center"><?php  echo $this->alerta; ?></div> 
<?php
endif;
    ?>
<div class="well well-sm"> Todos os campos são obrigatórios
</div>
    
    <form method="post" id="cadastrarEmpresaForm">
    <div class="col-lg-12">
        <div>
            <div class="col-sm-6 col-sm-offset-1 empresa">
                <label for="empresa"><?= $this->translate('Empresa')?></label><i style=" display: none;"  class=" empresa-valid glyphicon glyphicon-ok-circle"></i>
                <input id="empresa" name="empresa" type="text" class="form-control "  /><br/>
           </div>
            <div class="col-sm-4 cnpj">
                <label for="cnpj"><?= $this->translate('CNPJ')?></label><i style=" display: none;"  class=" cnpj-valid glyphicon glyphicon-ok-circle"></i>
                <input maxlength="14" id="cnpj" name="cnpj" type="text" class="form-control" /><br/>
            </div>
            <div class="col-sm-offset-1 col-sm-3 telefone">
                <label for="telefone"><?= $this->translate('Telefone')?></label><i style=" display: none;"  class=" telefone-valid glyphicon glyphicon-ok-circle"></i>
                <input name="telefone" id="telefone" type="tel" class="form-control" /><br/>
            </div>
        <div class="col-sm-4  endereco">
            <label for="endereço"><?= $this->translate('Endereço')?></label><i style=" display: none;"  class=" endereco-valid glyphicon glyphicon-ok-circle"></i>
            <input id="endereco" name="endereco" type="text" class="form-control" /><br/>
        </div>
         <div class="col-sm-3 email">
             <label for="email"><?= $this->translate('Email')?></label><i style=" display: none;"  class=" email-valid glyphicon glyphicon-ok-circle"></i>
            <input id="email" name="email"  class="form-control" /><br/>
         </div>
          <div class="col-sm-offset-1 col-sm-3 responsavel">
              <label for="responsavel"><?= $this->translate('Responsável')?></label><i style=" display: none;"  class=" responsavel-valid glyphicon glyphicon-ok-circle"></i>
            <input id="responsavel" name="responsavel"  type="text" class="form-control"/><br/>
         </div>
            <div class="col-sm-3  tamanho ">
                <label for="tamanho"><?= $this->translate('Tamanho da Empresa')?></label><i style=" display: none;"  class=" tamanho-valid glyphicon glyphicon-ok-circle"></i>
                <select id="tamanho" name="tamanho" class="form-control">
                <option></option>
                <option>Micro</option>
                <option>Pequena</option>
                <option>Média</option>
                <option>Grande</option>
                </select>
            </div>
               <div class="col-sm-2  senha">
                <label for="senha"><?= $this->translate('Senha')?></label><i style=" display: none;"  class=" senha-valid glyphicon glyphicon-ok-circle"></i>
                <input id="senha" name="senha" type="password" class="form-control "  /><br/>
           </div>
            <div class="col-sm-2 confirmarSenha">
                <label for="confirmarSenha"><?= $this->translate('Confirmar Senha')?></label><i style=" display: none;"  class=" confirmarSenha-valid glyphicon glyphicon-ok-circle"></i>
                <input id="confirmarSenha" name="confirmarSenha" type="password" class="form-control" /><br/>
            </div>
        </div>  
    </div>
    <div class="well-lg col-sm-offset-1">
    <button type="submit" class="btn btn-primary" name="cadastrar" value="Cadastrar" ><i class="fa fa-check fa-2x pull-left"></i> Finalizar<br>Cadastro</button>
    </div>  
</form>
</div>
<?= $this->resp; ?>
