<html lang="pt-br">
<meta charset="utf-8">
<body>
  <?php   $success = $this-> success ?>
    <h3 class="navbar-brand"><i class="glyphicon glyphicon-plus"></i>&nbsp;&nbsp;Cadastro de Empresa</h3>
<br/>
<br/><br/>

<br/>
<br/>
<div class="navbar-collapse" id="aluno">
  
<form class="navbar-default" method="post">
    <div class="col-lg-4">
    <?php echo $this->translate('Empresa')?><br/><input name="empresa" type="text" class="form-control" required=""/><br/>
        <?php echo $this->translate('CNPJ')?><br/><input id="cnpj" name="cnpj" type="text" class="form-control" required=""/><br/>
            <?php echo $this->translate('Telefone')?><br/><input id="telefone" name="telefone" type="text" class="form-control" required=""/><br/>
            <input type="submit" class="btn btn-default" name="cadastrar" value="Cadastrar" />
    </div>
</form>
   
</div>
<nav>
        <div style=" margin-top: 15%">
            <ul class="pager">

                <li ><a href="<?php echo $this->url('vaga/default',array('controller' => 'index', 'action' => 'index','id'=>$this->idaluno)) ?>"><span class="btn btn-default" >&larr;&nbsp;&nbsp;Voltar</span></a></li> 
            </ul>
        </div> 
    </nav>
<?php echo $this->resp; ?>
</body>
</html>