<html lang="pt-br">
<meta charset="utf-8">
<body>
  <?php   $success = $this-> success ?>
    <h3 class="navbar-brand"><i class="glyphicon glyphicon-plus"></i>&nbsp;&nbsp;Cadastro de Empresa</h3>
<br/>
<br/><br/>

<br/>
<br/>
<div class="navbar-collapse" id="aluno">
  
<form class="navbar-default" method="post">
    <div class="col-lg-4">
    <?php echo $this->translate('Empresa')?><br/><input name="empresa" type="text" class="form-control" /><br/>
        <?php echo $this->translate('CNPJ')?><br/><input name="cnpj" type="text" class="form-control" /><br/>
            <?php echo $this->translate('Telefone')?><br/><input name="telefone" type="text" class="form-control"/><br/>
            <input type="submit" class="btn btn-default" name="cadastrar" value="Cadastrar" />
    </div>
</form>
   
</div>

<?php echo $this->resp; ?>
</body>
</html>