<body>
  <?php   $success = $this-> success ?>
    <h3 class="navbar-brand"><i class="glyphicon glyphicon-plus"></i>&nbsp;&nbsp;Cadastro de Empresa</h3>
<br/>
<br/><br/>

<br/>
<br/>
<div class="navbar-collapse" id="aluno">
  
<form class="navbar-default" method="post">
    <?php echo $this->translate('Empresa')?><br/><input name="empresa"type="text" class="navbar-default   " /><br/>
        <?php echo $this->translate('CNPJ')?><br/><input name="cnpj" type="text" class="navbar-default" /><br/>
            <?php echo $this->translate('Telefone')?><br/><input name="telefone" type="text" class="navbar-default"/><br/>
            <input type="submit"class="navbar-btn" name="cadastrar" value="Cadastrar" type="button"/>
</form>
   
</div>

<?php echo $this->resp; ?>
</body>