<script>
$(function () {
 
  $("#rateYo").rateYo({
 
    rating    : 4.3,
    spacing   : "2px",
    starWidth: '12px',
    multiColor: {
        
      "startColor": "#FF0000", //RED
      "endColor"  : "#ffcf18"  //GREEN
    }
  });
 
});
</script>
<div class=" panel panel-primary">
    <div class="panel-heading">
       <?= $this->translate("Perfil da emrpesa")?>
    </div>
    <div style="color:  #ffcf18"class="caption" >
    <ul class="nav  nav-tabs" >
        <li class="  active" role="presentation"><a><label><?= $this->translate("Painel")?></label></a></li>
        <li role="presentation"><a href="<?= $this->url('painelEmpresa/default',['controller'=>'empresa', 'action'=>'mensagens','id'=>'1'])?>"> <i class="fa fa-envelope-o"></i> <?= $this->translate("Mensagens")?></a></li>
   </ul>
</div>
<div class="row">
    <div class="caption">
        <?php if($this->identidade): foreach ($this->identidade as $l):  $idEmpresa = $l->getIdempresa(); ?>
         <?=
        '<div class="navbar pager">'.
            '<img src="'.$this->basePath('img/empresa.png').'" class="img-circle " alt="Cinque Terre" width="70" height="70">'.
        '<h3 class="pager">'.  $l->getEmpresa().'</h3>'?>
            <span class=" center-block" id="rateYo"></span>
            <?=
        '<p class="pager"><label>CNPJ:</label>'.  $l->getCnpj().'<br/>'
            . '<label>Responável: </label> '. $l->getResponsavel().' '
            . '<label> Telefone: </label> '.  $l->getTelefone().'<br/></div> ';
        ?>
        <?php endforeach; endif;?>
    </div>
 </div>
 <div >
  <div >
    <div>
        <div class="caption">
            <div class="caption">
                <ul class="nav  nav-tabs" style=" background-color: #f4f4f4">
                    <li role="presentation" ><a href="<?= $this->url('painelEmpresa/default', ['controller'=>'empresa','action'=>'painelEmpresaEstagiando','id'=>'1'])?>"><?= $this->translate("Estagiando ")?><span class="label label-default"> <?= count($this->listaVagaEstagiando)?></span></a></li>
                    <li role="presentation" ><a href="<?= $this->url('painelEmpresa/default', ['controller'=>'empresa','action'=>'painelEmpresaEncerrado','id'=>'1'])?>"><?= $this->translate("Encerrado ")?><span class="label label-default"> <?= count($this->vagas) - count($this->listaVagaEstagiando)  ?></span></a></li>
                    <li  class="  active" role="presentation"><a href="#"><label><?= $this->translate("Todos os estágios ")?></label>  <span class="label label-primary"> <?= count($this->vagas) ?></span> </a></li>
                    <li  role="presentation" ><a href="<?= $this->url('painelEmpresa/default', ['controller'=>'empresa','action'=>'painelEmpresaContratosVencendo','id'=>'1'])?>"><?= $this->translate("Contratos vencendo ")?><span class="label label-default"> <?= count($this->listaContratosVencendo)?></span></a></li>
                </ul>
            </div>
<?php if ($this->vagas){?>
            <form method="post" >
   
        <table class="table" >
            <tr>
                <th><?= $this->translate("Aluno")?></th>
                <th><?= $this->translate("Agente de Integração")?></th>
                <th><?= $this->translate("Processo")?></th>
            </tr>
                <?php foreach ($this->pagination   as $l):?>
                <?php 

             if($l->getRecisao() !=(null)){ ?>
            <tr class="table" style="background:  #b70909; color: white">
                <td><?= $l->getAluno()?></td>
                <td><?= $l->getAgente(); ?></td>
                <td><a href="<?= $this->url('painelEmpresa/default',['controller'=>'empresa', 'action'=>'processo','id'=>$l->getIdalunovaga()])?>"><i class="fa fa-plus"></i></a></td>
             </tr>
                <?php } ?>
                <?php  if($l->getSituacao() =='1'){ ?>
             <tr class="table" style="background: #cafaca; ">
                <td><?= $l->getAluno()?></td>
                <td><?= $l->getAgente(); ?></td>  
                <td><a href="<?= $this->url('painelEmpresa/default',['controller'=>'empresa', 'action'=>'processo','id'=>$l->getIdalunovaga()])?>"><i class="fa fa-plus"></i></a></td>
            </tr> <?php } ?>
                <?php
                endforeach;?>
        </table>   
              <br/>
    <nav aria-label="Page navigation">
        <ul  class="pager">
            <li 
                <?php  if ($this->pageNumber == 1|| $this->pageNumber == 0 ){ ?>
                <?= "class='disabled'". "style='pointer-events: none'";}?>
            >
            <a href="<?php if ($this->pageNumber > 1){echo $this->pageNumber - 1; }?>" aria-label="Previous">
                <span aria-hidden="true"><i class="glyphicon glyphicon-chevron-left"> </i></span>
            </a>
              </li>
            <li <?php if ($this->pageNumber >= $this->count){ ?>
                <?= "class='disabled'". "style='pointer-events: none'";}?>>     
            <a href="<?= $this->pageNumber + 1?>" aria-label="Next">
                <span aria-hidden="true"><i class="glyphicon glyphicon-chevron-right"></i></span>
            </a>
            </li> 
       </ul>
    </nav>
              <div class="pager"><?php echo $this->pageNumber.' de '.$this->count;?></div>   
              
</form>
            <?php }
            else{?> 
     <div class=" thumbnail">
        <div class="alert-danger " style="margin: initial">
                   <br/>
                   <h4 style="text-align: center">Nenhum estágio lançado</h4><br/>      
        </div>
      </div> <?php };?>   
      </div>
       
      </div>
    </div>
  </div>
      <div class="well-lg ">
        <a href="<?= $this->url('painelEmpresa/default', array('controller'=>'empresa', 'action'=>'editarEmpresa', 'id'=>'Y E S H U A'))?>">
            <span class="btn btn-primary  ">
                <i class=" fa fa-edit fa-2x pull-left"></i><?= $this->translate("Editar").'<br>'. $this->translate("Perfil")?>
            </span>
        </a>
    </div>
</div>
<?= $this->resp; ?>
