<script>
$(function () {
 
  $("#rateYo").rateYo({
 
    rating    : 4.3,
    spacing   : "2px",
    starWidth: '12px',
    multiColor: {
        
      "startColor": "#FF0000", //RED
      "endColor"  : "#ffcf18"  //GREEN
    }
  });
 
});
</script>
<div class=" panel panel-primary">
        <div class="panel-heading">
           <?= $this->translate("Perfil da emrpesa")?>
        </div>
    <div>
        <div class="caption">
            <ul class="nav  nav-tabs" style=" background-color: #f4f4f4">
                <li class="  active" role="presentation"><a><label><?= $this->translate("Painel")?></label></a></li>
                 <li role="presentation"><a href="<?= $this->url('painelEmpresa/default',['controller'=>'empresa', 'action'=>'mensagens','id'=>'1'])?>"> <i class="fa fa-envelope-o"></i> <?= $this->translate("Mensagens")?></a></li>
        
            </ul> 
        </div>
    </div>
<div class="caption">
    <?php if($this->empresaSelect): foreach ($this->empresaSelect as $l):  $idEmpresa = $l->getIdempresa(); ?>
        <?=
        '<div class="navbar pager">'.
            '<img src="'.$this->basePath('img/empresa.png').'" class="img-circle " alt="Cinque Terre" width="70" height="70">'.
        '<h3 class="pager">'.  $l->getEmpresa().'</h3>'?>
            <span class=" center-block" id="rateYo"></span>
            <?=
        '<p class="pager"><label>CNPJ:</label>'.  $l->getCnpj().'<br/>'
            . '<label>Responável: </label> '. $l->getResponsavel().' '
            . '<label> Telefone: </label> '.  $l->getTelefone().'<br/></div> ';
        ?>
    <?php endforeach; endif;?>
</div>
<div class="caption">
    <div class="caption">
        <ul class="nav  nav-tabs" style=" background-color: #f4f4f4">
            <li role="presentation" ><a href="<?= $this->url('painelEmpresa/default', ['controller'=>'empresa','action'=>'painelEmpresaEstagiando','id'=>'1'])?>"><?= $this->translate("Estagiando ")?><span class="label label-default"> <?= count($this->listaVagaEstagiando)?></span></a></li>
            <li role="presentation" ><a href="<?= $this->url('painelEmpresa/default', ['controller'=>'empresa','action'=>'painelEmpresaEncerrado','id'=>'1'])?>"><?= $this->translate("Encerrado ")?><span class="label label-default"> <?= count($this->listaVaga) - count($this->listaVagaEstagiando)  ?></span></a></li>
            <li role="presentation"><a href="<?= $this->url('painelEmpresa/default', ['controller'=>'empresa','id'=>'1'])?>"><?= $this->translate("Todos os estágios ")?><span class="label label-default"> <?= count($this->listaVaga) ?></span> </a></li>
            <li class="  active" role="presentation" ><a href=""><label><?= $this->translate("Contratos vencendo ")?></label> <span class="label label-warning "> <?= count($this->listaContratosVencendo)?></span></a></li>
           
        </ul> 
    </div>
   
      <form method="post" > 
     <?php if ($this->listaContratosVencendo){?>
        <table class="table navbar-default" >
        <tr>
            <th><?= $this->translate("Processo")?></th>
            <th><?= $this->translate("Inicio")?></th>
            <th><?= $this->translate("Fim")?></th>
        </tr>
        
   <?php foreach ($this->pagination   as $l):
        ?>
        <tr class="table" style="background: #fff194 ">
             <td><?= $l[0]->getRelatorio()?></td>
             <td><?= date_format($l[0]->getInicio(), 'd/m/Y')?></td>
            <td><?= date_format($l[0]->getFim(), 'd/m/Y')?></td>
            <td><a href="<?= $this->url('painelEmpresa/default',['controller'=>'empresa', 'action'=>'processo','id'=>$l[0]->getIdalunoDocumento()])?>"><i class="fa fa-plus"></i></a></td>
        
        </tr> <?php endforeach;?>
        </table><br/>  
    <nav aria-label="Page navigation">
        <ul  class="pager">
            <li 
                <?php  if ($this->pageNumber == 1|| $this->pageNumber == 0 ){ ?>
                <?= "class='disabled'". "style='pointer-events: none'";}?>
            >
            <a href="<?php if ($this->pageNumber > 1){echo $this->pageNumber - 1; }?>" aria-label="Previous">
                <span aria-hidden="true"><i class="glyphicon glyphicon-chevron-left"> </i></span>
            </a>
              </li>
            <li <?php if ($this->pageNumber >= $this->count){ ?>
                <?= "class='disabled'". "style='pointer-events: none'";}?>>     
            <a href="<?= $this->pageNumber + 1?>" aria-label="Next">
                <span aria-hidden="true"><i class="glyphicon glyphicon-chevron-right"></i></span>
            </a>
            </li> 
       </ul>
    </nav>
            <div class="pager">
               <?= $this->pageNumber.' de '.$this->count;?>
            </div>     
        </form>
            <?php } else{ ?> 
    <div class=" thumbnail ">  
        <div class="alert-danger" style="margin: initial">
            <br/>
            <h4 style="text-align: center"><?= $this->translate("Nenhum documento vencendo!")?></h4><br/>      
        </div>
    </div>
        <?php }?>   
</div> 
    <div class="well-lg ">
        <a href="<?= $this->url('painelEmpresa/default', array('controller'=>'empresa', 'action'=>'editarEmpresa', 'id'=>'Y E S H U A'))?>">
            <span class="btn btn-primary  ">
                <i class=" fa fa-edit fa-2x pull-left"></i><?= $this->translate("Editar").'<br>'. $this->translate("Perfil")?>
            </span>
        </a>
    </div>
</div> 
<?= $this->resp; ?>
