<?php echo $this->doctype(); 
?>

<html lang="pt-br">
    <!--
    Autor: Romário Macedo Portela
    Estudante de Análise e Desenv. de Sistemas
    Framework utilizado: Zend 2
    -->
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('UCB -  '. $this->translate('Projem'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => '', 'href' => $this->basePath() . ''))
                                
                        ->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
                        ?>
                         

        <!-- Scripts -->
        <?php echo $this->headScript()
             
            ->prependFile($this->basePath('js/Chart.min.js'))
            ->prependFile($this->basePath('js/Mascaras.js'))
            ->prependFile($this->basePath('js/jquery.maskedinput.js'))
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body  style=" background-image: url('img/UCBLogo.jpg'); background-position: center;  background-repeat: no-repeat; background-attachment: fixed; background-color: #cfe6ff">
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"> <?php echo $this->translate('Início') ?></a>
                    
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="dropdown navbar-inverse active">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="glyphicon glyphicon-book"></i> Aluno<span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                   <li><a href="<?php echo $this->url('perfil') ?>"><i class="glyphicon glyphicon-user"></i> <?php echo $this->translate('Perfil do Aluno') ?></a></li>    
                                   <li><a href="<?php echo $this->url('aluno/default',['controller'=>'aluno','action'=>'cadastrar','id'=>'0']) ?>"><i class="glyphicon glyphicon-plus"></i> <?php echo $this->translate('Cadastrar Aluno') ?></a></li>    
                                </ul>
                        </li> 
                        
                       <li class="dropdown navbar-inverse active">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class=" glyphicon glyphicon-briefcase"></i> Empresa<span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li><a href="<?php echo $this->url('cadastrarEmpresa/default', ['controller'=>'empresa', 'action' =>'cadastrarEmpresa','id'=>'0']) ?>"><i class=" glyphicon glyphicon-plus"></i> <?php echo $this->translate('Cadastrar Empresa') ?></a></li>
                                    <li><a href="<?php echo $this->url('cadastrarEmpresa/default', ['controller'=>'empresa', 'action' =>'cadastrarAgente','id'=>'0']) ?>"><i class=" glyphicon glyphicon-plus"></i> <?php echo $this->translate('Cadastrar Agente') ?></a></li>
                                
                                </ul>
                        </li> 
                        <li class="active"><a href="<?php echo $this->url('relatorio') ?>"><i class="glyphicon glyphicon-stats"></i> <?php echo $this->translate('Relatórios') ?></a></li>
                         
                    </ul>
                    
                    <ul class=" nav navbar-nav navbar-right">
                        <li> <a aria-haspopup="true" style="color:  #e2a8b3; " href="<?php echo $this->url('sair', array(
              'action' => 'logout'
                            )) ?>">Sair&nbsp;&nbsp;<i class="glyphicon glyphicon-log-out"></i></a></li>
                    </ul>
                    <ul class=" nav navbar-nav navbar-right">
                       <li class="dropdown navbar-inverse">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Área Administrativa<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="<?php echo $this->url('paginator', ['controller'=>'administrador', 'action' =>'aluno']) ?>"> <?php echo $this->translate('Alunos') ?></a></li> 
                            <li><a href="<?php echo $this->url('paginator', ['controller'=>'administrador', 'action' =>'empresa']) ?>"> <?php echo $this->translate('Empresa Concedente') ?></a></li>
                            <li><a href="<?php echo $this->url('paginator', ['controller'=>'administrador', 'action' =>'agente']) ?>"> <?php echo $this->translate('Agente de Integração') ?></a></li>
                            <li><a href="<?php echo $this->url('usuarios') ?>"> <?php echo $this->translate('Acessos') ?></a></li>
                        
                        </ul>
                    </li> 
                    </ul>
                </div><!--/.nav-collapse -->
                
            </div>
            
                    
             
            
        </nav>
  
        <div class="container" style=" background-color: #f7f8f9">
            <?php echo $this->content; ?>
            <footer style="background-color:  #ffffff; height: 150px"><hr>
                <p style="text-align: center">&copy; <?php echo date('Y') ?> <a href="http://www.ucb.br/Cursos/58ProjetoDeEmpregabilidadeProjem/">PROJEM - UCB</a>. </p>
               
              <p style="color: #b2b2b2; text-align: center"><b>Gestor:</b> Wagner Soares <br/>
                  <b>Contatos:</b> projem@ucb.br / 3356-9076 3356-9483 <br/>
                  <b>Localização:</b> Campus I, Bloco L, Sala 008</P><br/><br/><br/>
        </footer>
            
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
        
    </body>
    
</html>
