<?=  $this->doctype(); ?>
<html lang="pt-br">
    <head>
        <meta charset="utf-8">
    <?= $this->headTitle('UCB -  '. $this->translate('Projem'))->setSeparator(' - ')->setAutoEscape(false) ?>
    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>
    <?= $this->headLink(array('rel' => 'shortcut icon', 'type' => '', 'href' => $this->basePath() . ''))
                    ->prependStylesheet($this->basePath('css/bootstrap.css'))
                    ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
                    ->prependStylesheet($this->basePath('css/bootstrap-datepicker.min.css'))
                    ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                    ->prependStylesheet($this->basePath('fonts/FontAwesome.otf'))
                    ->prependStylesheet($this->basePath('css/font-awesome.min.css'))
                    ->prependStylesheet($this->basePath('css/bootstrap-toggle.min.css'))
                    ->prependStylesheet($this->basePath('css/style.css'))
    ?>
    <?= $this->headScript()
                    ->prependFile($this->basePath('js/jquery.validate.js'))
        ->prependFile($this->basePath('js/jquery.tablesorter.min.js'))
        ->prependFile($this->basePath('js/jquery.jquery-latest.js'))
                    ->prependFile($this->basePath('js/bootstrap.min.js'))
                    ->prependFile($this->basePath('js/bootstrap-toggle.min.js'))
                    ->prependFile($this->basePath('js/locales/bootstrap-datepicker.pt-BR.js'))
                    ->prependFile($this->basePath('js/bootstrap-datepicker.js'))
                    ->prependFile($this->basePath('js/bootstrap-datepicker-globalize.js'))
                    ->prependFile($this->basePath('js/jquery.min.js'))
                    ->prependFile($this->basePath('js/pace.js'))
                    ->prependFile($this->basePath('js/Chart.min.js'))
                    
    ;?>
    </head>
    
    <body style="  background-color: #f2f2f2">
	<nav  class="navbar navbar-fixed-top navbar-inverse" role="navigation">
            <div class="container navbar-inverse navbar-default " style=" background-color: #0089cd" >
                <div class="navbar-header  active">
                    <button type="button" class="navbar-toggle  active" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand  active" href="<?php echo $this->url('home') ?>"><i style=" font-size: 23px" class=" fa fa-home"></i></a>
                    
                </div>
                <div  class="collapse navbar-collapse ">
                    <ul  class="nav navbar-nav  ">
                        <li class="dropdown  active">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class=" fa fa-mortar-board"></i> Aluno<span class="caret"></span></a>
                                <ul  class="dropdown-menu nav" >
                                    <li  ><a href="<?php echo $this->url('perfilPresencial') ?>">  <?php echo $this->translate('Perfil do Aluno') ?></a></li>  
                                    <li> </li>
                                   <li  ><a href="<?php echo $this->url('aluno/default',['controller'=>'alunoPresencial','action'=>'cadastrar','id'=>'0']) ?>"> <?php echo $this->translate('Cadastro') ?></a></li>    
                                </ul>
                        </li> 
                        
                       <li class="dropdown active">
                           <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class=" fa fa-briefcase"></i> Empresa<span class="caret"></span></a>
                                <ul  class="dropdown-menu nav  " >
                                    <!--<li><a href="<?php // echo $this->url('buscarEmpresa') ?>"><i class="glyphicon glyphicon-user"></i> <?php // echo $this->translate('Perfil da Empresa') ?></a></li>-->
                                    <li ><a href="<?php echo $this->url('buscarEmpresa') ?>"> <?php echo $this->translate('Perfil da Empresa') ?></a></li>
                                    <li  ><a href="<?php echo $this->url('cadastrarEmpresa/default', ['controller'=>'empresa', 'action' =>'cadastrarEmpresa','id'=>'0']) ?>"><?php echo $this->translate('Cadastrar Empresa') ?></a></li>
                                    <li ><a href="<?php echo $this->url('cadastrarEmpresa/default', ['controller'=>'empresa', 'action' =>'cadastrarAgente','id'=>'0']) ?>"> <?php echo $this->translate('Cadastrar Agente') ?></a></li>
                                </ul>
                        </li>
                      
                        
                        <li class="dropdown active">
                          
                            <a href="<?php echo $this->url('relatorioPresencial') ?>"><?php echo $this->translate('Relatórios') ?></a>
                                 
                       </li>  
                         <li class="dropdown active ">
                           <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i></i> Vagas<span class="caret"></span></a>
                              <ul  class="dropdown-menu nav  " >
                                    <li  ><a href="<?php echo $this->url('oportunidades') ?>"><?php echo $this->translate('Nova Vaga') ?></a></li>
                                    <li  ><a href="<?php echo $this->url('perfilOportunidade/default',(['controller'=>'oportunidade', 'action'=>'oportunidade', 'page'=>'1'])) ?>"><?php echo $this->translate('Oportunidades') ?></a>
                                    </li>
                                </ul>
                        </li> 
                    </ul>
                    <ul class=" nav navbar-nav navbar-right">
                        <li> <a aria-haspopup="true" style="color:  #e2a8b3; " href="<?php echo $this->url('sair', array(
              'action' => 'logout'
                            )) ?>">Sair&nbsp;&nbsp;<i class="glyphicon glyphicon-log-out"></i></a></li>
                    </ul>
                    <ul>   
                    </ul>
                </div><!--/.nav-collapse --> 
            </div>     
        </nav>
</div>   
     <br/><br/><br/>
        <div>
            <div class=" container" >
                <?= 
                    $this->content;
                    $this->inlineScript(); 
                ?>
                <footer class="pager"style=" background-color:white; height: 100px; color: #0089cd">
                    <hr>
               <?='&copy; Romário Macedo - '. date('Y'); ?>
                    <hr>
                </footer>
            </div>
        </div> 
</html>
