<nav  class="navbar navbar-fixed-top navbar-inverse" role="navigation">
            <div class="container navbar-inverse navbar-default " >
                <div class="navbar-header ">
                    <button type="button" class="navbar-toggle " data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand " href="<?php echo $this->url('home') ?>"><i style=" font-size: 23px" class=" fa fa-home"></i></a>          
                </div>
                <div  class="collapse navbar-collapse ">
                    <ul  class="nav navbar-nav  ">
                        <li class="dropdown ">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class=" fa fa-mortar-board"></i> Aluno<span class="caret"></span></a>
                                <ul  class="dropdown-menu nav" >
                                    <li><a href="<?= $this->url('perfilPresencial') ?>">  <?= $this->translate('Perfil do Aluno') ?></a></li>  
                                    <li></li>
                                    <li><a href="<?= $this->url('aluno/default',['controller'=>'alunoPresencial','action'=>'cadastrar','id'=>'0']) ?>"> <?php echo $this->translate('Cadastro') ?></a></li>    
                                </ul>
                        </li> 
                        
                       <li class="dropdown ">
                           <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class=" fa fa-briefcase"></i> Empresa<span class="caret"></span></a>
                                <ul  class="dropdown-menu nav  " >
                                    <li><a href="<?= $this->url('buscarEmpresa') ?>"> <?= $this->translate('Perfil da Empresa') ?></a></li>
                                    <li><a href="<?= $this->url('cadastrarEmpresa/default', ['controller'=>'empresa', 'action' =>'cadastrarEmpresa','id'=>'0']) ?>"><?php echo $this->translate('Cadastrar Empresa') ?></a></li>
                                    <li><a href="<?= $this->url('cadastrarEmpresa/default', ['controller'=>'empresa', 'action' =>'cadastrarAgente','id'=>'0']) ?>"> <?php echo $this->translate('Cadastrar Agente') ?></a></li>
                                </ul>
                        </li>            
                        <li class="dropdown">
                            <a href="<?= $this->url('relatorioPresencial') ?>"><?php echo $this->translate('Relatórios') ?></a>   
                       </li>  
                    </ul>
                    <ul class=" nav navbar-nav navbar-right">
                        <li> <a aria-haspopup="true" style="color:  #e2a8b3; " href="<?php echo $this->url('sair', array(
              'action' => 'logout'
                            )) ?>">Sair&nbsp;&nbsp;<i class="glyphicon glyphicon-log-out"></i></a></li>
                    </ul>
                </div><!--/.nav-collapse --> 
            </div>     
</nav><?= '<br><br><br>'?>