<html>   
<div class=" nav row" style=" background-color: #1989f1">
     <h4 style="color: white; text-align: center">Nova Oportunidade</h4>
  </div>
<div  class="nav">
      <div class="caption">
          <div class="row">
            <div>
                <div class="" style=" ">
                <div class="caption">
                    <ul class="nav  nav-tabs" style=" background-color: #f4f4f4">
                   
                        <li class="  active" role="presentation"><a><label>Cadastrar Vaga</label></a></li>
                      
                    </ul> 
                </div>
              </div>
            </div>
        </div>  
      </div>
</div><br/>
    <div  style=" height: 1000px">
        <form method="post">
        <div class="thumbnail col-lg-8" style=" height:800px; background-color: #f5fef1">
   
       <div class="pager"><label>Informações da vaga</label></div>
         
        <div class=" nav-tabs" style="background-color: #1989f1; height: 3px"></div>
        *
           <div class="input-group">
               <span class="input-group-addon"><label>Empresa</label></span>
            <select name="empresa" class="form-control" required="">
             <?php foreach ( $this->listaEmpresa as $l):?>
                <option><?php echo $l->getEmpresa()?></option>
              <?php endforeach;?>
                            </select>
            </div><br>
            
            <div class="input-group">
                <span class="input-group-addon"><label>Título da vaga</label></span>
                <input name="cargo" type="text" class="form-control " required="">
            </div>
            <br>
             <div class="input-group">
                 <span class="input-group-addon"><label>Tipo da vaga</label></span>
            <select name="tipo" class="form-control" required="">
             
                <option> Estágio</option>
                <option> CLT</option>
                <option> Treinee</option>
              
                            </select>
            </div><br>
            <div class="input-group">
                <span class="input-group-addon"><label>Número de vagas</label></span>
                <input name="numeroVaga" type="text" class="form-control" required="">
            </div>
            <br/>
            <div class="input-group">
                <span class="input-group-addon"><label>Descrição</label></span>
                <textarea name="descricao" style=" height:200px" class=" ckeditor" required="" placeholder="Atividades à serem desenvolvidas no estágio, Carga horária..."></textarea>
            </div><br/><br/>
            
            
            
             
    <div class=" nav-tabs" style="background-color:   #1989f1; height: 3px"></div>
        <br/><br/>
        
       
    </div>
    


    <div class="thumbnail col-lg-4" style=" height: 800px; background-color: #f5fef1">
      
       <div class="pager"><label> Área da vaga</label></div>
        
         <div class=" nav-tabs" style="background-color:   #1989f1; height: 3px; font-size: 5px"></div>
            * <br/>             
           
            <div >
                <select multiple="multiple" id="my-select" name="my-select[]"> 
                    <optgroup label='Graduação Presencial'>
                    <?php foreach ( $this->listaCurso as $l):?>
                        <option value="<?php echo $l->getCurso()?>"> <?php echo $l->getCurso()?></option>
                    <?php endforeach;?>
                    </optgroup>
                        
                </select>
            </div><br/><br/>
            <div >
                <select multiple="multiple" id="my-selectEAD" name="my-select[]"> 
                    <optgroup label='Graduação EAD'>
                    <?php foreach ( $this->listaCursoEAD as $l):?>
                        <option value="<?php echo $l->getCurso()?>"> <?php echo $l->getCurso()?></option>
                    <?php endforeach;?>
                    </optgroup>
                        
                </select><br/><br/>
               
            </div><br/><br/><br/><br/>
            
      <div class=" nav-tabs" style="background-color:   #1989f1; height:3px"></div>
      <script>
        $('#my-select').multiSelect({ selectableOptgroup: true });
        $('#my-selectEAD').multiSelect({ selectableOptgroup: true });
        
    </script> 
    
    </div>
            
            <div class="pager"> <input type="submit" style=" background-color: #1989f1; color: white" class="btn " name="cadastrar" value="Salvar"></div>
        </form>
    </div>



    
</body></html>