
<html lang="pt-br">
    <head>
        <title>Perfil</title>
        <meta charset="utf-8">
        
    </head>
<body >
    <script>
     
    </script>
     <div class=" nav row" style=" background-color: #1989f1">
   
     <h4 style="color: white; text-align: center"> Oportunidade</h4>
  
 </div>
     <div class="row" >
            <div>
                <div class="" style=" ">
                <div class="caption">
                    <ul class="nav  nav-tabs" style=" background-color: #f4f4f4">
                        <li class="  active" role="presentation"><a href=""><label>Oportunidade Info</label></a></li>
                        
                    </ul> 
                </div>
              </div>
            </div>
        </div>
    <div>
        
        <table class=" table" >
            
            
           
            <?php foreach ($this->oportunidade as $l):?>
            <?php if(date_format($l->getData(), 'd/m/Y')== date('d/m/Y')):?>
            <div class=" pager thumbnail " style="  background-color:  #f5fef1"  >
                        <div class=" nav-tabs" style="background-color:  #20af05; height: 3px"></div>
                        <h4 style=" color: #0044cc "><?php echo "Hoje";?></h4>
                    <h3> <?php echo $l->getCargo();?>   </h3>

                    <label ><?php echo $l->getEmpresa();?></label><br/>
                    <i class=" fa fa-map-marker"></i> <span style=" color: #808080"> Brasília - DF</span><br/><br/>
                    
                    <div class=" nav-tabs" style="background-color:  #20af05; color: white"><label>Descrição</label></div>
                    <div  style="text-align: left"><?php echo $l->getDescricao();?></div><br/>
                    
                    <div class=" nav-tabs" style="background-color:  #20af05; color: white"><label>Área</label></div>
                    
                    <div  style="text-align: left"><?php echo $l->getCurso();?></div>
                    <label>Número de vagas</label>
                    <div  ><?php echo $l->getNumeroVaga();?></div><br/>
                    <button  style=" height:25px; width:90px; color: white; background-color:   #1989f1; border-radius: 20px"><i class=" fa fa-edit" style=" height: 3px;   color: white"></i> Editar</button>
                    <button  style=" height:25px; width:90px; color: white; background-color:    #c30202; border-radius: 20px"><i class=" fa fa-remove" style=" height: 3px;   color: white"></i> Excluir</button><br/> <br/>
                    
                    <div class=" nav-tabs" style="background-color:  #20af05; height: 3px"></div>
                    </div>
            <?php else:
                ?>
                    <div class=" pager thumbnail" style=" background-color:#f5fef1"  >
                        <div class=" nav-tabs" style="background-color:   #1989f1; height: 3px"></div>
                        <h4 style=" color: #0044cc "><?php echo date_format($l->getData(), 'd/m/Y');?></h4>
                    <h3> <?php echo $l->getCargo();?>   </h3>

                    <label ><?php echo $l->getEmpresa();?></label><br/>
                    <i class=" fa fa-map-marker"></i> <span style=" color: #808080"> Brasília - DF</span><br/><br/>
                    <div class=" nav-tabs" style="background-color:  #1989f1; color: white"><label>Descrição</label></div>
                    <div  style="text-align: left"><?php echo $l->getDescricao();?></div><br/>
                    
                    <div class=" nav-tabs" style="background-color:  #1989f1; color: white"><label>Área</label></div>
                    
                    <div  style="text-align: left"><?php echo $l->getCurso();?></div>
                    <label>Número de vagas</label>
                    <div  ><?php echo $l->getNumeroVaga();?></div><br/>
                   <button  style=" height:25px; width:90px; color: white; background-color:   #1989f1; border-radius: 20px"><i class=" fa fa-edit" style=" height: 3px;   color: white"></i> Editar</button>
                    <button  style=" height:25px; width:90px; color: white; background-color:    #c30202; border-radius: 20px"><i class=" fa fa-remove" style=" height: 3px;   color: white"></i> Excluir</button><br/> <br/>
                    <div class=" nav-tabs" style="background-color:  #1989f1; height: 3px"></div>
                    </div>
            <?php
            endif;
            endforeach;?>
            
            
            
        </table>
        
        
    </div>
         
<?php echo $this->resp; ?>
</body>
</html>