<html lang="pt-br">
    
    <!--
    Autor: Romário Macedo Portela
    Estudante de Análise e Desenv. de Sistemas
    Framework utilizado: Zend 2
    -->
    <head>  
    </head> 
    <body>    
   <div class=" nav row" style=" background-color: #1989f1">
   
     <h4 style="color: white; text-align: center">Atualizar dados</h4>
  
 </div>
         <div class="row" >
            <div>
                <div class="" style=" ">
                <div class="caption">
                    <ul class="nav  nav-tabs" style=" background-color: #f4f4f4">
                        <li   role="presentation"><a href="<?php echo $this->url('dadosPresencial')?>">Modalidade Presencial</a></li>
                        <li class=" active" role="presentation" ><a href="#"><label>Modalidade EAD</label></a></li>
                      
                    </ul> 
                </div>
              </div>
            </div>
        </div>
        <br/>
        <div style=" height: 1000px">
      <div class="caption">
        <div class="navbar-collapse">
            <form class="navbar-default" method="post">
                <div >
                     <table class="table">
                     
                       <tr >  
                            <th style=" text-align: center">Curso</th> 
                            <th style=" width: 200px; text-align: center">Quantidade de Alunos</th>
                            <th  style=" width: 200px; text-align: center">Meta em porcentagem</th>
                            <th style=" text-align: center">Professor Orientador</th>
                            
                        </tr>
                       <?php foreach ( $this->lista as $l){
                       ?>
                        <tr style=" background-color: #e0f0f4">
                            <td>
                                <div class="input-group ">
                                    <span class="input-group-addon " > <?php  echo $l->getIddados()?></span>
                                <input name="<?php echo$l->getIddados()?>" value="<?php echo $this->translate($l->getCurso())?>" type="text" class="form-control input-group"/>
                                </div></td>
                                <td><input name="<?php echo "GV-".$l->getIddados()?>" value="<?php echo $this->translate($l->getQuantidadealunos())?>" type="number" class="form-control input-group" required=""/>   
                                </td>
                            <td >
                                <input name="<?php echo $this->translate($l->getIddados()+100)?>" value="<?php echo $this->translate($l->getMeta())?>" type="number" class="form-control input-group" required=""/>   
                            </td>
                            <td >
                                <input name="<?php echo "orientador".$l->getIddados()?>" value="<?php echo $this->translate($l->getOrientador())?>" type="text" class="form-control input-group" />   
                            </td>
                        </tr><?php }
                            ?>
                    </table>
                    
                </div>
                <nav class="pager">
                    <input type="submit" value="Salvar" class=" btn btn-primary"/>
                    </nav><br/>
            </form>
            
        </div>
      </div>
    </div>

<?php echo $this->resp; ?>
    </body>
    
</html>