<?php
        $listaEmpresa = $this->listaEmpresa;
        $listaVaga = $this->vagas;
        $listaAluno = $this->listaAluno;
        $idaluno = $this->idaluno;
    
     ?>
<script>
    $(document).ready(function(){
    $("#form").validate({
    highlight: function(element) {
    $(element.form).find("." + element.id )
            .addClass("has-error")
            .removeClass("has-succes");
    $("em").css("color","red");        
    },
    unhighlight: function(element) {
    $(element.form).find("." + element.id)
            .removeClass("has-error")
            .addClass("has-success");
            
    },
    errorElement: "em",
    
        
    messages: {
        bolsa: 'Por favor digite a bolsa',
        curso: 'Por favor digite o curso',
        carga: 'Por favor digite a carga',
        inicio: 'Por favor, digite o início',
        empresa: 'Por favor digite a empresa'
    },
    rules:{
        bolsa: {
           required: true
        },
        curso: {
           required: true,
           
        },
        carga: {
           required: true
        },
        inicio: {
           required: true
        },
        empresa: {
           required: true
        }
    }
        });
    });
</script>
<style>
    .bs-wizard {margin-top: 40px;}

/*Form Wizard*/
.bs-wizard {border-bottom: solid 1px #e0e0e0; padding: 0 0 10px 0;}
.bs-wizard > .bs-wizard-step {padding: 0; position: relative;}
.bs-wizard > .bs-wizard-step + .bs-wizard-step {}
.bs-wizard > .bs-wizard-step .bs-wizard-stepnum {color: #595959; font-size: 16px; margin-bottom: 5px;}
.bs-wizard > .bs-wizard-step .bs-wizard-info {color: #999; font-size: 14px;}
.bs-wizard > .bs-wizard-step > .bs-wizard-dot {position: absolute; width: 30px; height: 30px; display: block; background: #c9fdd5; top: 45px; left: 50%; margin-top: -15px; margin-left: -15px; border-radius: 50%;} 
.bs-wizard > .bs-wizard-step > .bs-wizard-dot:after {content: ' '; width: 14px; height: 14px; background:  #5fce78; border-radius: 50px; position: absolute; top: 8px; left: 8px; } 
.bs-wizard > .bs-wizard-step > .progress {position: relative; border-radius: 0px; height: 8px; box-shadow: none; margin: 20px 0;}
.bs-wizard > .bs-wizard-step > .progress > .progress-bar {width:0px; box-shadow: none; background:#c9fdd5;}
.bs-wizard > .bs-wizard-step.complete > .progress > .progress-bar {width:100%;}
.bs-wizard > .bs-wizard-step.active > .progress > .progress-bar {width:50%;}
.bs-wizard > .bs-wizard-step:first-child.active > .progress > .progress-bar {width:0%;}
.bs-wizard > .bs-wizard-step:last-child.active > .progress > .progress-bar {width: 100%;}
.bs-wizard > .bs-wizard-step.disabled > .bs-wizard-dot {background-color: #f5f5f5;}
.bs-wizard > .bs-wizard-step.disabled > .bs-wizard-dot:after {opacity: 0;}
.bs-wizard > .bs-wizard-step:first-child  > .progress {left: 50%; width: 50%;}
.bs-wizard > .bs-wizard-step:last-child  > .progress {width: 50%;}
.bs-wizard > .bs-wizard-step.disabled a.bs-wizard-dot{ pointer-events: none; }
/*END Form Wizard*/
</style>

    
    <div class="row thumbnail">
         <div class="panel panel-primary">
            <div class="panel-heading">Lançamento de vaga</div>
        </div>
        <div>
            <div class="row bs-wizard" style="border-bottom:0;">
                
                <div class="col-xs-4 bs-wizard-step active">
                  <div class="bs-wizard-info text-center bs-wizard-stepnum">Cadastro</div>
                  <div class="progress"><div class="progress-bar"></div></div>
                  <a href="#" class="bs-wizard-dot"></a>
                  <div class="bs-wizard-info text-center">  
                  </div>
                </div> 
                <div class="col-xs-4 bs-wizard-step disabled"><!-- complete -->
                  <div class="bs-wizard-info text-center bs-wizard-stepnum">Documentos</div>
                  <div class="progress"><div class="progress-bar"></div></div>
                  <a href="#" class="bs-wizard-dot"></a>
                  <div class="bs-wizard-info text-center">
                  </div>
                </div>
                <div class="col-xs-4 bs-wizard-step disabled"><!-- complete -->
                  <div class="bs-wizard-info text-center bs-wizard-stepnum">Fim</div>
                  <div class="progress"><div class="progress-bar"></div></div>
                  <a href="#" class="bs-wizard-dot"></a>
                  <div class="bs-wizard-info text-center">
                  </div>
                </div>
            </div>
	</div>
        <form method="post" id="form" class=" form-group ">
                            <div class="row">
                            <div class="aluno col-sm-6">
                                <label for="aluno" >Aluno</label>
                                <select id="aluno" name="aluno" class="form-control " >
                                            <?php foreach ($this->aluno as $l): ?>
                                           <option>  <?php echo  $l->getNome()?></option>
                                            <?php endforeach; ?>         
                                </select>
                            </div> 
                            <div class=" curso col-sm-6">
                                <label for="curso">Curso</label>
                                <select name="curso" id="curso" class="form-control">
                                        <option></option>
                                        <?php  foreach ( $this->listaDados as $l): ?>
                                        <option value="<?php echo $l->getIddados()?>"><?php echo $l->getCurso()?></option>
                                        <?php endforeach; ?> 
                                    </select>
                            </div>
                            </div>
                            <br/>
                            <div class="row">            
                              <div class="col-sm-6 agente">
                                    <label for="agente"><?php echo $this->translate('Agente')?></label>
                                    <select id="agente" name="agente" class="form-control" >
                                           <option></option>
                                            <?php foreach ($this->listaAgente as $l): ?>
                                           <option><?php print_r($l->getAgente()); ?></option>
                                            <?php endforeach; ?>         
                                    </select>
                            </div>
                            <div class="col-sm-6 nome">
                                <label for="empresa"><?php echo $this->translate('Empresa')?></label>
                                    <select name="empresa" id="empresa" class="form-control" >
                                       <option></option>
                                        <?php sort($listaEmpresa); foreach ($listaEmpresa as $l): ?>
                                       <option><?php print_r($l->getEmpresa()); ?></option>
                                        <?php endforeach; ?>  
                                    </select>
                            </div>
                            </div>
                            <br/>
                            <div class="row">
                            <div class="  col-sm-4 carga">
                                <label for="carga"><?php echo $this->translate('Carga')?></label>
                                 <input  id="carga" name="carga" type="text" class="form-control" />
                            </div>
                            <div class="col-sm-4 bolsa">
                                <label for="bolsa"><?php echo $this->translate('Bolsa')?></label>
                                <input id="bolsa" name="bolsa" type="number" class="form-control" />
                            </div> 
                                <div class="  col-sm-4 inicio">
                                    <div  class="date" >
                                        <label for="inicio"><?php echo $this->translate('Início')?></label>
                                        <input  onkeypress="mascaraData( this, event )" class="form-control" type="date" name="inicio"  id="inicio"   />
                                    </div>
                                </div>
                            </div>      
                            <br/> 
                             <button    type="submit" class="btn btn-success " >Salvar</button>
            </form>
   </div> 
<?php echo $this->resp; ?>
