 <script>
 $(document).ready(function(){
     $('[data-toggle="popover"]').popover();
 //Bootstrap Toggle
 $(".operacao1").bootstrapToggle({
        on: '<label>1 - </label> Assinado',
        off: '<label>1 - </label> Em Processo',
        onstyle: 'success',
        offstyle: 'warning',
        size: 'mini',
        width: '125',
        style: 'android'
    });
    $(".operacao2").bootstrapToggle({
        on: '<label>2 - </label> Assinado',
        off: '<label>2 - </label> Em Processo',
        onstyle: 'success',
        offstyle: 'warning',
        size: 'mini',
        width: '125',
        style: 'android'
    });
    $(".operacao3").bootstrapToggle({
        on: '<label>3 - </label> Entregue',
        off: '<label>3 - </label> Não Entregue',
        onstyle: 'success',
        offstyle: 'warning',
        size: 'mini',
        width: '125',
        style: 'android'
    });
    $(".operacao4").bootstrapToggle({
        on: '<label>4 - </label> Entregue',
        off: '<label>4 - </label> pendente',
        onstyle: 'success',
        offstyle: 'warning',
        size: 'mini',
        width: '125',
        style: 'android'
    });
  
    //jquery Validate
    $("#my-form").validate({
        highlight: function(element) {
        $(element.form).find("." + element.id )
            .addClass("has-error")
            .removeClass("has-succes");
        $("em").css("color","red");
        $("."+element.id+"-valid").css("display","none");
        },
        unhighlight: function(element) {
        $(element.form).find("." + element.id)
            .removeClass("has-error")
            .addClass("has-success"); 
        $("."+element.id+"-valid").css({
            display: "inline",
            color: "green"
        });
        },
        errorElement: "em",
        messages: {
        inicioEnc: 'Entre com uma data válida',
        fimEnc: 'Entre com uma data válida',
        documento: 'Por favor selecione o tipo de documento'
        },
        rules:{
        inicioEnc: {
           required: true
        },
        fimEnc: {
           required: true 
        },
        documento:{
            required: true
        }
        }
    });
    //Bootstrap DatePiker
    $('.input-group.date').datepicker({
    	format: 'yyyy-mm-dd',
    	language: 'pt-BR',
    	weekStart: 0,
    	startDate:'',
    	todayHighlight: true
    });
 });
 function excluirDocumento(idDocumento){
    $(".excluir-"+idDocumento)
            .removeClass("fa-trash")
            .addClass("fa-spinner fa-pulse fa-fw");
    $(".btn").attr("disabled",true);
    $.post(
        '<?= $this->url('deleteDocumentoPresencial', ['action' => 'excluir', 'iddelete' => '']) ?>'+idDocumento+'/',
        'json'
        ).always(function() {
             $("#"+idDocumento).hide('2000');
             $(".btn").attr("disabled",false);
        });
 }
  function salvarDocumento(idDocumento){
      $(".salvar-"+idDocumento)
            .addClass("fa fa-spinner fa-pulse fa-fw");
      $(".btn").attr("disabled",true);
      $.post(
              '<?= $this->url('deleteDocumentoPresencial', ['action' => 'salvarDocumento', 'idDocumento' => '']) ?>'+idDocumento,
      {
          operacao1: function(){
            var  operacao1 = $("#list-"+idDocumento+" input[name='operacao1']");
                if(operacao1.is(":checked")){
                    return '1';  
                }
                else{
                    return '0';
                }   
          },
          operacao2: function(){
            var  operacao2 = $("#list-"+idDocumento+" input[name='operacao2']");
                if(operacao2.is(":checked")){
                    return '1';  
                }
                else{
                    return '0';
                }    
          },
          operacao3: function(){
            var  operacao3 = $("#list-"+idDocumento+" input[name='operacao3']");
                if(operacao3.is(":checked")){
                    return '1';  
                }
                else{
                    return '0';
                }  
          },
         operacao4: function(){
            var  operacao4 = $("#list-"+idDocumento+" input[name='operacao4']");
                if(operacao4.is(":checked")){
                    return '1';  
                }
                else{
                    return '0';
                }    
          }
      },
      'json').always(function(){
           var n = $( "#list-"+idDocumento+" input:checked").length;
          switch(n){
              case 1: $(".progress-"+idDocumento).css("width",'25%').html("25%") ;
              break
                   case 2: $(".progress-"+idDocumento).css("width",'50%').html("50%") ;
                   break
                        case 3: $(".progress-"+idDocumento).css("width",'75%').html("75%");
                        break
                             case 4: $(".progress-"+idDocumento).css("width",'100%').html("Processo Finalizado!") ;
                             break
                                  case 0: $(".progress-"+idDocumento).css("width",'10%').html("10%") ;
                                      break
            }
            $(".salvar-"+idDocumento).removeClass("fa fa-spinner fa-pulse fa-fw");
            $(".btn").attr("disabled",false);
      }
        );
 };
 function editarDocumento(idDocumento){
     $(".btn-edit").html("<i class='fa fa-spinner fa-pulse fa-fw'></i>");
     $.post(
        '<?= $this->url('deleteDocumentoPresencial', ['action' => 'editarDocumento', 'idDocumento' => '']) ?>'+idDocumento,
        {
            inicio: function(){
                return $("#editarInicio-"+idDocumento).val();},
            fim: function(){
                return $("#editarFim-"+idDocumento).val();},
            tipo: function(){ 
                return $("#editarTipo-"+idDocumento).val();}
        },
        'json').always(
        function(){
            location.reload();
        }
            );
 }
 </script>     
      <div  class=" panel panel-primary well-lg">
        <div class="panel-heading"> 
            <div class="row bs-wizard " style="border-bottom:0;">     
                <div class="col-xs-4 bs-wizard-step complete">
                  <div class="bs-wizard-info text-center bs-wizard-stepnum">Cadastro</div>
                  <div class="progress"><div class="progress-bar"></div></div>
                  <a href="#" class="bs-wizard-dot"></a>
                  <div class="bs-wizard-info text-center">  
                  </div>
                </div> 
                <div class="col-xs-4 bs-wizard-step active"><!-- complete -->
                  <div class="bs-wizard-info text-center bs-wizard-stepnum">Documentos</div>
                  <div class="progress"><div class="progress-bar"></div></div>
                  <a href="#" class="bs-wizard-dot"></a>
                  <div class="bs-wizard-info text-center">
                  </div>
                </div>
                <div class="col-xs-4 bs-wizard-step disabled"><!-- complete -->
                  <div class="bs-wizard-info text-center bs-wizard-stepnum">Fim</div>
                  <div class="progress"><div class="progress-bar"></div></div>
                  <a href="#" class="bs-wizard-dot"></a>
                  <div class="bs-wizard-info text-center">
                  </div>
                </div>
            </div><br>     
        </div>
                  <?php  if (!empty($this->listaContratos)):
                    echo    '<div class="list-group "><div class="panel-footer"> 
                                <label>Documentos lançados</label></div>';            
                    foreach ($this->listaContratos as $f):
                    ?> 
        <div id="<?= $f->getIddocumento()?>">    
                <button  type="button" class="list-group-item list-group-item-success"  data-toggle="collapse" href="#list-<?= $f->getIddocumento()?>" aria-expanded="false" aria-controls="collapseExample" style=" border-color: #33610a">
       
        <div class="progress">
        <?php
        $progress = $f->getOperacao1()+$f->getOperacao2()+$f->getOperacao3()+$f->getOperacao4();
        switch($progress){
            case 1: $width = "25%" ;
                break;
                case 2: $width = "50%" ;
                    break;
                    case 3: $width = "75%" ;
                        break;
                        case 4: $width = "100%" ;
                            break;
                            case 0: $width = "10%" ;
                                break;
        }
        ?>
        <div class="<?= 'progress-'.$f->getIdDocumento()?> progress-bar progress-bar-success" role="progressbar" aria-valuenow="20" aria-valuemin="10" aria-valuemax="100" style="width:<?= $width?>">
         <?= $width?> 
        </div> 
        </div>
         <?= $f->getRelatorio()?> <i class=" pull-right fa fa-bars"></i>      
    </button>
                <div class="collapse" id="list-<?= $f->getIddocumento()?>">     
                    <div class="pager">
                    <div class="col-sm-3">
                <span class="fa-stack fa-sm ">
                    <i class="fa fa-square-o fa-stack-2x"></i>
                    <span class="fa-stack-1x">1</span> 
                </span> Direção do Curso <i class="fa fa-chevron-right"></i>
            </div>
                    <div class="col-sm-3">
                <span class="fa-stack fa-sm">
                    <i class="fa fa-square-o fa-stack-2x"></i>
                    <span class="fa-stack-1x">2</span> 
                </span>Instituição de Ensino <i class="fa fa-chevron-right"></i>
            </div>
                    <div class="col-sm-3" >
                <span class="fa-stack fa-sm">
                    <i class="fa fa-square-o fa-stack-2x"></i>
                    <span class="fa-stack-1x">3</span> 
                </span>Entregue ao aluno? <i class="fa fa-chevron-right"></i>
            </div>
                    <div class="col-sm-3" >
                <span class="fa-stack fa-sm">
                    <i class="fa fa-square-o fa-stack-2x"></i>
                    <span class="fa-stack-1x">4</span> 
                </span>Via do documento 
            </div>
        </div>
            <?=    '<div class="pager">'.
                '<div class=" col-sm-3">'.
                    
                    $this->formRow($this->documentoForm->get('operacao1')
                        ->setAttribute('checked',$f->getOperacao1())
                        ->setAttribute('class', 'operacao1')
                        ->setUncheckedValue('0')
                        ->setCheckedValue('1')).' </div>'.
                '<div class=" col-sm-3">'.
                
                    $this->formRow($this->documentoForm->get('operacao2')
                        ->setAttribute('checked', $f->getOperacao2())
                        ->setAttribute('class', 'operacao2')
                        ->setUncheckedValue('0')
                        ->setCheckedValue('1')).'</div> '.
                '<div class=" col-sm-3">'.
                
                     $this->formRow($this->documentoForm->get('operacao3')
                        ->setAttribute('checked',$f->getOperacao3())
                        ->setAttribute('class', 'operacao3')
                        ->setUncheckedValue('0')
                        ->setCheckedValue('1')).'</div> '.
                '<div class=" col-sm-3">'.
               
                    $this->formRow($this->documentoForm->get('operacao4')
                        ->setAttribute('checked',$f->getOperacao4())
                        ->setAttribute('class', 'operacao4')
                        ->setUncheckedValue('0')
                        ->setCheckedValue('1')).'</div>'.
                    '</div>'
                    ?> 
                    <div class="pager well">
                        
                            <button class="btn btn-success  " onclick="return salvarDocumento(<?= $f->getIddocumento()?>)"><i class="  fa--save  <?= 'salvar-'.$f->getIddocumento()?>"></i><span ><i class="fa fa-check"></i><br></span></button>
                            <button class="btn btn-danger " onclick="return excluirDocumento(<?= $f->getIddocumento()?>)" ><i class="  fa--trash  <?= 'excluir-'.$f->getIddocumento()?>"></i><span ><i class="fa fa-remove"></i><br></span></button>
                            <button type="button" class="btn btn-primary " data-toggle="modal" data-target="#<?= 'modal-'.$f->getIddocumento()?>">
                                <i class=" fa fa-plus"></i>
                             </button>
                            <button type="button" class="btn btn-primary " data-toggle="modal" data-target="#<?= 'modal-editar-'.$f->getIddocumento()?>">
                                <i class=" fa fa-edit"></i>
                            </button>
                            </div>
                    <div class="modal fade" id="<?= 'modal-'.$f->getIddocumento()?>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                <div class="modal-dialog modal-sm" role="document">
                  <div class="modal-content">
                      <div class="panel panel-primary"> <h4 class="modal-title panel panel-heading " id="myModalLabel">Informações 
                          <button type="button" class="close " data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                     
                          </h4>
                    <div class="modal-body">
                        <?= '<label>Documento:</label> '.$f->getRelatorio().'<br>'?>
                        <?= '<label>Inicio:</label> '.date_format($f->getInicio(), 'd/m/Y').'<br>'?>
                        <?= '<label>Fim:</label> '.date_format($f->getFim(), 'd/m/Y').'<br>'?>
                        <?= '<label>Data de lançamento:</label> '.$f->getdataLancamento()?>
                    </div>
                      </div>
                  </div>
                </div>
              </div>
               <div class="modal fade" id="<?= 'modal-editar-'.$f->getIddocumento()?>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                <div class="modal-dialog modal-sm" role="document">
                  <div class="modal-content">
                      <div class="panel panel-primary "> <h4 class="modal-title panel panel-heading " id="myModalLabel">Editar 
                          <button type="button" class="close pull-right" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                     
                          </h4>
                    <div class="modal-body">
                        <form method="post" >
                            <label>Inicio</label>
                            <input id="<?= 'editarInicio-'.$f->getIddocumento()?>" name="inicio" class=" form-control" type="date" value="<?= date_format($f->getInicio(), 'd-m-Y')?>"/>
                            <label>Fim</label>
                            <input id="<?= 'editarFim-'.$f->getIddocumento()?>" name="fim" class=" form-control" type="date" value="<?=date_format($f->getFim(), 'd/m/Y')?>"/>
                            <label>Tipo</label>
                            <input id="<?= 'editarTipo-'.$f->getIddocumento()?>" name="tipo" class=" form-control" type="text" value="<?=$f->getRelatorio()?>"/>
                            <div class="pager well">
                                <button onclick="return editarDocumento(<?= $f->getIddocumento()?>)" type="button" class="btn btn-success btn-edit">Salvar</button>
                            </div>
                        </form>
                    </div>
                      </div>
                  </div>
                </div>
              </div>
                </div>
        </div>
                    <?php 
                    $idVagaDocumento = $f->getIdvagadocumento();
                    $idaluno = $f->getIdalunodocumento();
                        endforeach; 
                            echo  '</div>';
                        endif;    
                    ?>
                    
                        </div>
                    <?php     
                      $this->documentoForm->prepare();
                      echo 
                      $this->form()->openTag($this->documentoForm);
                    ?>
    <div class=" panel panel-primary">
        <div class=" panel-heading">Lançar documento</div>
        <div class="row" ><br/>
                <div class="  col-sm-3 col-sm-offset-1">
                    <div  class=" date inicioEnc" >
                     <i style="display: none" class=" inicioEnc-valid glyphicon glyphicon-ok-circle"></i>
                        <?= $this->formRow($this->documentoForm->get('inicioEnc')
                                ->setAttribute('id', 'inicioEnc')
                                ->setAttribute('required', 'true')
                                ->setAttribute('class', 'form-control datepicker input-group.date')
                        );?>
                    </div>        
                </div>
                <div class="  col-sm-3">
                    <div class=" date fimEnc" >
                    <i  style="display: none" class=" fimEnc-valid glyphicon glyphicon-ok-circle"></i>
                    <?= $this->formRow($this->documentoForm->get('fimEnc')
                            ->setAttribute('id', 'fimEnc')
                            ->setAttribute('required', 'true')
                            ->setAttribute('class', 'form-control datepicker input-group.date'))
                    ;?>
                    </div>
                </div>
                <div class="  col-sm-4 documento">
                    <i  style="display: none" class=" documento-valid glyphicon glyphicon-ok-circle"></i>
                    <label>Documento</label>
                    <?= $this->formRow($this->documentoForm->get('documento')
                            ->setAttribute('class', 'form-control')
                            ->setAttribute('id', 'documento')
                            );?>
                </div>
            </div><div class="well-sm">
                    <?= $this->formSubmit($this->documentoForm->get('lançar')
                            ->setValue('Lançar')
                            ->setAttribute('class', 'btn  btn-success col-sm-offset-1'));
                    ?>
                </div>
        <div class="well-lg ">
                        <?php  if (!empty($this->listaContratos)):
                          echo '<a  href="'. $this->url('vagaPresencial/default', array('controller' => 'vagaPresencial', 'action' => 'perfilvagafinalizada','id'=>$idaluno ,'idVaga'=>$idVagaDocumento)).'"><span class="btn btn-primary" ><i class="fa fa-check-square-o fa-2x pull-left"></i>Finalizar <br>Cadastro</span></a>';
                    endif;?>
        </div>
    </div> 
</div>
<?= $this->form()->closeTag();?>
<?= $this->resp;
