 <?php 
 foreach ($this->listaVaga as $f):
     $empresa = $f->getEmpresa();
     $carga = $f->getCarga();
     $bolsa = $f->getBolsa();
     $inicio = $f->getInicio();
     $recisao = $f->getRecisao();
     $idVaga = $f->getidVaga();
     $agente = $f->getAgente();
     $idAluno = $f->getIdalunovaga();
     $aluno = $f->getAluno();
 endforeach;
 foreach ($this->listaAcompanhamento as $f):
     $idAcompanhamento = $f->getIdacompanhamento();
 endforeach;
?>
<script>
 $(document).ready(function(){
       $('.date').datepicker({
    	format: 'yyyy-mm-dd',
    	language: 'pt-BR',
    	todayHighlight: true
    });
    $('#fim-recisao-<?= $idVaga?>').datepicker()
            .on('changeDate',function(ev){
                if(ev.date.valueOf() > startDate.valueOf()){
                    alert("Error");
                }
    });
    
    $('[data-toggle="popover"]').popover();
 //Bootstrap Toggle
    $(".operacao1").bootstrapToggle({
        on: '<label>1 - </label> Assinado',
        off: '<label>1 - </label> Em Processo',
        onstyle: 'success',
        offstyle: 'warning',
        size: 'mini',
        width: '125',
        style: 'android'
    });
    $(".operacao2").bootstrapToggle({
        on: '<label>2 - </label> Assinado',
        off: '<label>2 - </label> Em Processo',
        onstyle: 'success',
        offstyle: 'warning',
        size: 'mini',
        width: '125',
        style: 'android'
    });
    $(".operacao3").bootstrapToggle({
        on: '<label>3 - </label> Entregue',
        off: '<label>3 - </label> Não Entregue',
        onstyle: 'success',
        offstyle: 'warning',
        size: 'mini',
        width: '125',
        style: 'android'
    });
    $(".operacao4").bootstrapToggle({
        on: '<label>4 - </label> Entregue',
        off: '<label>4 - </label> pendente',
        onstyle: 'success',
        offstyle: 'warning',
        size: 'mini',
        width: '125',
        style: 'android'
    });
    //jquery Validate
  
 });
 function excluirDocumento(idDocumento){
     var apagar = confirm('Deseja realmente excluir este registro?');
      if (apagar){
	 $(".excluir-"+idDocumento)
            .removeClass("fa-trash")
            .addClass("fa-spinner fa-pulse fa-fw");
    $(".btn").attr("disabled",true);
    $.post(
        '<?= $this->url('deleteDocumentoPresencial', ['action' => 'excluir', 'iddelete' => '']) ?>'+idDocumento+'/',
        'json'
        ).always(function() {
             $("#"+idDocumento).hide('2000');
             $(".btn").attr("disabled",false);
        });			
      }else{
         event.preventDefault();
      }	   
 }
 function excluirAcompanhamento(idDocumento){
    var apagar = confirm('Deseja realmente excluir este registro?');
      if (apagar){
	   $(".excluirAcompanhamento-"+idDocumento)
            .removeClass("fa-trash")
            .addClass("fa-spinner fa-pulse fa-fw");
    $(".btn").attr("disabled",true);
    $.post(
        '<?= $this->url('deleteDocumentoPresencial', ['action' => 'excluirAcompanhamento', 'iddelete' => '']) ?>'+idDocumento+'/',
        'json'
        ).always(function() {
             $("#listaAcompanhamento-"+idDocumento).hide('2000');
             $(".btn").attr("disabled",false);
        });			
      }else{
         event.preventDefault();
      }	
 
 }
  function salvarDocumento(idDocumento){
    $(".salvar-"+idDocumento)
            .addClass("fa fa-spinner fa-pulse fa-fw");
    $(".btn").attr("disabled",true);
    $.post(
    '<?= $this->url('deleteDocumentoPresencial', ['action' => 'salvarDocumento', 'idDocumento' => '']) ?>'+idDocumento,
    {
        operacao1: function(){
            var  operacao1 = $("#list-"+idDocumento+" input[name='operacao1']");
                if(operacao1.is(":checked")){
                    return '1';  
                }
                else{
                    return '0';
                }   
          },
        operacao2: function(){
            var  operacao2 = $("#list-"+idDocumento+" input[name='operacao2']");
                if(operacao2.is(":checked")){
                    return '1';  
                }
                else{
                    return '0';
                }    
        },
        operacao3: function(){
            var  operacao3 = $("#list-"+idDocumento+" input[name='operacao3']");
                if(operacao3.is(":checked")){
                    return '1';  
                }
                else{
                    return '0';
                }  
        },
        operacao4: function(){
            var  operacao4 = $("#list-"+idDocumento+" input[name='operacao4']");
                if(operacao4.is(":checked")){
                    return '1';  
                }
                else{
                    return '0';
                }    
        }
    },
    'json'
    ).always(function(){
           var n = $( "#list-"+idDocumento+" input:checked").length;
            switch(n){
                case 1: $(".progress-"+idDocumento).css("width",'25%').html("25%") ;
                break
                     case 2: $(".progress-"+idDocumento).css("width",'50%').html("50%") ;
                     break
                          case 3: $(".progress-"+idDocumento).css("width",'75%').html("75%");
                          break
                               case 4: $(".progress-"+idDocumento).css("width",'100%').html("Processo Finalizado!") ;
                               break
                                    case 0: $(".progress-"+idDocumento).css("width",'10%').html("10%") ;
                                        break
              }
        $(".salvar-"+idDocumento).removeClass("fa fa-spinner fa-pulse fa-fw");
        $(".btn").attr("disabled",false);
      }
    );
 };
 function editarDocumento(idDocumento){
     $(".btn-edit").html("<i class='fa fa-spinner fa-pulse fa-fw'></i>");
     $.post(
        '<?= $this->url('deleteDocumentoPresencial', ['action' => 'editarDocumento', 'idDocumento' => '']) ?>'+idDocumento,
        {
            inicio: function(){
                return $("#editarInicio-"+idDocumento).val();},
            fim: function(){
                return $("#editarFim-"+idDocumento).val();},
            tipo: function(){ 
                return $("#editarTipo-"+idDocumento).val();}
        },
        'json').always(
                    function(){
                        location.reload();
                    }
                );
 }
function editarAcompanhamento(idDocumento){
    $(".btn-edit-acompanhamento").html("<i class='fa fa-spinner fa-pulse fa-fw'></i>");
    $.post(
        '<?= $this->url('salvarDocumento', ['action' => 'editarAcompanhamento', 'idDocumento' => '']) ?>'+idDocumento,
        {
            inicio: function(){
                return $("#editarInicioAcompanhamento-"+idDocumento).val();},
            fim: function(){
                return $("#editarFimAcompanhamento-"+idDocumento).val();},
            relatorioAcompanhamento: function(){ 
                return $("#relatorioAcompanhamento-"+idDocumento).val();},
            acompanhante: function(){ 
                return $("#acompanhante-"+idDocumento).val();}
        },
        'json').always(
                    function(){
                        location.reload();
                        }
                );
 }
  function recisao(idDocumento){   
    var inicio = $("#inicio-recisao-"+idDocumento).val();
    if( inicio === ''){
        $("#recisaoValidate").addClass("has-error");
            return false;
    }else{
    $("#recisaoValidate").removeClass("has-error").addClass("has-success has-feedback");    
    $(".btn-recisao").html("<i class='fa fa-spinner fa-pulse fa-fw'></i>");
    $.post(
        '<?= $this->url('salvarDocumento', ['action' => 'recisao', 'idDocumento' => '']) ?>'+idDocumento,
        {
            inicioRecisao: function(){
                return $("#inicio-recisao-"+idDocumento).val();},
            fimRecisao: function(){
                return $("#fim-recisao-"+idDocumento).val();}
        },
        'json').always(
            function(){
                var data = $("#fim-recisao-"+idDocumento).val();
                if(data === ''){
                    $("#fimBaixa").html("Ativo até o momento") ;
                }else{
                    $("#fimAtivo").html(" "+data) ;
                }
                 $(".btn-recisao").html("<i class='fa fa-check '></i>");
            }
            );}
 }
 
 function acompanhamento (){
 var inicio = $("#inicioAcompanhamento").val();
 var fim = $("#fimAcompanhamento").val();
 var periodo = $("#periodo").val();
 var acompanhante = $("#acompanhante").val();
 
    if(inicio === ''|| fim ==='' ){
        alert  ("Preencha todos os campos!")
        return false;
    }else{
     $("#btn-acompanhamento").html("<i class='fa fa-spinner fa-pulse fa-fw'></i>");
    $.post(
        '<?= $this->url('salvarDocumento', ['action' => 'acompanhamento','idDocumento'=>'0']) ?>',
        {
            inicio: function(){
            return inicio;    
             },
            fim: function(){
            return fim;
            },
            periodo: function (){
                return periodo;
            },
            acompanhante: function (){
                return acompanhante;
            },
            idAluno: function(){
                return <?= $idAluno ?>
            },
            idVaga: function(){
                return <?= $idVaga ?>
            }
        }, 
        'json'
 
    ).always(
            function(){
             location.reload();
            }
    );   
    };
    
    }
 </script>
        <!--________________________________________Painel principal___________________________________-->
        <div class=" panel panel-primary">
        <div class="panel-heading">
              <?= '<h4>'.$aluno.'</h4>'?>
            
        </div>
        <!--___________________________________________________________________________________________ -->

        <!--________________________________________navegação ________________________________________ -->
        <ul class="nav nav-tabs" role="tablist">
           <li role="presentation" class="active"><a href="#hom" aria-controls="hom" role="tab" data-toggle="tab">Início</a></li>
           <li role="presentation"><a href="#acompanhamento" aria-controls="acompanhamento" role="tab" data-toggle="tab">Acompanhamento</a></li>
        </ul>
        <!--__________________________________________________________________________________________-->
        <div class="navbar pager">
            <p><label>Agente de Integração: </label> <?= $agente?></p>
            <p><label>Empresa: </label> <?= $empresa?></p>
                <p class="pager" style=""><label>Carga-Horária: </label> <?php echo $carga; ?> horas &nbsp;&nbsp; <label>Bolsa-Auxílo: </label> R$ <?php echo $bolsa ?>,00 
                </p>
        </div>
        <!--________________________________________Painel ________________________________________ -->
        <div class="tab-content">
         <div role="tabpanel" class="tab-pane fade in active" id="hom">
        <div class="col-sm-12  ">
            <div class=" panel panel-primary thumbnail">
            <div class="panel-heading">
                <?= $this->translate("Processos")?>
            </div>  
            <div>     
<?php  if (!empty($this->listaContratos)):
    foreach ($this->listaContratos as $f):
?> 
    <div   id="<?= $f->getIddocumento()?>">
    <button  type="button" class="list-group-item list-group-item-success"  data-toggle="collapse" href="#list-<?= $f->getIddocumento()?>" aria-expanded="false" aria-controls="collapseExample" style=" border-color: #33610a">
       
        <div class="progress">
        <?php
        $progress = $f->getOperacao1()+$f->getOperacao2()+$f->getOperacao3()+$f->getOperacao4();
        switch($progress){
            case 1: $width = "25%" ;
                break;
                case 2: $width = "50%" ;
                    break;
                    case 3: $width = "75%" ;
                        break;
                        case 4: $width = "100%" ;
                            break;
                            case 0: $width = "10%" ;
                                break;
        }
        ?>
        <div class="<?= 'progress-'.$f->getIdDocumento()?> progress-bar progress-bar-success" role="progressbar" aria-valuenow="20" aria-valuemin="10" aria-valuemax="100" style="width:<?= $width?>">
         <?= $width?> 
        </div> 
        </div>
         <?= $f->getRelatorio()?> <i class=" pull-right fa fa-bars"></i>      
    </button>
        
   <?= '<div class="collapse" id="list-'.$f->getIddocumento().'">'?>
        <div class="pager">
                    <div class="col-sm-3">
                <span class="fa-stack fa-sm ">
                    <i class="fa fa-square-o fa-stack-2x"></i>
                    <span class="fa-stack-1x">1</span> 
                </span> Direção do Curso <i class="fa fa-chevron-right"></i>
            </div>
                    <div class="col-sm-3">
                <span class="fa-stack fa-sm">
                    <i class="fa fa-square-o fa-stack-2x"></i>
                    <span class="fa-stack-1x">2</span> 
                </span>Instituição de Ensino <i class="fa fa-chevron-right"></i>
            </div>
                    <div class="col-sm-3" >
                <span class="fa-stack fa-sm">
                    <i class="fa fa-square-o fa-stack-2x"></i>
                    <span class="fa-stack-1x">3</span> 
                </span>Entregue ao aluno? <i class="fa fa-chevron-right"></i>
            </div>
                    <div class="col-sm-3" >
                <span class="fa-stack fa-sm">
                    <i class="fa fa-square-o fa-stack-2x"></i>
                    <span class="fa-stack-1x">4</span> 
                </span>Via do documento 
            </div>
        </div>
            <?=    '<div class="pager">'.
                '<div class=" col-sm-3">'.
                    
                    $this->formRow($this->documentoForm->get('operacao1')
                        ->setAttribute('checked',$f->getOperacao1())
                        ->setAttribute('class', 'operacao1')
                        ->setUncheckedValue('0')
                        ->setCheckedValue('1')).' </div>'.
                '<div class=" col-sm-3">'.
                
                    $this->formRow($this->documentoForm->get('operacao2')
                        ->setAttribute('checked', $f->getOperacao2())
                        ->setAttribute('class', 'operacao2')
                        ->setUncheckedValue('0')
                        ->setCheckedValue('1')).'</div> '.
                '<div class=" col-sm-3">'.
                
                     $this->formRow($this->documentoForm->get('operacao3')
                        ->setAttribute('checked',$f->getOperacao3())
                        ->setAttribute('class', 'operacao3')
                        ->setUncheckedValue('0')
                        ->setCheckedValue('1')).'</div> '.
                '<div class=" col-sm-3">'.
               
                    $this->formRow($this->documentoForm->get('operacao4')
                        ->setAttribute('checked',$f->getOperacao4())
                        ->setAttribute('class', 'operacao4')
                        ->setUncheckedValue('0')
                        ->setCheckedValue('1')).'</div>'.
                    '</div>'
            ?> 
            <div class="pager well thumbnail ">
               <div class="btn-group-sm">
                   <button class="btn btn-success  " onclick="return salvarDocumento(<?= $f->getIddocumento()?>)"><i class="  fa--save  <?= 'salvar-'.$f->getIddocumento()?>"></i><span ><i class="fa fa-check"></i><br></span></button>
                    <button class="btn btn-danger " onclick="return excluirDocumento(<?= $f->getIddocumento()?>)" ><i class="  fa--trash  <?= 'excluir-'.$f->getIddocumento()?>"></i><span ><i class="fa fa-remove"></i><br></span></button>
                    <button type="button" class="btn btn-primary " data-toggle="modal" data-target="#<?= 'modal-'.$f->getIddocumento()?>">
                        <i class=" fa fa-plus"></i>
                    </button>
                    <button type="button" class="btn btn-primary " data-toggle="modal" data-target="#<?= 'modal-editar-'.$f->getIddocumento()?>">
                        <i class=" fa fa-edit"></i>
                    </button>
               </div>
               <div class="modal fade" id="<?= 'modal-'.$f->getIddocumento()?>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                <div class="modal-dialog modal-sm" role="document">
                  <div class="modal-content">
                      <div class="panel panel-primary"> <h4 class="modal-title panel panel-heading " id="myModalLabel">Informações 
                          <button type="button" class="close " data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                     
                          </h4>
                    <div class="modal-body">
                        <?= '<label>Documento:</label> '.$f->getRelatorio().'<br>'?>
                        <?= '<label>Inicio:</label> '.date_format($f->getInicio(), 'd/m/Y').'<br>'?>
                        <?= '<label>Fim:</label> '.date_format($f->getFim(), 'd/m/Y').'<br>'?>
                        <?= '<label>Data de lançamento:</label> '.$f->getdataLancamento()?>
                    </div>
                      </div>
                  </div>
                </div>
              </div>
               <div class="modal fade" id="<?= 'modal-editar-'.$f->getIddocumento()?>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                <div class="modal-dialog modal-sm" role="document">
                  <div class="modal-content">
                      <div class="panel panel-primary "> <h4 class="modal-title panel panel-heading " id="myModalLabel">Editar 
                          <button type="button" class="close pull-right" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                          </h4>
                    <div class="modal-body">
                        <div class="input-daterange date">
                            <label>Inicio</label>
                            <input id="<?= 'editarInicio-'.$f->getIddocumento()?>" name="inicio" class=" form-control date" type="date" value="<?= date_format($f->getInicio(), 'Y-m-d')?>"/>
                            <label>Fim</label>
                            <input id="<?= 'editarFim-'.$f->getIddocumento()?>" name="fim" class=" form-control date" type="date" value="<?=date_format($f->getFim(), 'Y-m-d')?>"/>
                           </div>
                        <label>Tipo</label>
                            <input id="<?= 'editarTipo-'.$f->getIddocumento()?>" name="tipo" class=" form-control" type="text" value="<?=$f->getRelatorio()?>"/>
                            <div class="pager well">
                                <button onclick="return editarDocumento(<?= $f->getIddocumento()?>)" type="button" class="btn btn-success btn-edit">Salvar</button>
                            </div>
                    </div>
                      </div>
                  </div>
                </div>
              </div>
            </div>
        </div>
    </div>
<?php 
    $idVagaDocumento = $f->getIdvagadocumento();
    $idaluno = $f->getIdalunodocumento();
    endforeach; 
?>
    <?php else:?>
    <div class="alert-danger" style="margin: initial">
           <br/>
           <h4 style="text-align: center">Nenhum documento lançado </h4><br/>      
    </div>
      <?php endif;?>     
            </div>
        </div>  
    </div>
                 <?php     
                      $this->documentoForm->prepare();
                      echo 
                      $this->form()->openTag($this->documentoForm);
                    ?>
   <div class="col-sm-12">
    <div class="well pager">
        <button class="btn btn-success  " type="button" data-toggle="collapse" data-target="#NovoProcesso" aria-expanded="false" aria-controls="NovoProcesso">
            Novo Processo <i class="fa fa-bars "></i>
        </button>
        <div class="collapse" id="NovoProcesso">
            <div class="row "><br/>
                <div class="input-daterange date">
                <div class="  col-sm-3 col-sm-offset-1">
                    <div  class=" inicioEnc" >
                     <i style="display: none" class=" inicioEnc-valid glyphicon glyphicon-ok-circle"></i>
                        <?= $this->formRow($this->documentoForm->get('inicioEnc')
                                ->setAttribute('id', 'inicioEnc')
                                ->setAttribute('required', 'true')
                                ->setAttribute('class', 'form-control date')
                        );?>
                    </div>        
                </div>
                <div class="  col-sm-3">
                    <div class=" fimEnc" >
                    <i  style="display: none" class=" fimEnc-valid glyphicon glyphicon-ok-circle"></i>
                    <?= $this->formRow($this->documentoForm->get('fimEnc')
                            ->setAttribute('id', 'fimEnc')
                            ->setAttribute('required', 'true')
                            ->setAttribute('class', 'form-control date'))
                    ;?>
                    </div>
                </div>
                </div>
                <div class="  col-sm-3 documento">
                    <i  style="display: none" class=" documento-valid glyphicon glyphicon-ok-circle"></i>
                    <label>Documento</label>
                    <?= $this->formRow($this->documentoForm->get('documento')
                            ->setAttribute('class', 'form-control ')
                            ->setAttribute('required', 'true')
                            ->setAttribute('id', 'documento')
                            );?>
                </div><br>
                <div class="col-sm-2 ">
                    <?= $this->formSubmit($this->documentoForm->get('lançar')
                            ->setValue('Lançar')
                            ->setAttribute('class', 'btn  btn-success col-sm-offset-1'));
                    ?>
                </div>
            </div>
    </div>
  </div>
        </div>
         </div>
        <div role="tabpanel" class="tab-pane fade" id="acompanhamento">
          <div class="col-sm-12">
            <div class=" panel panel-primary ">
            <div class="panel-heading">
                <?= $this->translate("Relatório Semetral")?>
            </div>
               <div class="list-group thumbnail">
                   
                       
                   <?php foreach ($this->listaAcompanhamento as $l):?>
                   <div id="listaAcompanhamento-<?= $l->getIdacompanhamento()?>">
                   <a  data-toggle="collapse" href="#acompanhamento-<?= $l->getIdacompanhamento()?>" aria-expanded="false" aria-controls="collapseExample" class="list-group-item list-group-item-success">
                       <?= $l->getPeriodo().' - '.$l->getAcompanhante()?>
                        <i class=" pull-right fa fa-bars"></i> 
                </a>
                <div id="acompanhamento-<?= $l->getIdacompanhamento()?>" class="collapse">
                    <div class=" pager">
                        <?= '<div><label>Período: </label> '.date_format($l->getInicio(), 'd/m/Y').' a '.date_format($l->getFim(), 'd/m/Y').'<br>'
                           . '<label>Data de lançamento: </label>'.$l->getdataAcompanhamento()
                           . '</div>'?>
                        <div class="well well-sm">
                            <button onclick="return excluirAcompanhamento(<?= $l->getIdacompanhamento()?>)" class="btn btn-danger" type="button"><i class="<?= 'excluirAcompanhamento-'.$l->getIdacompanhamento()?> fa fa-remove"></i></button>
                            <button type="button" class="btn btn-primary " data-toggle="modal" data-target="#<?= 'modal-editar-acompanhamento-'.$l->getIdacompanhamento()?>">
                                <i class=" fa fa-edit"></i>
                            </button>
                        </div>
                    </div>
                    <div class="modal fade" id="<?= 'modal-editar-acompanhamento-'.$l->getIdacompanhamento()?>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                <div class="modal-dialog modal-sm" role="document">
                  <div class="modal-content">
                      <div class="panel panel-primary "> <h4 class="modal-title panel panel-heading " id="myModalLabel">Editar 
                          <button type="button" class="close pull-right" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                     
                          </h4>
                    <div class="modal-body">
                        <form method="post">
                            <label>Inicio</label>
                            <input id="<?= 'editarInicioAcompanhamento-'.$l->getIdacompanhamento()?>" name="inicio" class=" form-control date" type="text" value="<?= $l->getInicio()?>"/>
                            <label>Fim</label>
                            <input id="<?= 'editarFimAcompanhamento-'.$l->getIdacompanhamento()?>" name="fim" class=" form-control date" type="tex" value="<?= $l->getFim()?>"/>
                            <label>Relatório</label>
                            <select class=" form-control" id="<?= 'relatorioAcompanhamento-'.$l->getIdacompanhamento()?>">
                                <option><?= $l->getPeriodo()?></option>
                                <option>1º Relatório</option>
                                <option>2º Relatório</option>
                                <option>3º Relatório</option>
                                <option>4º Relatório</option>
                            </select>
                            
                            <label>Acompanhante</label>
                            <select id="<?= 'acompanhante-'.$l->getIdacompanhamento()?>" name="tipo" class=" form-control" type="text" >
                                <option>Instituição de Ensino</option>
                                <option>Empresa Concedente</option>
                                <option>Agente de Integração</option>
                            </select>
                            <div class="pager well">
                                <button onclick="return editarAcompanhamento(<?= $l->getIdacompanhamento()?>)" type="button" class="btn btn-success btn-edit-acompanhamento">Salvar</button>
                            </div>
                        </form>
                    </div>
                      </div>
                  </div>
                </div>
              </div>
                </div> </div> 
                    <?php endforeach;?>
              
               </div>
            </div>
               <?= $this->form()->closeTag();?> 
    <div class="well pager">
        <button class="btn btn-success  " type="button" data-toggle="collapse" data-target="#NovoRelatorio" aria-expanded="false" aria-controls="NovoRelatorio">
            Novo Relatório <i class="fa fa-bars "></i>
        </button>
        <div class="collapse" id="NovoRelatorio">
            <div class="row "><br/>
                <div class="input-daterange date">
                <div class="  col-sm-3 ">
                    <div  class="inicioEnc" >
                     <label>Início</label><input  data-provide="datepicker" id="inicioAcompanhamento" name="inicioAcompanhamento" type="text" class="form-control date" />
                    </div>        
                </div>
                <div class="  col-sm-3">
                    <div class="  fimEnc" >
                        <label>Fim</label>
                        <input data-provide="datepicker" id="fimAcompanhamento" name="fimAcompanhamento" type="text" class="form-control date"/>
                    </div>
                </div>
                </div>
                <div class="  col-sm-2 documento">
                   <label>Período</label>
                    <select class=" form-control" id="periodo">
                        <option>1º Relatório</option>
                        <option>2º Relatório</option>
                        <option>3º Relatório</option>
                        <option>4º Relatório</option>
                    </select>
                </div>
                <div class="  col-sm-3 documento">
                    <label>Acompanhante</label>
                    <div class=" input-group">
                        <select class=" form-control" name="acompanhante" id="acompanhante">
                        <option>Instituição de Ensino</option>
                        <option>Empresa Concedente</option>
                        <option>Agente de Integração</option>
                    </select>
                        <span class="input-group-btn">
                            <button onclick="acompanhamento()" id="btn-acompanhamento"type="button" class="btn btn-success"><i class="fa fa-check"></i></button>   
                        </span></div>
                </div>
            </div>
    </div>
  </div>
              <div class="well-lg pager">
                <?php
                 if(!empty($reciao)){
                    echo "<div   class=' alert alert-warning' role='alert'><p><label>Início:</label>".$inicio.'<label>&nbsp;&nbsp; Fim:</label> <span id="fimBaixa">'.$recisao.'</span></p></div>';
                    }else{
                    echo "<div  class=' alert alert-warning' role='alert'><p><label>Início:</label>".$inicio.'<label>&nbsp;&nbsp; Fim:</label><span id="fimAtivo"> Até o momento</span></p></div>';
                        
                    }
                    ?><div class=" well pager">
                    <button class="btn btn-danger  " type="button" data-toggle="collapse" data-target="#baixa" aria-expanded="false" aria-controls="baixa">
                    Recisão <i class="fa fa-bars "></i>
                    </button><br><br>
                <div class="collapse row input-daterange date" id="baixa">
                    <div class="col-lg-8 col-sm-offset-2 well thumbnail " id="recisaoValidate">
                             <div class="col-lg-4 col-sm-offset-2 ">
                                 <LABEL>Início</LABEL>
                                 <input  id="<?= 'inicio-recisao-'.$idVaga?>" name="inicioRecisao" type="date"  class="form-control date " value="<?= $inicio;?> ">
                             </div>
                             <div class="col-lg-4">
                                 <LABEL>Recisão</LABEL>
                                 <input data-provide="datepicker"  id="<?='fim-recisao-'.$idVaga?>"   type="date" name="fimRecisao" class=" form-control date" value="<?= $recisao;?>"  />  
                             </div> 
                         </div> 
                         <br>
                         <div class="col-sm-8 well-sm col-sm-offset-2">
                                <button onclick="return recisao(<?= $idVaga?>)" type="button" class=" btn-recisao btn btn-success">Salvar</button>
                         </div>  
                </div>
                </div>
            </div>
        </div>                  
    </div> 
    </div>
        <div class="well-lg">
         <?= '<a  href="'. $this->url('perfil/default', array('controller' => 'alunoPresencial', 'action' => 'perfil','id'=>$idAluno)).'"><span class="btn btn-primary" ><i class="fa fa-arrow-left fa-2x pull-left"></i>Painel do <br>aluno</span></a>';?>
        </div>
       
        </div>
    <?= $this->resp;?>