<?php
use Base\Model\Constantes;
?>
<script>
 $(document).ready(function(){
     $('[data-toggle="popover"]').popover();
      $('.date').datepicker({
    	format: 'yyyy-mm-dd',
    	language: 'pt-BR',
    	todayHighlight: true
    });
 //Bootstrap Toggle
 $(".operacao1").bootstrapToggle({
        on: '<label>1 - </label> Assinado',
        off: '<label>1 - </label> Em Processo',
        onstyle: 'success',
        offstyle: 'warning',
        size: 'mini',
        width: '125',
        style: 'android'
    });
    $(".operacao2").bootstrapToggle({
        on: '<label>2 - </label> Assinado',
        off: '<label>2 - </label> Em Processo',
        onstyle: 'success',
        offstyle: 'warning',
        size: 'mini',
        width: '125',
        style: 'android'
    });
    $(".operacao3").bootstrapToggle({
        on: '<label>3 - </label> Entregue',
        off: '<label>3 - </label> Não Entregue',
        onstyle: 'success',
        offstyle: 'warning',
        size: 'mini',
        width: '125',
        style: 'android'
    });
    $(".operacao4").bootstrapToggle({
        on: '<label>4 - </label> Entregue',
        off: '<label>4 - </label> pendente',
        onstyle: 'success',
        offstyle: 'warning',
        size: 'mini',
        width: '125',
        style: 'android'
    });
  
    //jquery Validate
    $("#my-form").validate({
        highlight: function(element) {
        $(element.form).find("." + element.id )
            .addClass("has-error")
            .removeClass("has-succes");
        $("em").css("color","red");
        $("."+element.id+"-valid").css("display","none");
        },
        unhighlight: function(element) {
        $(element.form).find("." + element.id)
            .removeClass("has-error")
            .addClass("has-success");
        $("."+element.id+"-valid").addClass("glyphicon glyphicon-ok-circle");
        $("."+element.id+"-valid").css({
            display: "inline",
            color: "green"
        });
        },
        errorElement: "em",
        messages: {
        inicioEnc: 'Entre com uma data válida',
        fimEnc: 'Entre com uma data válida',
        documento: 'Por favor selecione o tipo de documento'
        },
        rules:{
        inicioEnc: {
           required: true
        },
        fimEnc: {
           required: true 
        },
        documento:{
            required: true
        }
        }
    });
    $(".cadastro").removeClass("active");
    $(".cadastro").addClass("complete");
    $(".documentos").removeClass("disabled");
    $(".documentos").addClass("active");
    $(".glyphicon-ok-circle").css("display", "none");
 });
 function excluirDocumento(idDocumento){
    $(".excluir-"+idDocumento)
            .removeClass("fa-trash")
            .addClass("fa-spinner fa-pulse fa-fw");
    $(".btn").attr("disabled",true);
    $.post(
        '<?= $this->url('deleteDocumentoPresencial', ['action' => 'excluir', 'iddelete' => '']) ?>'+idDocumento+'/',
        'json'
        ).always(function() {
             $("#"+idDocumento).hide('2000');
             $(".btn").attr("disabled",false);
        });
 }
  function salvarDocumento(idDocumento){
      $(".salvar-"+idDocumento)
            .addClass("fa fa-spinner fa-pulse fa-fw");
      $(".btn").attr("disabled",true);
      $.post(
        '<?= $this->url('editarDocumento',['action'=>'salvarDocumento'])?>',
      {
           idDocumento: function(){
                return idDocumento;
            },
          operacao1: function(){
            var  operacao1 = $("#list-"+idDocumento+" input[name='operacao1']");
                if(operacao1.is(":checked")){
                    return '1';  
                }
                else{
                    return '0';
                }   
          },
          operacao2: function(){
            var  operacao2 = $("#list-"+idDocumento+" input[name='operacao2']");
                if(operacao2.is(":checked")){
                    return '1';  
                }
                else{
                    return '0';
                }    
          },
          operacao3: function(){
            var  operacao3 = $("#list-"+idDocumento+" input[name='operacao3']");
                if(operacao3.is(":checked")){
                    return '1';  
                }
                else{
                    return '0';
                }  
          },
         operacao4: function(){
            var  operacao4 = $("#list-"+idDocumento+" input[name='operacao4']");
                if(operacao4.is(":checked")){
                    return '1';  
                }
                else{
                    return '0';
                }    
          }
      },
      'json').always(function(){
           var n = $( "#list-"+idDocumento+" input:checked").length;
          switch(n){
              case 1: $(".progress-"+idDocumento).css("width",'25%').html("25%") ;
              break
                   case 2: $(".progress-"+idDocumento).css("width",'50%').html("50%") ;
                   break
                        case 3: $(".progress-"+idDocumento).css("width",'75%').html("75%");
                        break
                             case 4: $(".progress-"+idDocumento).css("width",'100%').html("Processo Finalizado!") ;
                             break
                                  case 0: $(".progress-"+idDocumento).css("width",'10%').html("10%") ;
                                      break
            }
            $(".salvar-"+idDocumento).removeClass("fa fa-spinner fa-pulse fa-fw");
            $(".btn").attr("disabled",false);
      }
        );
 };
 function editarDocumento(idDocumento){
     $(".btn-edit").html("<i class='fa fa-spinner fa-pulse fa-fw'></i>");
     $.post(
        '<?= $this->url('editarDocumento',['action'=>'editarDocumento']) ?>',
        {
            idDocumento: function(){
                return idDocumento;
            },
            inicio: function(){
                return $("#editarInicio-"+idDocumento).val();},
            fim: function(){
                return $("#editarFim-"+idDocumento).val();},
            documento: function(){ 
                return $("#editarTipo-"+idDocumento).val();}
        },
        'json').always(
                  location.reload()
                );
 }
 </script> 
        <?=     $this->painelTitulo($this->partial('vagaPresencial/layout/cadastrarVagaPartial'));
                if (!empty($this->listaContratos)): 
                    echo '<div class="list-group "><div class="panel-footer"><label>Documentos lançados</label></div>';
                foreach ($this->listaContratos as $l):
                    ?>
        <div id="<?= $l->getIddocumento()?>">    
        <?=     $this->partialLoop('vagaPresencial/layout/processoPartial',[
                    [
                        'idDocumento'=> $l->getIddocumento(),
                        'operacao1'=>$l->getOperacao1(),
                        'operacao2'=>$l->getOperacao2(),
                        'operacao3'=>$l->getOperacao3(),
                        'operacao4'=>$l->getOperacao4(),
                        'relatorio'=>$l->getRelatorio()
                    ]
                ]) 
        ?>   
        <div class="collapse" id="list-<?= $l->getIddocumento()?>">  
        <div class="pager">
            <?= $this->painelTitulo($this->partial('vagaPresencial/layout/painelProcessoPartial'));?>
        </div>
<?php           $this->processoForm->prepare();
        echo    $this->form()->openTag($this->processoForm).
                '<div class="pager">'.
                '<div class=" col-sm-3">'.
                    $this->formRow($this->processoForm->get('operacao1')
                        ->setAttribute('checked',$l->getOperacao1())
                        ->setAttribute('class', 'operacao1')
                        ->setUncheckedValue('0')
                        ->setCheckedValue('1')).' </div>'.
                '<div class=" col-sm-3">'.
                
                    $this->formRow($this->processoForm->get('operacao2')
                        ->setAttribute('checked', $l->getOperacao2())
                        ->setAttribute('class', 'operacao2')
                        ->setUncheckedValue('0')
                        ->setCheckedValue('1')).'</div> '.
                '<div class=" col-sm-3">'.
                
                     $this->formRow($this->processoForm->get('operacao3')
                        ->setAttribute('checked',$l->getOperacao3())
                        ->setAttribute('class', 'operacao3')
                        ->setUncheckedValue('0')
                        ->setCheckedValue('1')).'</div> '.
                '<div class=" col-sm-3">'.
               
                    $this->formRow($this->processoForm->get('operacao4')
                        ->setAttribute('checked',$l->getOperacao4())
                        ->setAttribute('class', 'operacao4')
                        ->setUncheckedValue('0')
                        ->setCheckedValue('1')).'</div>'.
                '</div>'.
                $this->form()->closeTag();
    ?> 
    <div class="pager well">
            <button class="btn btn-success  " onclick="return salvarDocumento(<?= $l->getIddocumento()?>)"><i class="  fa--save  <?= 'salvar-'.$l->getIddocumento()?>"></i><span ><i class="fa fa-check"></i><br></span></button>
            <button class="btn btn-danger " onclick="return excluirDocumento(<?= $l->getIddocumento()?>)" ><i class="  fa--trash  <?= 'excluir-'.$l->getIddocumento()?>"></i><span ><i class="fa fa-remove"></i><br></span></button>
            <button type="button" class="btn btn-primary " data-toggle="modal" data-target="#<?= 'modal-'.$l->getIddocumento()?>">
                <i class=" fa fa-plus"></i>
             </button>
            <button type="button" class="btn btn-primary " data-toggle="modal" data-target="#<?= 'modal-editar-'.$l->getIddocumento()?>">
                <i class=" fa fa-edit"></i>
            </button>
    </div>             
    <?=     $this->partialLoop('vagaPresencial/layout/infoProcessoModalPartial',[
                    ['idDocumento'=> $l->getIddocumento(),
                    'inicio'=>$l->getInicio(),
                    'fim'=>$l->getFim(),
                    'relatorio'=>$l->getRelatorio(),
                    'dataLancamento'=> $l->getdataLancamento()]
                ]).    
            $this->partialLoop('vagaPresencial/layout/editarProcessoModalPartial',[
                    [
                    'editarDocumentoForm' =>$this->editarDocumentoForm,
                    'idDocumento'=> $l->getIddocumento(),
                    'inicio'=>$l->getInicio(),
                    'fim'=>$l->getFim(),
                    'relatorio'=>$l->getRelatorio()]
                ]);?>
            </div>
            </div>
    <?php     
            $idVagaDocumento = $l->getIdvagadocumento();
            $idaluno = $l->getIdalunodocumento();
                endforeach; 
                    echo  '</div>';
                else:
                    echo $this->alertaDanger("Nenhum processo lançado");
                endif;  
                $this->documentoForm->prepare();
    ?>
 <br>
    <?=    $this->form()->openTag($this->documentoForm);       
    ?>
       <div class="well ">
        <button class="btn btn-success  " type="button" data-toggle="collapse" data-target="#NovoProcesso" aria-expanded="false" aria-controls="NovoProcesso">
            Novo Processo <i class="fa fa-bars "></i>
        </button>
        <div class="collapse" id="NovoProcesso">
           <div class="row" ><br/>
               <div class="input-daterange date">
                <div class="  col-sm-3 col-sm-offset-1">
                    <div  class=" inicioEnc" >
                     <i class=" inicioEnc-valid"></i>
                <?=     $this->formRow($this->documentoForm->get('inicioEnc')
                            ->setAttribute('id', 'inicioEnc')
                            ->setAttribute('required', 'true')
                            ->setAttribute('class', 'form-control date'));
                ?>
                    </div>        
                </div>
                <div class="  col-sm-3">
                    <div class=" fimEnc" >
                    <i class=" fimEnc-valid"></i>
                <?=     $this->formRow($this->documentoForm->get('fimEnc')
                            ->setAttribute('id', 'fimEnc')
                            ->setAttribute('required', 'true')
                            ->setAttribute('class', 'form-control date'))
                ;?>
                    </div>
                </div>
               </div>
                <div class="  col-sm-4 documento">
                    <i class=" documento-valid "></i>
                    <label>Documento</label>
                <?=     $this->formRow($this->documentoForm->get('documento')
                            ->setAttribute('class', 'form-control')
                            ->setAttribute('id', 'documento')
                            );
                ?>
                </div>
            </div><div class="well-sm">
                <?=     $this->formSubmit($this->documentoForm->get('lançar')
                            ->setValue('Lançar')
                            ->setAttribute('class', 'btn  btn-success col-sm-offset-1'));
                    ?>
                </div>
            </div>
    </div>
                <?=    $this->form()->closeTag().
                        '<div class="well-lg ">'; 
                        if (!empty($this->listaContratos)):
                            echo    $this->botaoGrande(
                                    $this->url(Constantes::rotaVagaDefault, ['controller' => Constantes::vaga, 'action' => Constantes::perfilVagaFinalizada,'id'=>$idaluno ,'idVaga'=>$idVagaDocumento]) ,
                                    'Finalizar <br>cadastro',
                                    'fa-check-square-o',
                                    'primary'
                                );
                        endif;
                        echo '</div>';
                        
