<?php
use Base\Model\Constantes;
?>
<script>
$(document).ready(function(){
 $(".cadastro").removeClass("active").addClass("complete");
 $(".documentos").removeClass("disabled").addClass("complete");
 $(".fim").removeClass("disabled").addClass("active");
});
</script>           
        <?=     $this->painel(Constantes::temaBootstrap.' well-lg').
                $this->painelTitulo($this->partial('vagaPresencial/layout/cadastrarVagaPartial'));
                if (!empty($this->listaVaga)):
                    foreach ($this->listaVaga as $l):       
        ?>  
                <div  class="list-group-item pager">
                   <h3 class="list-group-item-heading"><?= $l->getEmpresa()?></h3>
                   <p class="list-group-item-text"><?= '<label>Agente:</label> '. $l->getAgente()?></p>
                   <p class="list-group-item-text"><?= '<label>Aluno:</label> '. $l->getAluno()?></p>
                   <p class="list-group-item-text"><?= '<label>Bolsa Auxílio:</label> R$'. $l->getBolsa().',00'?></p>
                   <p class="list-group-item-text"><?= '<label>Carga horária:</label> '. $l->getCarga()?></p>
                </div>        
        <?=     $this->alertaSuccess("Vaga cadastrada com sucesso!").
                        '<div class="list-group-item well pager ">'.
                $this->botaoGrande(
                        $this->url(Constantes::rotaPerfilAlunoDefault, ['controller' => Constantes::administrador, 'action' => constantes::perfilAluno, 'id'=>$l->getidalunovaga(),]),
                         'Perfil do <br> aluno',
                         'fa-user',
                         'primary'
                     ).' '.
                 $this->botaoGrande(
                         $this->url(Constantes::rotaPerfilEmpresaDefault, ['controller' => Constantes::administrador, 'action' => Constantes::perfilEmpresa, 'id'=>$l->getIdEmpresaVaga()]),
                         'Perfil da <br> empresa',
                         'fa-briefcase',
                         'primary'
                     ).
                '</div> ';
                endforeach;
                endif;   
