<?php
foreach ($this->listaVaga as $l){
    $empresa = $l->getEmpresa();
    $aluno = $l->getAluno();
    $carga = $l->getCarga();
    $bolsa = $l->getBolsa();
    $curso = $l->getCursovaga();
}
?>
                    <div class=" container">
                        <div class=" panel panel-primary">
                            <div class="panel-heading">
                                <div class=" nav nav-form">
                                    <div class="row bs-wizard" style="border-bottom:0;">
                                    <div class="col-xs-4 bs-wizard-step complete">
                                      <div class="bs-wizard-info text-center bs-wizard-stepnum">Cadastro</div>
                                      <div class="progress"><div class="progress-bar"></div></div>
                                      <a href="#" class="bs-wizard-dot"></a>
                                      <div class="bs-wizard-info text-center">  
                                      </div>
                                    </div> 
                                    <div class="col-xs-4 bs-wizard-step complete">
                                      <div class="bs-wizard-info text-center bs-wizard-stepnum">Documentos</div>
                                      <div class="progress"><div class="progress-bar"></div></div>
                                      <a href="#" class="bs-wizard-dot"></a>
                                      <div class="bs-wizard-info text-center">
                                      </div>
                                    </div>
                                    <div class="col-xs-4 bs-wizard-step active">
                                      <div class="bs-wizard-info text-center bs-wizard-stepnum">Fim</div>
                                      <div class="progress"><div class="progress-bar"></div></div>
                                      <a href="#" class="bs-wizard-dot"></a>
                                      <div class="bs-wizard-info text-center">
                                    </div>
                                    </div>
                                </div>
                            </div> 
                        </div>
                    <div>
                    <?php
                    if (!empty($this->listaVaga)):
                              
                    foreach ($this->listaVaga as $l):
                    ?>         
                    <div class="list-group">        
                         <div  class="list-group-item">
                            <h3 class="list-group-item-heading"><?= $l->getEmpresa()?> <i class=" fa fa-check-square-o primary-color" data-toggle="tooltip" data-placement="left" ></i></h3>
                            <p class="list-group-item-text"><?= '<label>Aluno:</label> '. $l->getAluno()?></p>
                            <p class="list-group-item-text"><?= '<label>Bolsa Auxílio:</label> R$'. $l->getBolsa().',00'?></p>
                            <p class="list-group-item-text"><?= '<label>Carga horária:</label> '. $l->getCarga()?></p>
                        </div> 
                        <div class="list-group-item well ">
                            <a class="btn-group " href="<?= $this->url('perfil/default', 
                            array('controller' => 'alunoPresencial', 'action' => 'perfil', 'id'=>$l->getidalunovaga(),)); ?>">
                                <button class="btn  btn-primary " ><i class="fa fa-user fa-2x pull-left"></i><span class="computador">Perfil do <br>Aluno</span></button>
                            </a>
                             <a class="btn-group "  href="<?php echo $this->url('perfilEmpresa/default', 
                          array('controller' => 'empresa', 'action' => 'perfilempresa', 'id'=>$empresa,)); ?>">
                                 <button class="btn  btn-primary " ><i class="fa fa-briefcase fa-2x pull-left"></i><span class="computador">Perfil da <br>Empresa</span></button>
                            </a>
                        </div> 
                               
                    </div>                      
    <?php 
        endforeach; 
            echo  '</div>';
        endif;
            echo '</div> </div>'      
    ?>
<?= $this->resp;
