 <div class=" panel panel-primary">
        <div class="panel-heading">
              <?= 'Buscar aluno'?>
        </div>
     <div class="well-lg">
    <div class="caption"> 
        <form class="navbar-collapse nav" method="post">
            <div class="navbar-collapse"  >  
                <div class="row">
                    <div class="col-lg-6">
                      <div class="input-group">
                        <input name="porMatricula" type="text" class="form-control" placeholder="Procurar por matrícula">
                         <span class="input-group-btn">
                            <button class="btn btn-primary" name="buscar" value="buscarPorMatricula" type="submit"><i class=" glyphicon glyphicon-search"></i></button>
                        </span>
                      </div>
                    </div>
                    <div class="col-lg-6">
                      <div class="input-group">
                         <input name="porNome" type="text" class="form-control" placeholder="Procurar por nome">
                        <span class="input-group-btn">
                          <button class="btn btn-primary" name="buscar" value="buscarPorNome" type="submit"><i class=" glyphicon glyphicon-search"></i></button>
                        </span>
                      </div>
                    </div>
                  </div>
            <?php if(!empty($this->lista)):?>
                 <br/><br/><br/><br/>
        <table class="table">
                 <tr>
                  <th><i class="glyphicon glyphicon-user"></i> ALUNO</th>
                  <th>MATRICULA</th>
                  <th>CURSO</th>
                  <th></th>
                </tr>
                   <?php foreach ($lista as $f): ?>   
                <tr  style="background: #cdffff">
                  <td><?php echo $f->getNome(); ?></td>
                  <td><?php echo $f->getMatricula(); ?></td>
                  <td><?php echo $f->getCurso(); ?></td>
                  <td><a href="<?php echo $this->url('perfil/default', 
                          array('controller' => 'alunoPresencial', 'action' => 'perfil', 'id'=>$f->getidaluno(),)); ?>" class="btn"><i class="glyphicon glyphicon-ok-sign"></i></a></td>
                </tr><?php endforeach; endif;?>
            </table></div>
        </form>
    </div>
</div>
 </div>
<?php echo $this->resp; ?>
