<?php
echo $this->doctype();
$lista = $this->lista;
?>
<html lang="pt-br">
<meta charset="utf-8">
<body>
     <div class=" nav row" style=" background-color: #1989f1">
   
     <h4 style="color: white; text-align: center"><i class=" glyphicon glyphicon-search"  style=" color: #fff194"></i> Buscar aluno</h4>
  
 </div>
<div class="nav">
    <div class="caption"> 
    <div class="row" >
            <div>
                <div class="" style=" ">
                <div class="caption">
                    <ul class="nav  nav-tabs">
                        <li class="  active" role="presentation"><a>Modalidade Presencial</a></li>
                        <li role="presentation" ><a href="<?php echo $this->url('perfil')?>">Modalidade EAD</a></li>
                      
                    </ul> 
                </div>
              </div>
            </div>
        </div>
         <br/><br/><br/><br/>
        <form class="navbar-collapse nav" method="post">
            <div class="navbar-collapse"  >
                        
                <div class="row">
                    <div class="col-lg-6">
                      <div class="input-group">
                       
                        <input name="porMatricula" type="text" class="form-control" placeholder="Procurar por matrícula">
                         <span class="input-group-btn">
                            <button class="btn btn-primary" name="buscar" value="buscarPorMatricula" type="submit"><i class=" glyphicon glyphicon-search"></i></button>
                        </span>
                      </div><!-- /input-group -->
                    </div><!-- /.col-lg-6 -->
                    <div class="col-lg-6">
                      <div class="input-group">
                         <input name="porNome" type="text" class="form-control" placeholder="Procurar por nome">
                        <span class="input-group-btn">
                          <button class="btn btn-primary" name="buscar" value="buscarPorNome" type="submit"><i class=" glyphicon glyphicon-search"></i></button>
                        </span>
                      </div><!-- /input-group -->
                    </div><!-- /.col-lg-6 -->
                  </div><!-- /.row -->
                
                
                    
                 <!-- /.row -->

            <?php if($lista):?>
                 <br/><br/><br/><br/>
        <table class="table">
                 <tr>
                  <th><i class="glyphicon glyphicon-user"></i> ALUNO</th>
                  <th>MATRICULA</th>
                  <th>CURSO</th>
                  <th></th>
                </tr>
                   <?php foreach ($lista as $f): ?>   
                <tr  style="background: #cdffff">
                  <td><?php echo $f->getNome(); ?></td>
                  <td><?php echo $f->getMatricula(); ?></td>
                  <td><?php echo $f->getCurso(); ?></td>
                  <td><a href="<?php echo $this->url('perfil/default', 
                          array('controller' => 'alunoPresencial', 'action' => 'perfil', 'id'=>$f->getidaluno(),)); ?>" class="btn"><i class="glyphicon glyphicon-ok-sign"></i></a></td>
                </tr><?php endforeach; endif;?>
            </table></div>
        </form>
         <br/><br/><br/><br/>
    </div>
</div>
     
        <?php echo $this->resp; ?>
</body>
</html>