
<html lang="pt-br">
    <head>
        <title>Perfil</title>
        <meta charset="utf-8">
        
    </head>
    <head>
  
</head>
<body >
    <script>
     $(document).ready(function (e) {
        $("#divConteudo").hide();

        $("#btnMostrarEsconder").click(function (e) {
            $("#divConteudo").toggle();
        });
    });
});
    </script>
     <div class=" nav row" style=" background-color: #1989f1">
   
     <h4 style="color: white; text-align: center"> Oportunidade</h4>
  
 </div>
     <div class="row" >
            <div>
                <div class="" style=" ">
                <div class="caption">
                    <ul class="nav  nav-tabs" style=" background-color: #f4f4f4">
                        <li class="  active" role="presentation"><a href=""><label>Estágio</label> <span class="label label-primary"> <?php echo count($this->listaOportunidade)?></span></a></li>
                        
                    </ul> 
                </div>
              </div>
            </div>
        </div>
    <div>
        
        <table class=" table" >
            
            
           
            <?php foreach ($this->pagination as $l):?>
            <?php if(date_format($l->getData(), 'd/m/Y')== date('d/m/Y')):?>
            <div class=" pager thumbnail " style="  background-color:  #f5fef1"  >
                        <div class=" nav-tabs" style="background-color:  #20af05; height: 3px"></div>
                        <h4 style=" color: #0044cc "><?php echo "Hoje";?></h4>
                    <h3> <?php echo $l->getCargo();?>   </h3>

                    <label ><?php echo $l->getEmpresa();?></label><br/>
                    <i class=" fa fa-map-marker"></i> <span style=" color: #808080"> Brasília - DF</span><br/><br/>
                    <a href="<?php echo $this->url('perfilOportunidade/default',(['controller'=>'oportunidade', 'action'=>'oportunidadeinfo', 'page'=>$this->$l->getIdoportunidade()]))?>"><button  style=" height:25px; width:90px; color: white; background-color:   #1989f1; border-radius: 20px"><i class=" fa fa-plus" style=" height: 3px; color: white"></i> Info</button>  </a>
                    <button  style=" height:25px; width:90px; color: white; background-color:   #1989f1; border-radius: 20px"><i class=" fa fa-edit" style=" height: 3px;   color: white"></i> Editar</button>
                    <button  style=" height:25px; width:90px; color: white; background-color:    #c30202; border-radius: 20px"><i class=" fa fa-remove" style=" height: 3px;   color: white"></i> Excluir</button><br/> <br/>
                    
                    <div class=" nav-tabs" style="background-color:  #20af05; height: 3px"></div>
                    </div>
            <?php else:
                ?>
                    <div class=" pager thumbnail" style=" background-color:#f5fef1"  >
                        <div class=" nav-tabs" style="background-color:   #1989f1; height: 3px"></div>
                        <h4 style=" color: #0044cc "><?php echo date_format($l->getData(), 'd/m/yy');?></h4>
                    <h3> <?php echo $l->getCargo();?>   </h3>

                    <label ><?php echo $l->getEmpresa();?></label><br/>
                    <i class=" fa fa-map-marker"></i> <span style=" color: #808080"> Brasília - DF</span><br/><br/>
                    
                    <button  style=" height:25px; width:90px; color: white; background-color:   #1989f1; border-radius: 20px"><i class=" fa fa-plus" style=" height: 3px; color: white"></i> Info</button>  
                    <button  style=" height:25px; width:90px; color: white; background-color:   #1989f1; border-radius: 20px"><i class=" fa fa-edit" style=" height: 3px;   color: white"></i> Editar</button>
                    <button  style=" height:25px; width:90px; color: white; background-color:    #c30202; border-radius: 20px"><i class=" fa fa-remove" style=" height: 3px;   color: white"></i> Excluir</button><br/> <br/>
                    <div class=" nav-tabs" style="background-color:  #1989f1; height: 3px"></div>
                    </div>
            <?php
            endif;
            endforeach;?>
            
            
            
        </table>
        
        
    </div>
         <nav aria-label="Page navigation">
         <ul  class="pager">
             <li  <?php if ($this->pageNumber == 1|| $this->pageNumber == 0 ){
     echo "class='disabled'". "style='pointer-events: none'";
    }
    ?>>
      <a href="<?php if ($this->pageNumber > 1){echo $this->pageNumber - 1; }?>" aria-label="Previous">
          <span aria-hidden="true"><i class="glyphicon glyphicon-chevron-left"> </i></span>
      </a>
    </li>
    <li  <?php if ($this->pageNumber >= $this->count){ echo "class='disabled'". "style='pointer-events: none'";}?>>
      <a href="<?php echo $this->pageNumber + 1?>" aria-label="Next">
          <span aria-hidden="true"><i class="glyphicon glyphicon-chevron-right"></i></span>
      </a>
    </li> 
  </ul>
          
</nav><div class="pager"><?php echo $this->pageNumber.' de '.$this->count;?></div> 
<?php echo $this->resp; ?>
</body>
</html>