<?php
    foreach ($this->lista as $l): 
    $getidaluno = $l->getidAluno();
    $nome = $l->getNome();
    $email = $l->getEmail();
    $telefone = $l->getTelefone();
    $matricula = $l->getMatricula();
    $curso = $l->getCurso();
    endforeach;
    $th =[
        '',
        'Emrpesa',
        'Processo',
        'Excluir'
    ];
    $td = [];
    foreach ($this->listaVagaPresencial as $l){
        array_push($td,
        [   
            '<i class="fa fa-square situacao-'.$l->getSituacao().'" aria-hidden="true"></i>',
            $l->getEmpresa(),
            '<a href="'.$this->url('vagaPresencial/default', ['controller' => 'vagapresencial', 'action' => 'lancarcontratos','id'=>$getidaluno, 'idVaga'=>$l->getidvaga(),'curso'=>$l->getIdempresavaga()]).'" class="btn"><i class="fa fa-reorder"></i></a></td>',   
            '<a  class="btn" href="'.$this->url('deleteVagaPresencial', array( 'action' => 'excluirvaga', 'iddelete' => $l->getidVaga())).'"><i class=" glyphicon glyphicon-remove" ></i></a></td>'
        ]);
    }
    echo $this->painel('primary');
    echo $this->painelTitulo($nome)
?>
<ul class="nav nav-tabs" role="tablist">
  <li role="presentation" class="active"><a href="#home" aria-controls="home" role="tab" data-toggle="tab">Estágio</a></li>
</ul>
   
            <div class="pager">
                <p><label> Curso: </label> <?= $curso; ?> &nbsp;&nbsp; <label>Matricula: </label> <?= $matricula; ?></p>
                <p><label>Email: </label> <?= $email; ?> 
                <label>Telefone: </label><?= $telefone; ?></p> 
            </div>    
               
            <div class="col-lg-12">
                <?php 
                if(empty($this->listaVagaPresencial)){
                    echo '<div class="pager alert alert-danger" role="alert" >Nenhum estágio lançado!</div>';
                }else{
                    echo $this->painel('primary');
                    echo $this->tabela($th, $td);
                    echo $this->painelFim();
                }
                ?>
             </div>
            <div class=" well-lg">
                <?php
                echo $this->botaoGrande(
                    $this->url('vagaPresencial/default', array('controller' => 'vagapresencial', 'action' => 'cadastrarvagapresencial', 'idVaga'=>$getidaluno)),
                    'Nova <br> vaga',
                    'fa-plus',
                    'success'
                ); 
                echo ' ';
                echo $this->botaoGrande(
                     $this->url('administrador/default', ['controller'=>'administrador', 'action'=>'editarAlunoPresencial', 'id'=>$getidaluno,'page'=>0]),
                    'Editar <br> perfil',
                    'fa-edit',
                    'primary'
                ); 
                ?>
            </div>
<?= $this->painelFim()?>
<script>
$(document).ready(function(){
$(".situacao-1").css("color","green");  
$(".situacao-0").css("color","red");  
});
</script>
<?= $this->resp ?> 