<?php
    echo $this->doctype();
    $lista = $this->lista;
    $listaVaga = $this->listaVaga;
    $listaEncaminhamento = $this->listaEncaminhamento;
?>
<html lang="pt-br">
    <head>
        <title>Perfil</title>
        <meta charset="utf-8">
        
    </head>
<body>
      <?php if($lista):
            foreach ($lista as $f): 
             $getidaluno = $f->getidAluno();
             endforeach;
             
         endif;
         if ($listaVaga):
             foreach ($listaVaga as $f): 
             $curso = $f->getcursoVaga();
             endforeach;
                 
        endif;
          ?>
  
     
 <div >
       <div class=" nav row" style=" background-color: #1989f1">
   
     <h4 style="color: white; text-align: center"><i class=" glyphicon glyphicon-user"  style=" color: #fff194"></i> Perfil do aluno</h4>
  
 </div>
     
    <div class="nav">
      <div class="caption">
          
           
         <?php if($lista):
            foreach ($lista as $f): 
             
          ?>
            
    <div class="navbar">
        <h3 class="pager"><?php echo $f->getNome(); ?></h3>
        <p class="pager" style=""><i class="glyphicon glyphicon-book"></i>&nbsp;&nbsp;<?php echo $f->getCurso(); ?> &nbsp;&nbsp; <i class="glyphicon glyphicon-bookmark"></i>  <?php echo $f->getMatricula(); ?></p>
      
       
        <br/>
        
    </div>     
        <?php endforeach; endif;?>
      </div>
    </div>
  </div>

   
 
       
      
             
            

 
 <div >
  <div >
    <div class="thumbnail">
      <div class="caption">
          <div>
            <h3 style="text-align: center; " ><?php echo $this->translate('Estágios')?><br/>
            <a style="color:   #2f950c; " class="btn" href="<?php echo $this->url('vaga/default', array('controller' => 'index', 'action' => 'index', 'idVaga'=>$getidaluno)); ?>"><i class="glyphicon glyphicon-plus"></i> </a></h3>
        </div>
    
<?php if ($listaVaga){?>

      <form method="post" >
    <table class="table navbar-default" >
       
        <tr >
         
          <th>EMPRESA</th>
          <th>AGENTE</th>
          <th>CONTRATOS</th>
          <th>Excluir</th>
          <th>Declaração</th>
          
        </tr>
            <?php foreach ($listaVaga as $f):?>
            <?php 
            $idVaga = $f->getIdvaga();
            
            if($f->getRecisao() !=(null)){ ?>
        <tr class="table" style="background: #ab1c1c; color: white">
            
            <td><?php echo $f->getEmpresa(); ?></td>
            <td><?php echo $f->getAgente(); ?></td>
            <td><a href="<?php echo $this->url('vaga/default',  array('controller' => 'index', 'action' => 'lancarcontratos','id'=>$getidaluno, 'idVaga'=>$f->getidvaga(), 'curso'=>$curso)); ?>" class="btn"><i class="glyphicon glyphicon-ok"></i></a></td>     
            <td><a onclick="return confirm('Tem certeza que deseja apagar essa vaga?')" class="btn" href="<?php  echo $this->url('delete', array( 'action' => 'excluirvaga', 'iddelete' => $f->getidvaga())) ?>"><i class=" glyphicon glyphicon-remove" ></i></a></td> 
            <td><a href="<?php echo $this->url('aluno/default',['controller'=>'aluno', 'action'=>'declaracao', 'id'=>$getidaluno,'idVaga'=>$idVaga])?>"><i class="glyphicon glyphicon-file"></i></a></td>
            
         </tr>   <?php } ?>
            
            <?php  if($f->getRecisao() ==('')){ ?>
        <tr class="table" style="background: #8fee8f; ">
            
            
            <td><?php echo $f->getEmpresa(); ?></td>
            <td><?php echo $f->getAgente(); ?></td>
            <td><a href="<?php echo $this->url('vaga/default',  array('controller' => 'index', 'action' => 'lancarcontratos','id'=>$getidaluno, 'idVaga'=>$f->getidvaga(), 'curso'=>$curso)); ?>" class="btn"><i class="glyphicon glyphicon-ok"></i></a></td>     
            <td><a onclick="return confirm('Tem certeza que deseja deletar este lançamento?')" class="btn" href="<?php  echo $this->url('delete', array( 'action' => 'excluirvaga', 'iddelete' => $f->getidvaga())) ?>"><i class=" glyphicon glyphicon-remove" ></i></a></td> 
            <td>Indisponível</td>
        </tr> <?php } ?>
            <?php endforeach;?>
    </table>      
</form>
            <?php }
            else{?>        
<div class="alert-danger" style="margin: initial">
           <br/>
           <h4 style="text-align: center">Nenhum estágio lançado</h4><br/>      
</div>
        <?php };?> 
</div>
      </div>
    </div>
  </div>
    
<?php echo $this->resp; ?>
</body>
</html>