<?php
echo $this->doctype();
$lista = $this->lista;
?>
<html lang="pt-br">
<meta charset="utf-8">
<body>  
 <h3 class="navbar-brand"><i class="glyphicon glyphicon-search"></i>&nbsp;&nbsp;<?php echo $this->translate('Buscar Aluno')?></h3>
        <br/><br/><br/> <br/><br/>     
<form class="navbar-collapse" method="post">
    <div class="navbar-collapse" id="aluno">
       <div class="col-lg-4">
        <div class="input-group">
            <input name="busca" type="text" class="form-control" placeholder="Matrícula" required="" >
          <span class="input-group-btn">
              <button class="btn btn-default" name="buscar" value="Buscar" type="submit">Buscar</button>
          </span>
        </div><!-- /input-group -->
      </div><!-- /.col-lg-6 -->
    </div><!-- /.row -->
    <br/><br/><br/>
    <?php if($lista):?>
<table class="table">
         <tr>
          <th><i class="glyphicon glyphicon-user"></i>&nbsp;&nbsp;ALUNO</th>
          <th>MATRICULA</th>
          <th>CURSO</th>
        </tr>
         
           <?php foreach ($lista as $f): ?>   
        <tr  style="background: #cdffff">
          
          <td><?php echo $f->getNome(); ?></td>
          <td><?php echo $f->getMatricula(); ?></td>
          <td><?php echo $f->getCurso(); ?></td>
          <td><a href="<?php echo $this->url('perfil/default', 
                  array('controller' => 'index', 'action' => 'perfil', 'id'=>$f->getidaluno(),)); ?>" class="btn"><i class="glyphicon glyphicon-ok-sign"></i></a></td>
        </tr>
    </table>
<br/>
</form>
        <?php endforeach; endif;?> 
        <?php echo $this->resp; ?>
</body>
</html>