<?php
echo $this->doctype();
$lista = $this->lista;
?>
<body>
    <h3 class="navbar-brand"><i class="glyphicon glyphicon-search"></i>&nbsp;&nbsp;<?php echo $this->translate('Buscar Aluno')?></h3>
<br/><br/>
<br/><br/>
<div class="navbar-collapse" id="aluno">
<form class="navbar-default" method="post">
   <br/><input name="busca" type="text" class="navbar-default   " />
    <input type="submit" class="btn-info" name="buscar" value="Buscar"/>
    <br/><br/>
    <?php if($lista):?>
<table class="table">
         <tr>
          
          <th><i class="glyphicon glyphicon-user"></i>&nbsp;&nbsp;ALUNO</th>
          <th>MATRICULA</th>
          <th>CURSO</th>
        </tr>
         
           <?php foreach ($lista as $f): ?>   
        <tr  style="background: #cdffff">
          
          <td><?php echo $f->getNome(); ?></td>
          <td><?php echo $f->getMatricula(); ?></td>
          <td><?php echo $f->getCurso(); ?></td>
          <td><a href="<?php echo $this->url('perfil/default', 
                  array('controller' => 'index', 'action' => 'perfil', 'id'=>$f->getidaluno(),)); ?>" class="btn"><i class="glyphicon glyphicon-ok-sign"></i></a></td>
        </tr>
    </table>
<br/>
</form></div>
        <?php endforeach; endif;?> 
        <?php echo $this->resp; ?>
</body>
