<div class="panel-heading"> 
            <div class="row bs-wizard " style="border-bottom:0;">     
                <div class=" cadastro col-xs-4 bs-wizard-step active">
                  <div class="bs-wizard-info text-center bs-wizard-stepnum">Cadastro</div>
                  <div class="progress"><div class="progress-bar"></div></div>
                  <a href="#" class="bs-wizard-dot"></a>
                  <div class="bs-wizard-info text-center">  
                  </div>
                </div> 
                <div class="documentos col-xs-4 bs-wizard-step disabled">
                  <div class="bs-wizard-info text-center bs-wizard-stepnum">Documentos</div>
                  <div class="progress"><div class="progress-bar"></div></div>
                  <a href="#" class="bs-wizard-dot"></a>
                  <div class="bs-wizard-info text-center">
                  </div>
                </div>
                <div class=" fim col-xs-4 bs-wizard-step disabled">
                  <div class="bs-wizard-info text-center bs-wizard-stepnum">Fim</div>
                  <div class="progress"><div class="progress-bar"></div></div>
                  <a href="#" class="bs-wizard-dot"></a>
                  <div class="bs-wizard-info text-center">
                  </div>
                </div>
            </div>
    <br>     
</div>