<div class="modal fade" id="<?= 'modal-'.$this->idDocumento?>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
                <h4 class="modal-title panel panel-heading " id="myModalLabel">Informações 
                <button type="button" class="close " data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                </h4>
                <div class="modal-body">
                    <?= '<label>Documento:</label> '.$this->relatorio.'<br>'?>
                    <?= '<label>Inicio:</label> '.date_format($this->inicio, 'd/m/Y').'<br>'?>
                    <?= '<label>Fim:</label> '.date_format($this->fim, 'd/m/Y').'<br>'?>
                    <?= '<label>Data de lançamento:</label> '.$this->dataLancamento?>
                </div>
        </div>
    </div>
</div>