
    <div class="col-sm-3">
        <span class="fa-stack fa-sm ">
            <i class="fa fa-square-o fa-stack-2x"></i>
            <span class="fa-stack-1x">1</span> 
        </span> Direção do Curso <i class="fa fa-chevron-right"></i>
    </div>
    <div class="col-sm-3">
        <span class="fa-stack fa-sm">
            <i class="fa fa-square-o fa-stack-2x"></i>
            <span class="fa-stack-1x">2</span> 
        </span>Instituição de Ensino <i class="fa fa-chevron-right"></i>
    </div>
    <div class="col-sm-3" >
        <span class="fa-stack fa-sm">
            <i class="fa fa-square-o fa-stack-2x"></i>
            <span class="fa-stack-1x">3</span> 
        </span>Entregue ao aluno? <i class="fa fa-chevron-right"></i>
    </div>
    <div class="col-sm-3" >
        <span class="fa-stack fa-sm">
            <i class="fa fa-square-o fa-stack-2x"></i>
            <span class="fa-stack-1x">4</span> 
        </span>Via do documento 
    </div>
