<?php foreach ($this->curso as $l){
    $curso =  $l->getCurso();
    $idCurso = $l->getIddados();
    $orientador = $l->getOrientador();  
}
?>
    <div class=" panel panel-primary">
        <div class="panel-heading">
                <span style=" color:white"><?= $curso?></span>
                <span style=" color: #fff194" class=" pull-right"><?= $orientador; ?>&nbsp;&nbsp;</span>
                <span style="color: white" class=" pull-right">ORIENTADOR:&nbsp;&nbsp; </span>
        </div>
     <div class="nav">
      <div >
          <div>
            <div>
                <div class="" style=" ">
                <div class="caption">
                    <ul class="nav  nav-tabs" style=" background-color: #f4f4f4">
                        <li  role="presentation"><a href="<?php echo $this->url('relatorioPresencial/default', ['controller'=>'relatoriopresencial','action'=>'infopresencial','curso'=>$idCurso,'curso1'=>$curso])?>">Todas as vagas  <span class="label label-primary"> <?php echo $this->countListaTotalVaga?></span> </a></li>
                        <li role="presentation" ><a href="<?php echo $this->url('relatorioPresencial/default', ['controller'=>'relatoriopresencial','action'=>'infopresencialestagiando','curso'=>$idCurso,'curso1'=>$curso])?>">Estagiando <span class="label label-success"> <?php echo $this->countListaEstagiando?></span></a></li>
                        <li role="presentation" ><a href="<?php echo $this->url('relatorioPresencial/default', ['controller'=>'relatoriopresencial','action'=>'infopresencialencerrado','curso'=>$idCurso,'curso1'=>$curso])?>">Encerrados <span class="label label-danger"> <?php echo $this->countListaEncerrado?></span></a></li>
                        <li  class="  active" role="presentation" ><a href="#"><label>Alunos cadastrados</label> <span class="label label-warning"> <?php echo $this->countListaAlunosCadastrados?></span></a></li>
                        <li role="presentation"><a href="<?php echo $this->url('relatorioPresencial/default', ['controller'=>'relatoriopresencial','action'=>'infoestatisticas','curso'=>$idCurso,'curso1'=>$curso])?>">Estatísticas <i class="fa fa-line-chart"></i></a></li>       
                    </ul> 
                </div>
              </div>
            </div>
          </div>
          <br/>
          <div class="panel panel-default col-sm-12">
          <table class="table "> 
             <tr>
                 <th>Perfil</th>
                 <th>Matricula</th>
                 <th>Telefone</th>
             </tr> <?php  foreach ($this->pagination as $l){?>
                 <tr  style=" background-color: #c8fdff">  
                    <td><a href="<?php echo $this->url('perfilPresencial/default',['controller'=>'alunoPresencial', 'action'=>'perfil', 'id'=>$l[0]->getIdaluno()])?>"><i class="glyphicon glyphicon-user"></i></a> <?php echo  $l[0]->getNome();?></td>
                    <td><?= $l[0]->getMatricula();?></td>  
                    <td><?=  $l[0]->getTelefone();?></td> 
                 </tr><?php  } ?>
         </table>
          </div>
                    <?php
    if($this->countListaAlunosCadastrados == 0){
    echo $this->mensagem;
    
    }?>
      </div></div>
<nav aria-label="Page navigation">
         <ul  class="pager">
             <li  <?php if ($this->pageNumber == 1|| $this->pageNumber == 0 ){
     echo "class='disabled'". "style='pointer-events: none'";
    }
    ?>>
      <a href="<?php if ($this->pageNumber > 1){echo $this->pageNumber - 1; }?>" aria-label="Previous">
          <span aria-hidden="true"><i class="glyphicon glyphicon-chevron-left"> </i></span>
      </a>
    </li>
    <li  <?php if ($this->pageNumber >= $this->count){ echo "class='disabled'". "style='pointer-events: none'";}?>>
      <a href="<?php echo $this->pageNumber + 1?>" aria-label="Next">
          <span aria-hidden="true"><i class="glyphicon glyphicon-chevron-right"></i></span>
      </a>
    </li> 
  </ul>
          
</nav><div class="pager"><?php echo $this->pageNumber.' de '.$this->count;?></div> 





<div class=" row">
  <br/><br/>
           <form class="navbar-collapse nav" method="post">
            <div class="navbar-collapse"  >
                        
                <div class="row">
                    
                    <div class="col-lg-6">
                      <div class="input-group">
                       
                        <input name="porMatricula" type="text" class="form-control" placeholder="Procurar por matrícula">
                         <span class="input-group-btn">
                            <button class="btn btn-primary" name="buscar" value="buscarPorMatricula" type="submit"><i class=" glyphicon glyphicon-search"></i></button>
                        </span>
                      </div><!-- /input-group -->
                    </div><!-- /.col-lg-6 -->
                    <div class="col-lg-6">
                      <div class="input-group">
                         <input name="porNome" type="text" class="form-control" placeholder="Procurar por nome">
                        <span class="input-group-btn">
                          <button class="btn btn-primary" name="buscar" value="buscarPorNome" type="submit"><i class=" glyphicon glyphicon-search"></i></button>
                        </span>
                      </div><!-- /input-group -->
                    </div><!-- /.col-lg-6 -->
                  </div><!-- /.row -->
            </div><br/><br/>
           <?php if($this->lista):?>
                 
        <table class="table">
                 
                   <?php foreach ($this->lista as $l): ?>   
                <tr  style=" background-color: #c8fdff">  
                    <td><a href="<?php echo $this->url('perfilPresencial/default',['controller'=>'alunoPresencial', 'action'=>'perfil', 'id'=>$l[0]->getIdaluno()])?>"><i class="glyphicon glyphicon-user"></i></a> <?php echo  $l[0]->getNome();?></td>
                   
                    <td><?php echo  $l[0]->getMatricula();?></td>  
                    <td><?php echo  $l[0]->getTelefone();?></td> 
                 </tr><?php endforeach; endif;?>
        </table>
           </form>
          </div>





         <div class="pager" ><br/>
           
                
                <a href="<?php echo $this->url('relatorioPresencial') ?>"><span class="btn btn-default" >Voltar</span></a>
            
            </div> 

    </div>