<?php foreach ($this->curso as $l){
    $curso =  $l->getCurso();
    $idCurso = $l->getIddados();
    $orientador = $l->getOrientador();  
}
?>
    <div class=" panel panel-primary">
        <div class="panel-heading">
                <span style=" color:white"><?= $curso?></span>
                <span style=" color: #fff194" class=" pull-right"><?= $orientador; ?>&nbsp;&nbsp;</span>
                <span style="color: white" class=" pull-right">ORIENTADOR:&nbsp;&nbsp; </span>
        </div>
     <div class="nav">
                <div class="caption">
                    <ul class="nav  nav-tabs" style=" background-color: #f4f4f4">
                        <li  role="presentation"><a href="<?php echo $this->url('relatorioPresencial/default', ['controller'=>'relatoriopresencial','action'=>'infopresencial','curso'=>$idCurso,'curso1'=>$curso])?>">Todas as vagas  <span class="label label-primary"> <?php echo $this->countListaTotalVaga?></span> </a></li>
                        <li role="presentation" ><a href="<?php echo $this->url('relatorioPresencial/default', ['controller'=>'relatoriopresencial','action'=>'infopresencialestagiando','curso'=>$idCurso,'curso1'=>$curso])?>">Estagiando <span class="label label-success"> <?php echo $this->countListaEstagiando?></span></a></li>
                        <li role="presentation" ><a href="<?php echo $this->url('relatorioPresencial/default', ['controller'=>'relatoriopresencial','action'=>'infopresencialencerrado','curso'=>$idCurso,'curso1'=>$curso])?>">Encerrados <span class="label label-danger"> <?php echo $this->countListaEncerrado?></span></a></li>
                        <li  class="  active" role="presentation" ><a href="#"><label>Alunos cadastrados</label> <span class="label label-warning"> <?php echo $this->countListaAlunosCadastrados?></span></a></li>
                        <li role="presentation"><a href="<?php echo $this->url('relatorioPresencial/default', ['controller'=>'relatoriopresencial','action'=>'infoestatisticas','curso'=>$idCurso,'curso1'=>$curso])?>">Estatísticas <i class="fa fa-line-chart"></i></a></li>       
                    </ul> 
          <br/>
          <div class="well-lg">
          <table class="table "> 
             <tr>
                <th>Perfil</th>
                <th>Matricula</th>
                <th>Telefone</th>
             </tr> <?php  foreach ($this->pagination as $l){?>
            <tr  style=" background-color: #c8fdff">  
               <td><a href="<?php echo $this->url('perfil/default',['controller'=>'administrador', 'action'=>'perfilAluno', 'id'=>$l[0]->getIdaluno()])?>"><i class="glyphicon glyphicon-user"></i></a> <?php echo  $l[0]->getNome();?></td>
               <td><?= $l[0]->getMatricula();?></td>  
               <td><?=  $l[0]->getTelefone();?></td> 
            </tr><?php  } ?>
         </table>
          </div>
<?= $this->paginacao($this->pageNumber,$this->count)?>
      </div>
     </div>
<div class=" row">
  <br/><br/>
</div>
        <div class="pager" >
            <a href="<?php echo $this->url('relatorioPresencial') ?>"><span class="btn btn-default" >Voltar</span></a>
        </div> 
    </div>