<?php foreach ($this->curso as $l){
    $curso =  $l->getCurso();
    $idCurso = $l->getIddados();
    $orientador = $l->getOrientador();
}
?>   
    <div class=" panel panel-primary">
        <div class="panel-heading">
                <span style=" color:white"><?= $curso?></span>
                <span style=" color: #fff194" class=" pull-right"><?= $orientador; ?>&nbsp;&nbsp;</span>
                <span style="color: white" class=" pull-right">ORIENTADOR:&nbsp;&nbsp; </span>
        </div>
     <div class="nav">
                <div class="caption">
                    <ul class="nav  nav-tabs" style=" background-color: #f4f4f4">
                        <li  class="  active" role="presentation"><a href="#"><label>Todas as vagas </label>  <span class="label label-primary"><?php echo $this->countListaTotalVaga?></span> </a></li>
                        <li role="presentation" ><a href="<?= $this->url('relatorioPresencial/default', ['controller'=>'relatoriopresencial','action'=>'infopresencialestagiando','curso'=>$idCurso,'curso1'=>$curso])?>">Estagiando <span class="label label-success"> <?php echo $this->countListaEstagiando?></span></a></li>
                        <li role="presentation" ><a href="<?= $this->url('relatorioPresencial/default', ['controller'=>'relatoriopresencial','action'=>'infopresencialencerrado','curso'=>$idCurso,'curso1'=>$curso])?>">Encerrados <span class="label label-danger"> <?php echo $this->countListaEncerrado?></span></a></li>
                        <li role="presentation" ><a href="<?= $this->url('relatorioPresencial/default', ['controller'=>'relatoriopresencial','action'=>'infopresencialalunoscadastrados','curso'=>$idCurso,'curso1'=>$curso])?>">Alunos cadastrados <span class="label label-warning"><?php echo $this->countListaAlunosCadastrados ?></span></a></li>
                        <li role="presentation"><a href="<?= $this->url('relatorioPresencial/default', ['controller'=>'relatoriopresencial','action'=>'infoestatisticas','curso'=>$idCurso,'curso1'=>$curso])?>"> Estatísticas <i class="fa fa-line-chart"></i></a></li>
                    </ul>    
          <br/>
          <div class="pager"><i style="color:   #c4ffc2" class=" glyphicon glyphicon-stop"></i>Ativo
              <i style="color:#ae1111" class=" glyphicon glyphicon-stop"></i>Encerrado</div>
          <br/><br/>
          <div class="panel panel-default col-sm-12">
         <table class="table ">
             <tr>
                 <th>Perfil</th>
                 <th>Empresa</th>
                 <th>Agente de Integração</th>
             </tr>
   <?php
        foreach ($this->pagination as $l){
            if($l->getSituacao()== '1'){ ?> 
            <tr style="background-color: #c4ffc2;"><?php } else{?>
                 <tr style="background-color:  #ae1111; color: white"><?php };?>  
                    <td><a href="<?php echo $this->url('perfil/default', 
                         array('controller' => 'administrador', 'action' => 'perfilAluno', 'id'=>$l->getIdalunovaga(),)); ?>"><i class=" glyphicon glyphicon-user"></i></a> <?php echo $l->getAluno()?></td>
                    <td><?=  $l->getEmpresa();?></td>
                    <td><?=  $l->getAgente();?></td>
                 </tr>  
    <?php  } ?>
          
         </table>
          </div>
      </div></div><?= $this->paginacao($this->pageNumber,$this->count)?>
         <div class="pager" ><br/>
                <a href="<?php echo $this->url('relatorioPresencial') ?>"><span class="btn btn-default" >Voltar</span></a>
            </div>
    </div>