<!DOCTYPE html>
<html lang="pt-br">  
    <title>Info</title>
    <meta charset="utf-8">
     <body>
<?php foreach ($this->curso as $l){
    $curso =  $l->getCurso();
    $idCurso = $l->getIddados();
    $orientador = $l->getOrientador();
    
}
?>
         <div class=" nav row" style=" background-color: #1989f1">
   
             <h5>
               
                <span style=" color:white"> &nbsp;&nbsp;<?php echo $curso?></span>
                
                <span style=" color: #fff194" class=" navbar-right"><?php echo $orientador; ?>&nbsp;&nbsp;</span>
                <span style="color: white" class=" navbar-right">ORIENTADOR:&nbsp;&nbsp; </span>
             </h5>
  
 </div>
       

     <div class="nav">
      <div class="caption">
          <div class="row" >
            <div>
                <div class="" style=" ">
                <div class="caption">
                    <ul class="nav  nav-tabs" style=" background-color: #f4f4f4">
                        <li  role="presentation"><a href="<?php echo $this->url('relatorioPresencial/default', ['controller'=>'relatoriopresencial','action'=>'infopresencial','curso'=>$idCurso,'curso1'=>$curso])?>">Todas as vagas  <span class="label label-primary"> <?php echo $this->countListaTotalVaga?></span> </a></li>
                        <li role="presentation" ><a href="<?php echo $this->url('relatorioPresencial/default', ['controller'=>'relatoriopresencial','action'=>'infopresencialestagiando','curso'=>$idCurso,'curso1'=>$curso])?>">Estagiando <span class="label label-success"> <?php echo $this->countListaEstagiando?></span></a></li>
                        <li role="presentation" ><a href="<?php echo $this->url('relatorioPresencial/default', ['controller'=>'relatoriopresencial','action'=>'infopresencialencerrado','curso'=>$idCurso,'curso1'=>$curso])?>">Encerrados <span class="label label-danger"> <?php echo $this->countListaEncerrado?></span></a></li>
                        <li role="presentation" ><a href="<?php echo $this->url('relatorioPresencial/default', ['controller'=>'relatoriopresencial','action'=>'infopresencialalunoscadastrados','curso'=>$idCurso,'curso1'=>$curso])?>">Alunos cadastrados <span class="label label-warning"><?php echo $this->countListaAlunosCadastrados ?></span></a></li>
                        <li  class="  active" role="presentation"><a href="#"><label>Estatísticas </label> <i class="fa fa-line-chart"></i></a></li>
                        
                    </ul> 
                </div>
              </div>
            </div>
          </div></div></div> <br/><br/> 
          
          
<div id="curve_chart" ></div>

         <div class="pager" ><br/>
           
                
                <a href="<?php echo $this->url('relatorioPresencial') ?>"><span class="btn btn-default" >Voltar</span></a>
            
            </div> 

    <script type="text/javascript">
      google.charts.load('current', {'packages':['corechart']});
      google.charts.setOnLoadCallback(drawChart);

      function drawChart() {
        var data = google.visualization.arrayToDataTable([
          ['Mês',  'Novos estágios'],
          ['Jan',       <?php echo count($this->listaMensal[1])?>],
          ['Fev',     <?php echo count($this->listaMensal[2])?>],
          ['Mar',       <?php echo count($this->listaMensal[3])?>],
          ['Abr',     <?php echo count($this->listaMensal[4])?>],
          ['Mai',     <?php echo count($this->listaMensal[5])?>],
          ['Jun',     <?php echo count($this->listaMensal[6])?>],
          ['Jul',      <?php echo count($this->listaMensal[7])?>],
          ['Ago',      <?php echo count($this->listaMensal[8])?>],
          ['Set',     <?php echo count($this->listaMensal[9])?>],
          ['Out',      <?php echo count($this->listaMensal[10])?>],
          ['Nov',      <?php echo count($this->listaMensal[11])?>],
          ['Dez',      <?php echo count($this->listaMensal[12])?>]
        ]);

        var options = {
          title: 'Quantidade de estágios lançados mensalmente no curso de  <?php echo $curso?>',
          curveType: 'function',
          legend: { position: 'bottom' }
        };

        var chart = new google.visualization.LineChart(document.getElementById('curve_chart'));

        chart.draw(data, options);
      }
    </script>
     
    </body>
</html>