<?php 
       echo $this->Doctype();
       ?>
<html lang="pt-br">
    <meta charset="utf-8">
<body>
 <div class=" nav row" style=" background-color: #1989f1">
   
     <h4 style="color: white; text-align: center"><i class=" glyphicon glyphicon-stats"  style=" color: #fff194"></i> Relatórios</h4>
  
 </div>
    <div class="nav">
    <div class="caption">
        <div class="row" >
            <div>
                <div class="" style=" ">
                <div class="caption">
                    <ul class="nav  nav-tabs">
                        <li role="presentation"><a href="<?php echo $this->url('relatorioPresencial')?>">Relatório Geral</a></li>
                        <li  class="  active"  role="presentation" ><a >Estatísticas</a></li>
                        
                    </ul>
        <br/> 
      <form method="post">  
          <div class=" input-group col-lg-3" style=" margin-left: 3%">
            <span class="input-group-addon" id="basic-addon1">Ano</span>
            
            <select required="" class="form-control " name="ano" >
           <option></option>
           <?php 
            for ($date = date('Y'); $date >= 2010 ; $date--){
                echo '<option>'.$date.'</option>';
            }
                ?>
            </select>
            <span class="input-group-btn">
                <button type="submit" class="btn btn-default" >Filtrar</button>
            </span>
        </div>
          <br/>
    </form>
        
          
   <div class="nav">
     <div class="thumbnail">
      <div class="caption">
        
     
        <table class="table" style=" font-size: 12px; background-color:  #ccffff">
        
 <?php if (isset($this->ano)){
       echo '<br/><h4 style="text-align:  center">'.'Quantitativo de documentos lançados em '. $this->ano.' por curso</h4><br/>';
   }  else {
       echo '<br/><h4 style="text-align:  center">'.'Quantitativo de documentos lançados em '. date('Y').' por curso</h4><br/>';
   }
?>      
         <tr>  
             <th>Curso</th>
             <th>Estágios Lançados</th>
             <th>Contratos</th>
             <th>Termos Aditivos</th>
             <th>Relatório (Instituição)</th>
             <th>Relatórios (Empresa)</th>
     
         </tr>
             <?php foreach ($this->listaDados as $l){
             
        ?>  
         <tr> 
             <td><?php echo $l->getCurso()?></td>   
             <td><?php echo $this->cursoVagas[$l->getIddados()]?></td>
             <td><?php echo $this->cursoTce[$l->getIddados()]?></td>
             <td><?php echo $this->cursoTa[$l->getIddados()]?></td>
             <td><?php echo $this->cursoInstituicao[$l->getIddados()]?></td>
             <td><?php echo $this->cursoEmpresa[$l->getIddados()]?></td>
         </tr><?php  }?> 
         
         <tr style=" background-color:  #e9f1f1; ">
              <th>Total</th>    
              <th><?php echo $this->rowTodosCursos?> </th>
              <th><?php echo $this->tceRow?></th>
              <th><?php echo $this->taRow?></th>
              <th><?php echo $this->rtInstituicaoRow?></th>
              <th><?php echo $this->rtEmpresa ?></th>
              
         </tr>
        </table>
      </div>
     </div>
   </div>
         <?php if (isset($this->ano)){
       echo '<br/><br/><h4 style="text-align:  center">'.'Quantitativo de estágios lançados em '. $this->ano.' mensalmente</h4><br/>';
   }  else {
       echo '<br/><br/><h4 style="text-align:  center">'.'Quantitativo de estágios lançados em '. date('Y').' mensalmente</h4><br/>';
   }
?>              
        <canvas id="buyers" width="1100" height="400"></canvas><br/> 
        

    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script>
     // line chart data
            var buyerData = {
                labels : ["Janeiro","Fevereiro","Março","Abril","Maio","Junho","Julho","Agosto","Setembro","Outubro","Novembro","Dezembro"],
                datasets : [
                {
                    fillColor : "rgba(100,140,150,0.1)",
                    strokeColor : "#48b7ff",
                    pointColor : "#48b7ff",
                    pointStrokeColor : "blue",
                    data : [<?php 
                    for( $count = 1;$count<=12 ; $count++){
                        echo $this->mes[$count].',';
                    }
                    
                    ?>]
                }
            ]
            }
            // get line chart canvas
            var buyers = document.getElementById('buyers').getContext('2d');
            // draw line chart
            new Chart(buyers).Line(buyerData);
            
            
 
    
    
    </script>
                </div>   
              </div>
            </div>
        </div>   
    </div>
</div>
   
  </body>
</html>
     
     
     
     <!--Fim -->
  

