<html lang="pt-br">
<meta charset="utf-8">
<script>
function cont(){
   var conteudo = document.getElementById('print').innerHTML;
   tela_impressao = window.open('');
   tela_impressao.document.write(conteudo);
   tela_impressao.window.print();
   tela_impressao.window.close();
}
</script>
    <body>
        
        <?php 
        foreach ($this->aluno as $l){
            $nome = $l->getNome();
            $curso = $l->getCurso();
            $matricula = $l->getMatricula();
        }
         foreach ($this->vaga as $l){
             $agente = $l->getAgente();
            $empresa = $l->getEmpresa();
            $carga = $l->getCarga();
            $bolsa = $l->getBolsa();
        }
        ?>
        
        
        <div id="print" class="conteudo"> 
        <br/><br/><br/><br/><br/><br/><br/>
        <h2 style="text-align: center; size: 12px"><label> Declaração </label></h2>
        <br/><br/>
        <div class="navbar-collapse" style="text-align:justify ;">
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Declaramos para os devidos fins que consta no sistema do PROJEM 
        que a estudante <label><?php echo $nome;?></label>, matricula nº <label><?php echo $matricula;?></label> realizou <label><?php echo $carga;?>h semanais</label> 
        de estágio extracurricular, pelo agente de integração <label><?php echo $agente;?></label>
        na empresa <label><?php echo $empresa;?></label> de 10/08/2015 à 09/02/2017. 
        </div>
        
        <br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>
      <div style="text-align: center"> _________________________________________________________________________
        <p>Romário Macedo Portela</p>
    <p>Projeto Estágio e Empregabilidade – PROJEM</p></div>
        <br/><p style="text-align: end">Brasília, <?php echo date('d/m/Y')?>.</p>


        </div>
        <div class="pager">
            <input class="btn btn-warning" type="button" onclick="cont();" value="Imprimir">
        </div>
    </body>
</html>