<?php
/**
 * @author Romário Macedo Portela <romariomacedo18@gmail.com>
 */
echo    $this->painelTitulo("Dados")?>
                <div class="caption">
                    <ul class="nav  nav-tabs" style=" background-color: #f4f4f4">
                        <li  class=" active" role="presentation"><a href=""><label>Modalidade Presencial</label></a></li> 
                    </ul> 
                </div>
      <div class="well-lg">
            <form  method="post">
                     <table class="table">
                       <?php foreach ( $this->listaPresencial as $l){?>
                        <tr id="<?= 'linha-'.$l->getIddados()?>" style=" background-color: #e0f0f4">
                            <td>
                                <div>
                                    <input name="<?= $l->getIddados()?>" value="<?= $this->translate($l->getCurso())?>" type="text" class="form-control input-group"/>
                                </div>
                            </td>
                                <td>
                                    <input name="<?= "GP-".$l->getIddados()?>" value="<?= $this->translate($l->getQuantidadealunos())?>" type="number" class="form-control input-group" required=""/>   
                                </td>
                            <td >
                                <input name="<?= $l->getIddados()+100?>" value="<?= $this->translate($l->getMeta())?>" type="number" class="form-control input-group" required=""/>   
                            </td>
                            <td>
                                <input name="<?= "orientador".$l->getIddados()?>" value="<?= $this->translate($l->getOrientador())?>" type="text" class="form-control input-group" />     
                            </td>
                        </tr><?php }?>
                    </table>
                     <nav class="pager">
                    <input type="submit" value="Salvar" class=" btn btn-primary"/>
                    </nav><br/>
            </form>
      </div>

