<html lang="pt-br">
<meta charset="utf-8">
<body>
<div class="navbar-collapse">
        <h3>Atualizar orientações pedagógica</h3>
</div>
<div style="height: 600px" class="thumbnail">
    
      <div class="caption">
          
          <div class="row" >
            <div>
                <div class="" style=" ">
                <div class="caption">
                    <ul class="nav  nav-tabs">
                        <li class="  active" role="presentation"><a><label>Modalidade Presencial</label></a></li>
                        <li role="presentation" ><a href="<?php echo $this->url('aluno/default',['controller'=>'aluno', 'action'=>'cadastrar','id'=>'0'])?>">Modalidade EAD</a></li>
                      
                    </ul> 
                </div>
              </div>
            </div>
        </div>
          
          
          
          
<form class="navbar-collapse" method="post">
    <div class="col-lg-6">
        <div>
            <br/><h4 style=" color: #a4a4a4" > Campos obrigatórios</h4><br/>
            <div class="input-group">
                <span class="input-group-addon" ><?php echo $this->translate('Curso')?></span>
                <select name="curso" class="form-control">
                <option></option>
             
                <?php
                foreach ($this->listaPresencial as $l):?>
                <option value="<?php  echo $l->getIddados() ?>"><?php echo $l->getCurso()?></option>
                <?php endforeach;?>


                </select><br/>
            </div><br/>
            <div class="input-group">
                <span class="input-group-addon" ><?php echo $this->translate('Prof. Orientador(a)')?></span>
                <input name="orientador" type="text" class="form-control " required="" /><br/>
            </div>
            <br/>
            <div class="input-group">
                <span class="input-group-addon" ><?php echo $this->translate('E-mail')?></span>
                <input name="email" type="email" class="form-control" required=""/><br/>
            </div>
            <br/>
            <div class="input-group">
                <span class="input-group-addon" ><?php echo $this->translate('Semestra para estágio')?></span>
                <input  name="semestre"  type="number" class="form-control" required=""/><br/>
            </div>
            <br/>
        <div class="input-group">
            <span class="input-group-addon" ><?php echo $this->translate('Orientações')?></span>
            <textarea style="height: 100px" name="orientacao"  class="form-control" required=""></textarea><br/>
        </div>
        <br/>
  
      
              
            <input type="submit" class="btn btn-primary" name="cadastrar" value="Salvar" />
        </div>
    </div>          
</form></div></div>

<?php echo $this->resp; ?>
</body></html>