<html lang="pt-br">
<meta charset="utf-8">
<body>
    <script>
   function validar(){
    var senha = form.senha.value;
    var repetirSenha = form.confirmarSenha.value;
    
    if(senha != repetirSenha){
        alert('Senhas diferentes!');
        form.senha.focus();
        return false;
    };
     if(senha.length <= 5){
        alert('A senha deve conter no mínimo 6 caracteres');
        form.senha.focus();
        return false;
    }
    }   
    </script>
          
    <h3 class="navbar-brand"><i class="glyphicon glyphicon-plus"></i>&nbsp;&nbsp;Cadastro de Acesso</h3>
<br/>
<br/>
<br/>
<br/><br/>
<form name="form" class="navbar-collapse" method="post">
    <div class="col-lg-5">
        <div>
    <?php echo $this->translate('Nome')?><br/><input name="nome" type="text" class="form-control " required="" /><br/>
        <?php echo $this->translate('Login')?><br/><input name="login" type="text" class="form-control" required=""/>
        <br/><span class="col-lg-6"><input placeholder="Senha" name="senha" type="password" class="form-control" required=""/></span>
        <span class=" col-lg-6"><input placeholder="Confirmar Senha" name="confirmarSenha" type="password" class="form-control" required=""/></span><br/>
                 <br/><br/><?php echo $this->translate('Nível')?><br/><select name="nivel" class="form-control" required="">
                     <option >
                          
                     </option>
                     <option value="1">
                          Administrador
                     </option>
                     <option value="2">
                          Usuário Comum
                     </option>
            </select><br/>
            
            <input type="submit" class="btn btn-default" name="cadastrar" value="Cadastrar" onclick="return validar()" />
        </div>
    </div>          
</form>
<?php echo $this->resp; ?>
</body></html>