<?php
use Base\Model\Constantes;

echo    $this->painel(Constantes::temaBootstrap).
        $this->painelTitulo("Agentes de Integracao")?>
                <div class="caption">
                    <ul class="nav  nav-tabs" style=" background-color: #f4f4f4">
                        <li   role="presentation"><a href="<?= $this->url('paginator', ['controller'=>'administrador', 'action' =>'empresa']) ?>">Empresas Concedente <span class="label label-default"> <?php echo count($this->listaEmpresa)?></span></a> </li>
                        <li class=" active" role="presentation" ><a href="#"><label>Agentes de Integração</label> <span class="label label-primary"> <?php echo count($this->listaAgente)?></span></a></li>     
                    </ul> 
                </div>
        <?=   '<br><div class="col-lg-12">'.
                $this->tabelaAgentes([ 'Agente de Integração','Telefone','Editar','Excluir',],$this->pagination, $this->pageNumber).
                $this->paginacao($this->pageNumber,$this->count).
                '</div>'.
                '<div class=" well-lg">'.
                $this->botaoGrande(
                $this->url('cadastrarEmpresa/default', ['controller'=>'empresa', 'action' =>'cadastrarAgente','id'=>'0']) ,
                'Cadastrar <br> agente',
                'fa-plus',
                'success'
                ).
                ' '.
                $this->botaoGrande(
                $this->url('buscarEmpresa'),
                'Buscar <br> empresa',
                'fa-search',
                'primary'
                ).
                '</div>'. 
                $this->painelFIm();
