<?php
/**
 * @author Romário Macedo Portela <romariomacedo18@gmail.com>
 */
use Base\Model\Constantes;
echo    $this->painelTitulo("Agentes de Integração")?>
                <ol class="breadcrumb">
                    <li><a href="<?=$this->url('home')?>">Home</a></li>
                    <li class="active">Controle de empresas</li>
                </ol>
                <div class="caption">
                    <ul class="nav  nav-tabs">
                        <li class=" active" role="presentation" ><a href="#"><span class="label label-primary"> <?= count($this->listaAgente)?></span></a></li>     
                        <li   role="presentation"><a href="<?= $this->url('paginator', ['controller'=>'administrador', 'action' =>'empresa']) ?>">Empresas <span class="label label-default"> <?= count($this->listaEmpresa)?></span></a> </li>
                    </ul> 
                </div>
        <?=   '<br><div class="col-lg-12">'.
                $this->tabelaAgentes([ 'Agente de Integração','Telefone','Editar','Excluir',],$this->pagination, $this->pageNumber).
                $this->paginacao($this->pageNumber,$this->count).
                '</div>'.
                '<div class=" well-lg">'.
                $this->botaoGrande(
                $this->url(Constantes::rotaEmpresaDefault, ['controller'=>  Constantes::administrador, 'action' =>  Constantes::cadastrarAgente,'id'=>'0']) ,
                'Cadastrar <br> agente',
                'fa-plus',
                'success'
                ).
                ' '.
                $this->botaoGrande(
                $this->url(Constantes::perfilEmpresa),
                'Buscar <br> empresa',
                'fa-search',
                'primary'
                ).
                '</div>';
