<?php
echo $this->doctype();
$lista = $this->lista;
?>
<html lang="pt-br">
<meta charset="utf-8">
<body>
    <div class="navbar-collapse">
        <h3><i class="glyphicon glyphicon-search"></i> Buscar aluno</h3>
    </div> 
          
<div class="thumbnail">
    <div class="caption"> 
    
         <br/><br/>
        <form class="navbar-collapse" method="post">
            <div class="navbar-collapse"  >
                        
                <div class="row">
                    <div class="col-lg-6">
                      <div class="input-group">
                       
                        <input name="porMatricula" type="text" class="form-control" placeholder="Procurar por matrícula">
                         <span class="input-group-btn">
                            <button class="btn btn-default" name="buscar" value="buscarPorMatricula" type="submit"><i class=" glyphicon glyphicon-search"></i></button>
                        </span>
                      </div><!-- /input-group -->
                    </div><!-- /.col-lg-6 -->
                    <div class="col-lg-6">
                      <div class="input-group">
                         <input name="porNome" type="text" class="form-control" placeholder="Procurar por nome">
                        <span class="input-group-btn">
                          <button class="btn btn-default" name="buscar" value="buscarPorNome" type="submit"><i class=" glyphicon glyphicon-search"></i></button>
                        </span>
                      </div><!-- /input-group -->
                    </div><!-- /.col-lg-6 -->
                  </div><!-- /.row -->
                
                
                    
                 <!-- /.row -->

            <?php if($lista):?>
                 <br/><br/><br/><br/>
        <table class="table">
                 <tr>
                  <th><i class="glyphicon glyphicon-user"></i> ALUNO</th>
                  <th>MATRICULA</th>
                  <th>CURSO</th>
                  <th></th>
                </tr>
                   <?php foreach ($lista as $l): ?>   
                <tr  style="background: #cdffff">
                  <td><?php echo $l->getNome(); ?></td>
                  <td><?php echo $l->getMatricula(); ?></td>
                  <td><?php echo $l->getCurso(); ?></td>
                  <td><a href="<?php echo $this->url('perfil/default', 
                          array('controller' => 'aluno', 'action' => 'perfil', 'id'=>$l->getidaluno(),)); ?>" class="btn"><i class="glyphicon glyphicon-ok-sign"></i></a></td>
                </tr><?php endforeach; endif;?>
            </table></div>
        </form>
        
          
    </div>
</div>
     
        <?php echo $this->resp; ?>
</body>
</html>