 <?php
 use Base\Model\Constantes;
 echo  $this->painel(Constantes::temaBootstrap).
       $this->painelTitulo("Buscar Aluno")?>
     <div>
    <div class="caption"> 
        <form class="navbar-collapse nav" method="post">
            <div class="navbar-collapse well-lg"  >  
                <div class="row ">
                    <div class="col-lg-6">
                      <div class="input-group">
                        <input name="porMatricula" type="text" class="form-control" placeholder="Procurar por matrícula">
                         <span class="input-group-btn">
                            <button class="btn btn-primary" name="buscar" value="buscarPorMatricula" type="submit"><i class=" glyphicon glyphicon-search"></i></button>
                        </span>
                      </div>
                    </div>
                    <div class="col-lg-6">
                      <div class="input-group">
                         <input name="porNome" type="text" class="form-control" placeholder="Procurar por nome">
                        <span class="input-group-btn">
                          <button class="btn btn-primary" name="buscar" value="buscarPorNome" type="submit"><i class=" glyphicon glyphicon-search"></i></button>
                        </span>
                      </div>
                    </div>
                </div><br><br><br>
        <?php 
        if(!empty($this->lista)):
        echo
        $this->tabelaBuscarAluno(['Nome', 'Curso', 'Matricula', 'Perfil'],$this->lista);
        endif;
        ?>
            </div>
        </form>
         <div class="well-lg">
             <a href="<?= $this->url('paginator', ['controller'=>'administrador', 'action' =>'todosAlunos', 'id'=>'1']) ?>"> <span class="btn btn-primary"><i class="fa fa-users fa-2x pull-left"></i>Todos <br>Aluno</span></a>
           
         </div>
    </div>
</div>
<?= $this->painelFim();