<?php 
use Base\Model\Constantes;
/**
 * @author Romário Macedo Portela <romariomacedo18@gmail.com>
 */
?>
<script>
$(document).ready(function(){
 $("#cadastrarUsuarioForm").validate({
        highlight: function(element) {
        $(element.form).find("." + element.id )
            .addClass("has-error")
            .removeClass("has-succes");
        $("em").css("color","red");
        $("."+element.id+"-valid").css("display","none");
        },
        unhighlight: function(element) {
        $(element.form).find("." + element.id)
            .removeClass("has-error")
            .addClass("has-success"); 
        $("."+element.id+"-valid").css({
            display: "inline",
            color: "green"
        });
        },
        errorElement: "em",
        messages: {
        nome: 'Campo Obrigatório',
        login: 'campo Obrigatório',
        matricula: 'campo obrigatório',
        cargo: 'Campo Obrigatório',
        nivel:'Campo obrigatório',
        senha:'Campo Obrigatório',
        confirmarSenha: 'As senhas devem ser iguais (min. 6 carácteres)'
        },
        rules:{
        nome: {
           required: true
        },
        login: {
           required: true
          
        },
        matricula:{
            required: true
           
        },
        cargo:{
            required: true
        },
        nivel:{
            required: true
        },
        senha:{
            required: true,
             minlength : 6
        },
        confirmarSenha:{
            required: true,
            minlength : 6,
            equalTo : "#senha"
        }
        }
    });
});</script>
<?=    $this->painelTitulo("Cadastro de usuário").
        '<div class="well well-sm"> Todos os campos são obrigatórios</div>';
        $this->usuarioForm->prepare();
        echo $this->form()->openTag($this->usuarioForm);
?>
    <div class="col-lg-12">
            <div class="col-sm-6 col-sm-offset-1 nome">
                <i style=" display: none;"  class=" nome-valid glyphicon glyphicon-ok-circle"></i>
                <?= $this->formRow($this->usuarioForm->get('nome')
                         ->setAttribute('class', 'form-control')
                         ->setAttribute('id', 'nome')
                         ->setLabel('Nome'))
                         ?><br/>
           </div>
            <div class="col-sm-4 login">
                <i style=" display: none;"  class=" login-valid glyphicon glyphicon-ok-circle"></i>
                <?= $this->formRow($this->usuarioForm->get('login')
                         ->setAttribute('class', 'form-control')
                         ->setAttribute('id', 'login')
                         ->setLabel('Login'))
                         ?><br/>
            </div>
            <div class="col-sm-offset-1 col-sm-3 matricula">
                <i style=" display: none;"  class=" matricula-valid glyphicon glyphicon-ok-circle"></i>
                <?= $this->formRow($this->usuarioForm->get('matricula')
                         ->setAttribute('class', 'form-control')
                         ->setAttribute('id', 'matricula')
                         ->setLabel('Matricula'))
                         ?><br/>
            </div>
            <div class="col-sm-4  cargo">
                <i style=" display: none;"  class=" cargo-valid glyphicon glyphicon-ok-circle"></i>
                <?= $this->formRow($this->usuarioForm->get('cargo')
                         ->setAttribute('class', 'form-control')
                         ->setAttribute('id', 'cargo')
                         ->setLabel('Cargo'))
                         ?><br/>
            </div>
        
            <div class="col-sm-3  nivel ">
                <i style=" display: none;"  class=" nivel-valid glyphicon glyphicon-ok-circle"></i>
                <?= $this->formRow($this->usuarioForm->get('nivel')
                         ->setAttribute('class', 'form-control')
                         ->setAttribute('id', 'nivel')
                         ->setLabel('Nivel'))
                         ?>
            </div>
            <div class="col-sm-4 col-sm-offset-1 senha">
                <i style=" display: none;"  class=" senha-valid glyphicon glyphicon-ok-circle"></i>
                <?= $this->formRow($this->usuarioForm->get('senha')
                         ->setAttribute('class', 'form-control')
                         ->setAttribute('id', 'senha')
                         ->setLabel('Senha'))
                         ?><br/>
           </div>
            <div class="col-sm-4 confirmarSenha">
                <label for="confirmarSenha"><?= $this->translate('Confirmar Senha')?></label><i style=" display: none;"  class=" confirmarSenha-valid glyphicon glyphicon-ok-circle"></i>
                <input id="confirmarSenha" name="confirmarSenha" type="password" class="form-control" /><br/>
            </div>
    </div>
    <?=     '<div class="well-lg col-sm-offset-1">'.
            $this->formRow($this->usuarioForm->get('salvar')
                        ->setAttribute('id', 'salvar')
                        ->setAttribute('value', 'Salvar')
                        ->setAttribute('class', 'btn btn-primary')
                        ->setAttribute('type', 'submit')
                        ->setLabel(' <i class="fa fa-check fa-2x pull-left"></i> Finalizar<br>Cadastro')).

            '</div>'.
            $this->form()->closeTag();
