<html lang="pt-br">
<meta charset="utf-8">
<script>
function cont(){
   var conteudo = document.getElementById('print').innerHTML;
   tela_impressao = window.open('');
   tela_impressao.document.write(conteudo);
   tela_impressao.window.print();
   tela_impressao.window.close();
}
</script>
    <body>
        
        <?php 
        foreach ($this->aluno as $l){
            $nome = $l->getNome();
            $curso = $l->getCurso();
            $matricula = $l->getMatricula();
        }
         foreach ($this->vaga as $l){
             $agente = $l->getAgente();
            $empresa = $l->getEmpresa();
            $carga = $l->getCarga();
            $bolsa = $l->getBolsa();
            $inicio = $l->getInicio();
            $recisao = $l->getRecisao();
        }
        ?>
        
        <div class="thumbnail">
        <div class="caption">
        <div id="print" class="conteudo"> 
        <br/><br/><br/><br/><br/><br/><br/>
        <h2 style="text-align: center; size: 12px"><label> Declaração </label></h2>
        <br/><br/>
        <div class="navbar-collapse" style="text-align:justify ;">
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Declaramos para os devidos fins que consta no sistema do PROJEM 
        que a estudante <b><?php echo $nome;?></b>, matricula nº <b><?php echo $matricula;?></b> realizou <b><?php echo $carga;?>h semanais</b> 
        de estágio extracurricular, pelo agente de integração <b><?php echo $agente;?></b>
        na empresa <b><?php echo $empresa;?></b> de <b><?php echo date_format($inicio, 'd/m/Y'); ?></b> à <b><?php echo $recisao;?></b>. 
        </div>
        
        <br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>
      <div style="text-align: center"> _________________________________________________________________________
        <p>Romário Macedo Portela</p>
    <p>Projeto Estágio e Empregabilidade – PROJEM</p></div>
        <br/><p style="text-align: end">Brasília, <?php echo date('d/m/Y')?>.</p>

</div></div>
        </div>
        <div class="pager">
            <input class="btn btn-warning" type="button" onclick="cont();" value="Imprimir">
        </div>
    </body>
</html>