<?php
use Base\Model\Constantes;
echo    $this->painel(Constantes::temaBootstrap).
        $this->painelTitulo("Vias pendentes")?>
        <div class="caption">
            <ul class="nav  nav-tabs" style=" background-color: #f4f4f4">
                <li role="presentation" ><a href="<?= $this->url('documentos/default',['controller'=>'administrador','action'=>'documentosPresencial','id'=>'1'])?>">Documentos vencendo <span class="label label-default"><?= count($this->listaContratosVencendo)?></span></a></li>
                <li role="presentation" class="active"><a><label>Vias Pendentes </label> <span class="label label-warning"><?= count($this->listaDocumentoPendente)?></span></a></li>
            </ul>
        </div>
        <?=
        $this->tabelaDocumentos(['','Processo', 'Início','Fim'],$this->pagination).
        $this->paginacao($this->pageNumber,$this->count).
        $this->painelFim();?>