<?php
/**
 * @author Romário Macedo Portela <romariomacedo18@gmail.com>
 */
use Base\Model\Constantes;

echo    $this->painel(Constantes::temaBootstrap).
        $this->painelTitulo("Documentos")?>
        <div class="caption">
            <ul class="nav  nav-tabs" style=" background-color: #f4f4f4">
                <li role="presentation" class="active"><a><label>Documentos vencendo</label> <span class="label label-warning"><?= count($this->listaContratosVencendo)?></span></a> </li>
                <li role="presentation"><a href="<?= $this->url('documentos/default',['controller'=>'administrador','action'=>'documentosPresencialPendente','id'=>'1'])?>">Vias Pendentes <span class="label label-default"><?= count($this->listaDocumentoPendente)?></span></a></li>     
            </ul>
        </div>
        <?=
        $this->tabelaDocumentos(['','Processo', 'Início','Fim'],$this->pagination).
        $this->paginacao($this->pageNumber,$this->count).
        $this->painelFim();?>