<div class=" panel panel-primary">
        <div class="panel-heading">
            <h4 style="color: white; text-align: center"><i class=" fa fa-file" ></i> Documentos</h4>
  
        </div>
    <div class="nav">
      <div class="caption">
          <div>
            <div>
                <div>
                <div class="caption">
                    <ul class="nav  nav-tabs" style=" background-color: #f4f4f4">
                        <li role="presentation" ><a href="<?= $this->url('documentos')?>">Documentos vencendo</a></li>
                        <li role="presentation" class="active"><a><label>Vias Pendentes</label></a></li>
                  
                    </ul> 
                </div>
              </div>
            </div>
        </div>
          <table class="table">
            <tr >
                <th></th>
                <th>Processo</th>
                <th>Início</th>
                <th>Fim</th>
                
            </tr>
                <?php 
                
                foreach ($this->pagination as $l):
                    if(($l->getOperacao1() 
                            && $l->getOperacao2() 
                            && $l->getOperacao3() == '1')
                            && $l->getOperacao4() == '0' ):
                        
                    ?>
                            <tr style=" background-color: #ffffcc">
                                <td  style=" background-color: #ffcc33; text-align: center; width: 5px "></td>
                                <td><a href="<?php echo $this->url('vagaPresencial/default',  array('controller' => 'vagapresencial', 'action' => 'lancarcontratos','id'=>$l->getIdalunoDocumento(), 'idVaga'=>$l->getIdvagaDocumento(),'curso'=>$l->getCursoDocumento())); ?>"><i class="fa fa-file"></i></a></td>
                                <td><?= date_format($l->getInicio(), 'd/m/Y')?></td>
                                <td><?= date_format($l->getFim(), 'd/m/Y')?></td>
                            </tr>
                   <?php
                   endif; endforeach;?>
        </table>
      </div>
    </div>
    
    <nav aria-label="Page navigation">
         <ul  class="pager">
             <li  <?php if ($this->pageNumber == 1|| $this->pageNumber == 0 ){
     echo "class='disabled'". "style='pointer-events: none'";
    }
    ?>>
      <a href="<?php if ($this->pageNumber > 1){echo $this->pageNumber - 1; }?>" aria-label="Previous">
          <span aria-hidden="true"><i class="glyphicon glyphicon-chevron-left"> </i></span>
      </a>
    </li>
    <li  <?php if ($this->pageNumber >= $this->count){ echo "class='disabled'". "style='pointer-events: none'";}?>>
      <a href="<?php echo $this->pageNumber + 1?>" aria-label="Next">
          <span aria-hidden="true"><i class="glyphicon glyphicon-chevron-right"></i></span>
      </a>
    </li> 
  </ul>
          
</nav><div class="pager"><?php echo $this->pageNumber.' de '.$this->count;?></div> </div>
<?php echo $this->resp; ?>
