<?php
/**
 * @author Romário Macedo Portela <romariomacedo18@gmail.com>
 */
use Base\Model\Constantes;
echo    $this->painelTitulo("Vias pendentes")?>
        <div class="caption">
            <ul class="nav  nav-tabs" style=" background-color: #f4f4f4">
                <li role="presentation" ><a href="<?= $this->url(Constantes::rotaDocumentoDefault,['controller'=>  Constantes::administrador,'action'=>  Constantes::documentos,'id'=>'1'])?>">Documentos vencendo <span class="label label-default"><?= count($this->listaContratosVencendo)?></span></a></li>
                <li role="presentation" class="active"><a><label>Vias Pendentes </label> <span class="label label-warning"><?= count($this->listaDocumentoPendente)?></span></a></li>
            </ul>
        </div>
         <?php
        if(count($this->pagination)>0):
            echo    $this->tabelaDocumentos(['','Processo', 'Início','Fim'],$this->pagination).
                    $this->paginacao($this->pageNumber,$this->count); 
        else:
            echo
            '<div class="well-lg">'.
            $this->alertaDanger("Sem dados a apresentar").
            '</div>';
        endif;