<?php
use Base\Model\Constantes;
?>
<script>
$(document).ready(function(){
 $("#alunoForm").validate({
        highlight: function(element) {
        $(element.form).find("." + element.id )
            .addClass("has-error")
            .removeClass("has-succes");
        $("em").css("color","red");
        $("."+element.id+"-valid").css("display","none");
        },
        unhighlight: function(element) {
        $(element.form).find("." + element.id)
            .removeClass("has-error")
            .addClass("has-success");
        $("."+element.id+"-valid").addClass("glyphicon glyphicon-ok-circle");
        $("."+element.id+"-valid").css({
            display: "inline",
            color: "green"
        });
        },
        errorElement: "em",
        messages: {
        nome: 'Campo Obrigatório',
        matricula: 'Campo Obrigatório',
        cpf: 'CPF inválido',
        email: 'E-mail inválido',
        telefone:'Telefone inválido',
        curso:'Campo Obrigatório'
        },
        rules:{
        nome: {
           required: true
        },
        matricula: {
           required: true
        },
        telefone:{
            required: true,
            max: 99999999999999,
            min: 111111111
        },
        cpf:{
            required: true,
            rangelength: [11, 11],
            max: 99999999999
        },
        email:{
            required: true,
            email: true
        },
        curso:{
            required: true
        }
        }
    });
    $(".glyphicon-ok-circle").css("display", "none");
});
</script>
    <?=
        $this->painel(Constantes::temaBootstrap).
        $this->painelTitulo("Editar aluno").
        '<div class="well well-sm"> Todos os campos são obrigatórios</div>';
        foreach ($this->listaAluno as $l): 
        $this->alunoForm->prepare();
        echo $this->form()->openTag($this->alunoForm);
        ?>
        <div class="col-lg-12">
            <?php
            if($this->resposta == true):
                    echo $this->alertaSuccess(Constantes::alteraçãoSucesso);
            endif;
            ?>
            <div class="col-sm-5  nome">
                <i  class="nome-valid"></i>
                 <?= $this->formRow($this->alunoForm->get('nome')
                         ->setAttribute('class', 'form-control')
                         ->setAttribute('value', $l->getNome())
                         ->setAttribute('id', 'nome')
                         ->setLabel('Nome'))
                         ?>
                <br/>
            </div>
            <div class="col-sm-3 matricula">
                <i   class="matricula-valid"></i>
                <?= $this->formRow($this->alunoForm->get('matricula')
                         ->setAttribute('class', 'form-control')
                         ->setAttribute('value', $l->getMatricula())
                         ->setAttribute('id', 'matricula')
                         ->setLabel('Matricula'))
                         ?>
                <br/>
            </div>
            <div class=" col-sm-4 cpf">
                <i class="cpf-valid"></i>
                 <?= $this->formRow($this->alunoForm->get('cpf')
                         ->setAttribute('class', 'form-control')
                         ->setAttribute('value', $l->getCpf())
                         ->setAttribute('id', 'cpf')
                         ->setLabel('Cpf'))
                         ?>
                <br/>
            </div>
            <div class="col-sm-5 email ">
              <i class=" email-valid "></i>
              <?= $this->formRow($this->alunoForm->get('email')
                        ->setAttribute('class', 'form-control')
                        ->setAttribute('value', $l->getEmail())
                        ->setAttribute('id', 'email')
                        ->setLabel('Email'))
                        ?>
               <br/>
           </div>
            <div class="col-sm-3  telefone">
                <i class=" telefone-valid"></i>
                 <?= $this->formRow($this->alunoForm->get('telefone')
                             ->setAttribute('class', 'form-control')
                             ->setAttribute('value', $l->getTelefone())
                             ->setAttribute('id', 'telefone')
                             ->setLabel('Telefone'))
                             ?>
                    <br/>
            </div>
            <div class="col-sm-4  curso ">
               <i  class=" curso-valid"></i>
               <?php
                $cursos = [];
                foreach ($this->listaCursoPresencial as $f):
                $cursos[$f->getCurso()] = $f->getCurso();
                endforeach;
               ?>
                <?= $this->formRow($this->alunoForm->get('curso')
                         ->setAttribute('id', 'curso')
                         ->setLabel('Curso')
                         ->setValueOptions($cursos))
                         ?>
                <br/>
            </div>
        </div>
    <?=         '<div class="well-lg ">'.
                $this->formRow($this->alunoForm->get('salvar')
                            ->setAttribute('id', 'salvar')
                            ->setAttribute('value', 'Salvar')
                            ->setAttribute('class', 'btn btn-success')
                            ->setAttribute('type', 'submit')
                            ->setLabel(' <i class="fa fa-check fa-2x pull-left"></i> Salvar as<br>alterações')).
                ' '.
                $this->botaoGrande(
                        $this->url(Constantes::rotaPerfilAlunoDefault, ['controller' => Constantes::administrador, 'action' => Constantes::perfilAluno,'id'=>$l->getIdaluno()]),
                        'Perfil do <br> aluno',
                        'fa-user',
                        'primary'
                    ).'</div>'. 
    $this->form()->closeTag();
    endforeach;
    echo $this->painelFim();

