<script>
    $(document).ready(function(){
     $("#cadastrarAgenteForm").validate({
            highlight: function(element) {
            $(element.form).find("." + element.id )
                .addClass("has-error")
                .removeClass("has-succes");
            $("em").css("color","red");
            $("."+element.id+"-valid").css("display","none");
            },
            unhighlight: function(element) {
            $(element.form).find("." + element.id)
                .removeClass("has-error")
                .addClass("has-success"); 
            $("."+element.id+"-valid").css({
                display: "inline",
                color: "green"
            });
            },
            errorElement: "em",
            messages: {
            empresa: 'Campo Obrigatório',
            cnpj: 'cnpj inválido',
            telefone: 'Telefone inválido',
            endereco: 'Campo Obrigatório',
            email:'Email inválido',
            responsavel:'Campo Obrigatório',
            tamanho: 'Campo Obrigatório'
            },
            rules:{
            agente: {
               required: true
            },
            cnpj: {
               required: true,
              rangelength: [14, 14],
              max: 99999999999999
            },
            telefone:{
                required: true,
                max: 99999999999999,
                min: 11111111
            },
            endereco:{
                required: true
            },
            email:{
                required: true,
                email: true
            },
            responsavel:{
                required: true
            },
            tamanho:{
                required: true
            }
            }
        });
    });


</script>
    <div class=" panel panel-primary">
        <div class="panel-heading"><?= $this->translate('Editar Empresa')?></div>

        <?php if($this->alerta): ?>
            <?='<div class="alert-danger" style=" text-align: center">'. $this->alerta.'</div>'; ?> 
        <?php endif; ?>
        
        <?='<div class="well well-sm">'. $this->translate('Todos os campos são obrigatórios').'</div>'?> 
        
        <?php foreach ($this->listaAgente as $l):?>
        <form method="post" id="cadastrarAgenteForm">
            <div class="col-lg-12">
                <div class="col-sm-6 col-sm-offset-1 nome">
                    <label for="agente"><?= $this->translate('Agente')?></label><i style=" display: none;"  class=" agente-valid glyphicon glyphicon-ok-circle"></i>
                    <input value="<?= $l->getAgente()?>" id="agente" name="agente" type="text" class="form-control "  /><br/>
                </div>
                <div class="col-sm-4 cnpj">
                    <label for="cnpj"><?= $this->translate('CNPJ')?></label><i style=" display: none;"  class=" cnpj-valid glyphicon glyphicon-ok-circle"></i>
                    <input value="<?= $l->getCnpj()?>" maxlength="14" id="cnpj" name="cnpj" type="text" class="form-control" /><br/>
                </div>
                <div class="col-sm-offset-1 col-sm-3 telefone">
                    <label for="telefone"><?= $this->translate('Telefone')?></label><i style=" display: none;"  class=" telefone-valid glyphicon glyphicon-ok-circle"></i>
                    <input value="<?= $l->getTelefone()?>" name="telefone" id="telefone" type="tel" class="form-control" /><br/>
                </div>
                <div class="col-sm-4  endereco">
                    <label for="endereço"><?= $this->translate('Endereço')?></label><i style=" display: none;"  class=" endereco-valid glyphicon glyphicon-ok-circle"></i>
                    <input value="<?= $l->getEndereco()?>" id="endereco" name="endereco" type="text" class="form-control" /><br/>
                </div>
                <div class="col-sm-3 email">
                    <label for="email"><?= $this->translate('Email')?></label><i style=" display: none;"  class=" email-valid glyphicon glyphicon-ok-circle"></i>
                   <input value="<?= $l->getEmail()?>" id="email" name="email"  class="form-control" /><br/>
                </div>
              <div class="col-sm-offset-1 col-sm-3 responsavel">
                  <label for="responsavel"><?= $this->translate('Responsável')?></label><i style=" display: none;"  class=" responsavel-valid glyphicon glyphicon-ok-circle"></i>
                <input value="<?= $l->getResponsavel()?>" id="responsavel" name="responsavel"  type="text" class="form-control"/><br/>
             </div>
        </div>
        <div class="well-lg col-sm-offset-1">
        <button type="submit" class="btn btn-success" name="salvar" value="Salvar" ><i class="fa fa-check fa-2x pull-left"></i> Finalizar<br>Cadastro</button>
        </div>  
    </form>
        <?php endforeach?>
    </div>
    <?= $this->resp; ?>
