<?php
$th =[
    'Empresa',
    'Telefone',
    'Editar',
    'Excluir',
    ];

$td = [];
foreach ($this->pagination as $kay=> $l){
    array_push($td,
    array(
        '<a href="'. $this->url('perfilEmpresa/default', 
                          array('controller' => 'empresa', 'action' => 'perfilempresa', 'id'=>$l->getEmpresa(),)).'"><i class="glyphicon glyphicon-user"></i></a>'. $l->getEmpresa(),
        $l->getTelefone(),
        '<a href="'.$this->url('empresa/default', array('controller'=>'administrador', 'action'=>'editarEmpresa', 'id'=>$l->getIdempresa(),'page'=>$this->pageNumber)).'"><i class=" glyphicon glyphicon-edit"></i></a></td>',
        '<a onclick="return confirm("Tem certeza que deseja deletar este registro?")" style="color: #c81616" href="'. $this->url('excluirEmpresa',['action'=>'excluirAgente', 'deleteAgente'=>$l->getIdempresa(),'page'=>$this->pageNumber] ).'"><i  class=" glyphicon glyphicon-remove"></i></a>'
        ));
}
?>
<div class=" panel panel-primary">
    <?= $this->painel("Empresas")?>
    <div class="caption">
        <ul class="nav  nav-tabs" style=" background-color: #f4f4f4">
            <li  class=" active" role="presentation"><a><label>Empresas Concedente </label> <span class="label label-primary"> <?= count($this->listaEmpresa)?></span></a> </li>
            <li role="presentation" ><a href="<?= $this->url('paginator', ['controller'=>'administrador', 'action' =>'agente']) ?>">Agentes de Integração <span class="label label-default"> <?php echo count($this->listaAgente)?></span></a></li>
        </ul> 
    </div>
    <?= '<br><div class="col-lg-12">'?>
    <?= $this->tabela($th, $td)?>
    <?= $this->paginacao($this->pageNumber,$this->count)?>
    <?= '</div>'?>
    <div class="well-lg ">
        <a href="<?= $this->url('cadastrarEmpresa/default', ['controller'=>'empresa', 'action' =>'cadastrarEmpresa','id'=>'0']) ?>">
            <span class="btn btn-success  ">
                <i class=" fa fa-plus fa-2x pull-left"></i>Cadastrar <br>Empresa
            </span>
        </a>
        <a href="<?= $this->url('buscarEmpresa') ?>">
            <span class="btn btn-primary  ">
                <i class=" fa fa-search fa-2x pull-left"></i>Procurar <br>Empresa
            </span>
        </a>
    </div>
</div>
<?= $this->resp; ?>
