<script>
$(function () {
  $("#rateYo").rateYo({
    rating    : 3,
    spacing   : "2px",
    starWidth: '12px',
    multiColor: {
        
      "startColor": "#FF0000", 
      "endColor"  : "#ffcf18" 
    }
  });
 
});
</script>
<div class=" panel panel-primary">
    <div class="panel-heading">
        <?= $this->translate('Perfil da empresa')?>
    </div>
    
    <div class="caption">
    <?php if(!empty($this->empresa)): foreach ($this->empresa as $l):  $idEmpresa = $l->getIdempresa(); ?>
        <?=
        '<div class="navbar pager">'.
            '<img src="'.$this->basePath('img/empresa.png').'" class="img-circle " alt="Cinque Terre" width="70" height="70">'.
        '<h3 class="pager">'.  $l->getEmpresa().'</h3>'?>
            <span class=" center-block" id="rateYo"></span>
            <?=
        '<p class="pager"><label>CNPJ:</label>'.  $l->getCnpj().'<br/>'
            . '<label>Responável: </label> '. $l->getResponsavel().' '
            . '<label> Telefone: </label> '.  $l->getTelefone().'<br/></div> ';
            
        ?>
    <?php endforeach; endif;?>
    </div>
                <div class="caption">
                    <ul class="nav  nav-tabs" style=" background-color: #f4f4f4">
                        <li  class="  active" role="presentation"><a href="#"><label>Nova Mensagem</label></a></li>
                        <li role="presentation"><a href="#">Caixa de saída</a></li>
                    
                    </ul> 
                </div>
             
    <div class="pager">
        <form method="post">
           <div class="col-sm-12 well-lg col-sm-offset-2 ">
               <div class="col-sm-8"><input name="titulo" placeholder="Assunto: "class="form-control" type="text"/></div><br/><br/>
               <div class="col-sm-8"><textarea name="mensagem" style="height: 200px"placeholder="Mensagem..." class="form-control" type="text"></textarea></div>
           </div>
        <button class="btn btn-primary">Enviar</button>
    </form>    
    </div>
</div>
