
<div class=" panel panel-primary">
        <div class="panel-heading">
           <h4 style="color: white; text-align: center"><i class=" glyphicon glyphicon-user"  style=" color: #fff194"></i> Perfil da empresa</h4>
        </div>

      <div>
            <div>
                <div>
                    <div class="caption" >
                        <ul class="nav  nav-tabs" style=" background-color: #f4f4f4">
                            <li class="  active" role="presentation"><a><label>Painel</label></a></li>
                            <li role="presentation"><a href="<?=$this->url("empresaMensagem/default",['controller'=> 'administrador', 'action'=>'mensagem', 'id'=>$this->idEmpresa]) ?>"><?= $this->translate("<i class='fa fa-envelope-o'></i>")?></a></li>
                        </ul> 
                    </div>
                </div>
            </div>
        </div>
 <div >
     <div class="row">
    <div class="">
       <div class="caption">
    <?php if(!empty($this->empresaSelect)): foreach ($this->empresaSelect as $l): ?>
        <?=
        '<div class="navbar pager">'.
            '<img src="'.$this->basePath('img/empresa.png').'" class="img-circle " alt="Cinque Terre" width="70" height="70">'.
        '<h3 class="pager">'.  $l->getEmpresa().'</h3>'?>
            <span class=" center-block" id="rateYo"></span>
            <?=
        '<p class="pager"><label>CNPJ:</label>'.  $l->getCnpj().'<br/>'
            . '<label>Responável: </label> '. $l->getResponsavel().' '
            . '<label> Telefone: </label> '.  $l->getTelefone().'<br/></div> ';
            
        ?>
    <?php endforeach; endif;?>
    </div>
    </div>
  </div>
 </div>
 <div >
  <div >
    <div>
      <div class="caption">
                <div class="caption">
                    <ul class="nav  nav-tabs" style=" background-color: #f4f4f4">
                        <li  class="  active" role="presentation"><a href="#"><label>Todas as vagas </label>  <span class="label label-primary"> <?php echo count($this->listaVaga) ?></span> </a></li>
                        <li role="presentation" ><a href="<?php echo $this->url('perfilEmpresa/default', ['controller'=>'empresa','action'=>'perfilempresaestagiando','id'=>$this->empresa])?>">Estagiando <span class="label label-success"> <?php echo count($this->listaVagaEstagiando)?></span></a></li>
                         <li role="presentation" ><a href="<?php echo $this->url('perfilEmpresa/default', ['controller'=>'empresa','action'=>'perfilempresaencerrado','id'=>$this->empresa])?>">Encerrado <span class="label label-danger"> <?php echo count($this->listaVaga) - count($this->listaVagaEstagiando)  ?></span></a></li>
                    </ul> 
                </div>
<?php if ($this->listaVaga){?>
<form method="post" >
    <table class="table navbar-default" >
            <tr >
                <th>Aluno</th>
              <th>Empresa</th>
              <th>Agente de Integração</th>

            </tr>
                <?php foreach ($this->pagination   as $l):?>
                <?php 

             if($l->getSituacao() == '0'){ ?>
            <tr class="table" style="background: #ab1c1c; color: white">
                <td><a href="<?php echo $this->url('perfilAluno/default',['controller'=>'administrador', 'action'=>'perfilAluno', 'id'=>$l->getIdalunovaga()])?>"><i class="glyphicon glyphicon-user"></i></a> <?php echo $l->getAluno()?></td>
                <td><?php echo $l->getEmpresa(); ?></td>
                <td><?php echo $l->getAgente(); ?></td>

             </tr>   <?php } ?>

                <?php  if($l->getSituacao() == '1'){ ?>
            <tr class="table" style="background: #8fee8f; ">
                <td><a href="<?php echo $this->url('perfilAluno/default',['controller'=>'administrador', 'action'=>'perfilAluno', 'id'=>$l->getIdalunovaga()])?>"><i class="glyphicon glyphicon-user"></i></a> <?php echo $l->getAluno()?></td>
                <td><?php echo $l->getEmpresa(); ?></td>
                <td><?php echo $l->getAgente(); ?></td>          
            </tr> <?php } ?>
                <?php
                endforeach;?>
        </table>    
              <br/>
              <nav aria-label="Page navigation">
             <ul  class="pager">
                 <li  <?php if ($this->pageNumber == 1|| $this->pageNumber == 0 ){
         echo "class='disabled'". "style='pointer-events: none'";
        }
        ?>>
          <a href="<?php if ($this->pageNumber > 1){echo $this->pageNumber - 1; }?>" aria-label="Previous">
              <span aria-hidden="true"><i class="glyphicon glyphicon-chevron-left"> </i></span>
          </a>
        </li>
        <li  <?php if ($this->pageNumber >= $this->count){ echo "class='disabled'". "style='pointer-events: none'";}?>>
          <a href="<?php echo $this->pageNumber + 1?>" aria-label="Next">
              <span aria-hidden="true"><i class="glyphicon glyphicon-chevron-right"></i></span>
          </a>
        </li> 
      </ul>       
    </nav><div class="pager"><?php echo $this->pageNumber.' de '.$this->count;?></div>      
</form>
            <?php }
            else{?> 
     <div class=" thumbnail">
        <div class="alert-danger " style="margin: initial">
                   <br/>
                   <h4 style="text-align: center">Nenhum estágio lançado</h4><br/>      
        </div>
      </div> <?php }?>   
      </div>
       
      </div>
    </div>
  </div>
      <div class="well-lg ">
        <a href="<?= $this->url('editarEmpresa/default', array('controller'=>'administrador', 'action'=>'editarEmpresa', 'id'=>$this->idEmpresa))?>">
            <span class="btn btn-primary  ">
                <i class=" fa fa-plus fa-2x pull-left"></i>Editar <br>Perfil
            </span>
        </a>
    </div>
</div>