<?php echo $this->doctype(); ?>
<html lang="pt-br">
<meta charset="utf-8">
<body>
      <div class=" nav row" style=" background-color: #1989f1">
   
     <h4 style="color: white; text-align: center">Controle de alunos</h4>
  
 </div>
    <div class="nav">
      <div class="caption">
          <div class="row" >
            <div>
                <div class="" style=" ">
                <div class="caption">
                    <ul class="nav  nav-tabs">
                        <li class=" active" role="presentation"><a><label>Modalidade Presencial</label>   <span class="label label-primary"> <?php echo count($this->listaAlunoPresencial)?></span></a></li>
                        <li  role="presentation" ><a href="<?php echo $this->url('administrador/default',['controller'=>'administrador','action'=>'aluno','id'=>1])?>">Modalidade EAD  <span class="label label-default"> <?php echo count($this->listaAlunoEAD)?></span></a></li>
                      
                    </ul> 
                </div>
              </div>
            </div>
        </div>
        <table class="table">
            <tr>
                <th>Perfil</th>
                <th>Aluno</th>
                <th>Editar</th>
                <th>Excluir</th>
                
            </tr>
                <?php foreach ($this->pagination as $l):?>
            <tr style=" background-color: #b6fffd">
                <td><a href="<?php echo $this->url('perfilPresencial/default',['controller'=>'alunoPresencial', 'action'=>'perfil', 'id'=>$l->getIdaluno()])?>"><i class="glyphicon glyphicon-user"></i></a></td>
                <td><?php echo $l->getNome()?></td>
                <td><a href="<?php echo $this->url('administrador/default', ['controller'=>'administrador', 'action'=>'editarAlunoPresencial', 'id'=>$l->getIdaluno(),'page'=>$this->pageNumber])?>"><i class=" glyphicon glyphicon-edit"></i></a></td>
                <td><a onclick="return confirm('Tem certeza que deseja deletar este registro?')" style="color: #c81616" href="<?php echo $this->url('excluirAluno',['action'=>'excluirAlunoPresencial', 'deleteAluno'=>$l->getIdaluno(),'page'=>$this->pageNumber] )?>"><i  class=" glyphicon glyphicon-remove"></i></a></td>
            </tr><?php    endforeach;?>

        </table>     
      </div>
    </div>
    
    <nav aria-label="Page navigation">
         <ul  class="pager">
             <li  <?php if ($this->pageNumber == 1|| $this->pageNumber == 0 ){
     echo "class='disabled'". "style='pointer-events: none'";
    }
    ?>>
      <a href="<?php if ($this->pageNumber > 1){echo $this->pageNumber - 1; }?>" aria-label="Previous">
          <span aria-hidden="true"><i class="glyphicon glyphicon-chevron-left"> </i></span>
      </a>
    </li>
    <li  <?php if ($this->pageNumber >= $this->count){ echo "class='disabled'". "style='pointer-events: none'";}?>>
      <a href="<?php echo $this->pageNumber + 1?>" aria-label="Next">
          <span aria-hidden="true"><i class="glyphicon glyphicon-chevron-right"></i></span>
      </a>
    </li> 
  </ul>
          
</nav><div class="pager"><?php echo $this->pageNumber.' de '.$this->count;?></div> 
<?php echo $this->resp; ?>
</body>
</html>