<?php
use Base\Model\Constantes;
        echo    $this->painel(Constantes::temaBootstrap).
                $this->painelTitulo('Todos alunos cadastrados').
                '<br>'.
                '<div class="col-lg-12">'.
                $this->tabelaTodosAlunos(['Perfil','Aluno','Matricula','Editar','Excluir'],$this->pagination, $this->pageNumber).
                $this->paginacao($this->pageNumber,$this->count).
                '</div>'.
                '<div class=" well-lg">'.
                $this->botaoGrande(
                $this->url('aluno/default',['controller'=>'alunoPresencial','action'=>'cadastrar','id'=>'0']),
                'Novo <br> aluno',
                'fa-plus',
                'success'
                ). 
                ' '.
                $this->botaoGrande(
                $this->url(Constantes::rotaPerfilAluno),
                'Buscar <br> aluno',
                'fa-search',
                'primary'
                ).
                '</div>'. 
                $this->painelFim();
        