<?php
$th =   [
            'Perfil',
            'Aluno',
            'Matricula',
            'Editar',
            'Excluir'
        ];
$td =   [];
        foreach ($this->pagination as $kay=> $l){
            array_push($td,[
                '<a href="'.$this->url('perfilPresencial/default',['controller'=>'alunoPresencial', 'action'=>'perfil', 'id'=>$l->getIdaluno()]).'"><i class="glyphicon glyphicon-user"></i></a>',
                $l->getNome(),
                $l->getMatricula(),
                '<a href="'.$this->url('administrador/default', ['controller'=>'administrador', 'action'=>'editarAlunoPresencial', 'id'=>$l->getIdaluno(),'page'=>$this->pageNumber]).'"><i class=" glyphicon glyphicon-edit"></i></a>' ,
                '<a onclick="return confirm("Tem certeza que deseja deletar este registro?")" style="color: #c81616" href="'.$this->url('excluirAluno',['action'=>'excluirAlunoPresencial', 'deleteAluno'=>$l->getIdaluno(),'page'=>$this->pageNumber]).'"><i  class=" glyphicon glyphicon-remove"></i></a>'
                ]);  
        }
        echo    $this->painel('primary');
        echo    $this->painelTitulo('Todos alunos cadastrados');
        echo    '<div class="col-lg-12">';
        echo    $this->tabela($th,$td);
        echo    $this->paginacao($this->pageNumber,$this->count);
        echo    '</div>';
        echo    '<div class=" well-lg">';
        echo    $this->botaoGrande(
                $this->url('aluno/default',['controller'=>'alunoPresencial','action'=>'cadastrar','id'=>'0']),
                'Novo <br> aluno',
                'fa-plus',
                'success'
                ); 
        echo    ' ';
        echo    $this->botaoGrande(
                $this->url('perfilPresencial'),
                'Buscar <br> aluno',
                'fa-search',
                'primary'
                );
        echo    '</div>'; 
        echo    $this->painelFim();
        echo    $this->resp; 
        