<div>
<div class="panel panel-primary">
  <div class=" panel-heading ">
    Todos alunos cadastrados
  </div>
            <div>
                <div class="" style=" ">
                <div class="caption">
                    <ul class="nav  nav-tabs" style=" background-color: #f4f4f4">
                        <li class=" active" role="presentation"><a><span><input class="input-search form-control" placeholder="Nome"type="text" alt="lista-clientes" /></span>   </a></li>
                    </ul>    
                </div>
              </div>
            </div><br>
            <div class="col-lg-12">
        <table class="table table-bordered table-striped lista-clientes" >
            <tr>
                <th>Perfil</th>
                <th>Aluno</th>
                <th class=" modoCelularTable">Matricula</th>
                <th>Editar</th>
                <th>Excluir</th>
            </tr>
                <?php foreach ($this->pagination as $l):?>
            <tr >
                <td><a href="<?php echo $this->url('perfilPresencial/default',['controller'=>'alunoPresencial', 'action'=>'perfil', 'id'=>$l->getIdaluno()])?>"><i class="glyphicon glyphicon-user"></i></a></td>
                <td><?php echo $l->getNome()?></td>
                <td class=" modoCelularTable"><?php echo $l->getMatricula()?></td>
                <td><a href="<?php echo $this->url('administrador/default', ['controller'=>'administrador', 'action'=>'editarAlunoPresencial', 'id'=>$l->getIdaluno(),'page'=>$this->pageNumber])?>"><i class=" glyphicon glyphicon-edit"></i></a></td>
                <td><a onclick="return confirm('Tem certeza que deseja deletar este registro?')" style="color: #c81616" href="<?php echo $this->url('excluirAluno',['action'=>'excluirAlunoPresencial', 'deleteAluno'=>$l->getIdaluno(),'page'=>$this->pageNumber] )?>"><i  class=" glyphicon glyphicon-remove"></i></a></td>
            </tr>
                <?php    endforeach;?>
        </table>
        <nav aria-label="Page navigation">
         <ul  class="pager">
             <li  <?php if ($this->pageNumber == 1|| $this->pageNumber == 0 ){
                echo "class='disabled'". "style='pointer-events: none'";
               }
               ?>>
                 <a href="<?php if ($this->pageNumber > 1){echo $this->pageNumber - 1; }?>" aria-label="Previous">
                     <span aria-hidden="true"><i class="glyphicon glyphicon-chevron-left"> </i></span>
                 </a>
        </li>
    <li  <?php if ($this->pageNumber >= $this->count){ echo "class='disabled'". "style='pointer-events: none'";}?>>
      <a href="<?php echo $this->pageNumber + 1?>" aria-label="Next">
          <span aria-hidden="true"><i class="glyphicon glyphicon-chevron-right"></i></span>
      </a>
    </li> 
  </ul>      
</nav>
            <div class="pager">
             <?= $this->pageNumber.' de '.$this->count;?>
            </div>
            </div>
            <div class=" well-lg">
                <a href="<?= $this->url('aluno/default',['controller'=>'alunoPresencial','action'=>'cadastrar','id'=>'0']) ?>"> <span class="btn btn-success"><i class="fa fa-plus fa-2x pull-left"></i> Novo<br>Aluno</span></a>
                 <a href="<?= $this->url('perfilPresencial') ?>"> <span class="btn btn-primary"><i class="fa fa-search fa-2x pull-left"></i> Buscar<br>Aluno</span></a>
            
            </div> 
            
      </div>
 </div>
<?= $this->resp; ?>
<script>
$(function(){
    $(".input-search").keyup(function(){
        //pega o css da tabela 
        var tabela = $(this).attr('alt');
        if( $(this).val() != ""){
            $("."+tabela+" tbody>tr").hide();
            $("."+tabela+" td:contains-ci('" + $(this).val() + "')").parent("tr").show();
        } else{
            $("."+tabela+" tbody>tr").show();
        }
    }); 
});
$.extend($.expr[":"], {
    "contains-ci": function(elem, i, match, array) {
        return (elem.textContent || elem.innerText || $(elem).text() || "").toLowerCase().indexOf((match[3] || "").toLowerCase()) >= 0;
    }
});
</script>