<div class=" panel panel-primary">
       <?= $this->painel('Acessos')?><br>
            <table class="table" >
                <tr> 
                    <th>Nome</th>
                    <th>Login</th>
                    <th>Nível</th>
                    <th>Editar</th>
                    <th>Excluir</th>
                </tr>
                    <?php foreach ($this->listaUsuarios as $l):?> 
                <tr>
                    <td><?php echo $l->getNome();?> </td>
                    <td><?php echo $l->getLogin();?> </td>
                    <td><?php echo $l->getNivel();?> </td>
                    <td><a  class="btn" href="<?php echo $this->url('usuarios/default', array('controller'=>'administrador','action' => 'editarUsuario', 'id' => $l->getIdusuario())) ?>"><i class=" glyphicon glyphicon-edit"></i></a></td>
                    <td><a onclick="return confirm('Tem certeza que deseja deletar este registro?')" style="color: #c81616" class="btn" href="<?php echo $this->url('excluirUsuario', array('action' => 'excluirUsuario', 'deleteUsuario' => $l->getIdusuario())) ?>"><i class=" glyphicon glyphicon-remove"></i></a></td>
                </tr> <?php endforeach;?>
            </table>
 
    <div class="pager">
        <a href="<?= $this->url('cadastrarUsuario')?>"><span  class="btn btn-primary"><i class=" fa fa-user-plus"></i> Cadastrar Usuario</span></a>
    </div>
</div> 
<?= $this->resp; ?>
