<?php
/**
 * @author Romário Macedo Portela <romariomacedo18@gmail.com>
 */
        echo    $this->painelTitulo('Usuarios').
                '<ol class="breadcrumb">
                <li><a href="'.$this->url('home').'">Home</a></li>
                <li class="active">Usuários</li>
                </ol>'.
                '<div class="col-lg-12">'.
                $this->tabelaUsuarios([ 'Nome','Login','Conf.','Editar','Excluir',],$this->listaUsuarios).
                '</div>'.
                '<div class=" well-lg">'.
                $this->botaoGrande(
                $this->url('cadastrarUsuario'),
                'Cadastro de <br>usuarios',
                'fa-user-plus',
                'primary'
                ).
                '</div>';
