<?= $this->headScript()->prependFile($this->basePath('js/loader.js'))    ;?>

  <div class=" panel panel-primary">
        <div class="panel-heading">
                <h4 style="color: white; text-align: center"><i class=" fa fa-bar-chart-o"  style=" color: #fff194"></i> Relatórios</h4>
  
        </div>
    <div class="nav">
    <div class="caption">
        <div >
            <div>
                <div>
                <div class="caption">
                    <ul class="nav  nav-tabs" style=" background-color: #f4f4f4">
                        <li role="presentation"><a href="<?php echo $this->url('relatorioPresencial')?>">Aproveitamento em estágio</a></li>
                        <li  class="  active"  role="presentation" ><a ><label>Documentos</label></a></li>
                    </ul>
        <br/>
      <form method="post">  
          <div class=" input-group col-lg-2" style=" margin-left: 1%">
            <span class="input-group-addon" id="basic-addon1">Ano</span>
            
            <select required="" class="form-control " name="ano" >
           <option></option>
           <?php 
            for ($date = date('Y'); $date >= 2010 ; $date--){
                echo '<option>'.$date.'</option>';
            }
                ?>
            </select>
            <span class="input-group-btn">
                <button type="submit" class="btn btn-default" >Filtrar</button>
            </span>
        </div>
          
      </form>
   <div >
     <div >
         <form class=" navbar-default">
        
        
 <?php if (isset($this->ano)){
       echo '<br/><h4 style="text-align:  center">'.'Quantitativo de documentos lançados em '. $this->ano.' por curso</h4><br/>';
   }  else {
       echo '<br/><h4 style="text-align:  center">'.'Quantitativo de documentos lançados em '. date('Y').' por curso</h4><br/>';
   }
?>      <div class="panel panel-primary col-sm-12">
        <table class="table " >
         <tr>  
             <th></th>
             <th>Curso</th>
             <th>Estágios Lançados</th>
             <th>Contratos</th>
             <th>Termos Aditivos</th>
     
         </tr>
             <?php foreach ($this->listaDados as $chave => $l){
             
        ?>  
         <tr style=" background-color: #f9fcfe"> 
             <td  style=" background-color:  #1989f1; text-align: center; width: 3px; "></td>
             <td><?php echo $l->getCurso()?></td>   
             <td><?php echo $this->cursoVagas[0][$l->getIddados()]?></td>
             <td><?php echo $this->cursoTce[0][$l->getIddados()]?></td>
             <td><?php echo $this->cursoTa[0][$l->getIddados()]?></td>
         </tr><?php  }?> 
         <tr style=" background-color:  #e9f1f1; ">
              <th  style=" background-color:  #1989f1; text-align: center; width: 3px; "></th>
              <th>Total</th>    
              <th><?php echo $this->rowTodosCursos?> </th>
              <th><?php echo $this->tceRow?></th>
              <th><?php echo $this->taRow?></th>
         </tr>
        </table>
        </div>
         </form>
     </div>
   </div>
         <?php if (isset($this->ano)){
       echo '<br/><br/><h4 style="text-align:  center">'.'Quantitativo de estágios lançados em '. $this->ano.' mensalmente</h4><br/>';
   }  else {
       echo '<br/><br/><h4 style="text-align:  center">'.'Quantitativo de estágios lançados em '. date('Y').' mensalmente</h4><br/>';
   }
?>              
        <div id="curve_chart" style="width: 1135px; height: 500px">
        </div>
    <script type="text/javascript">
      google.charts.load('current', {'packages':['corechart']});
      google.charts.setOnLoadCallback(drawChart);

      function drawChart() {
        var data = google.visualization.arrayToDataTable([
          ['Mês',  'Novos estágios'],
          ['Jan',       <?= $this->mes[0][1]?>],
          ['Fev',     <?= $this->mes[0][2]?>],
          ['Mar',       <?= $this->mes[0][3]?>],
          ['Abr',     <?= $this->mes[0][4]?>],
          ['Mai',     <?= $this->mes[0][5]?>],
          ['Jun',     <?= $this->mes[0][6]?>],
          ['Jul',      <?= $this->mes[0][7]?>],
          ['Ago',      <?= $this->mes[0][8]?>],
          ['Set',     <?= $this->mes[0][9]?>],
          ['Out',      <?= $this->mes[0][10]?>],
          ['Nov',      <?= $this->mes[0][11]?>],
          ['Dez',      <?= $this->mes[0][12]?>]
        ]);

        var options = {
         
          curveType: 'function',
          legend: { position: 'bottom' }
        };

        var chart = new google.visualization.LineChart(document.getElementById('curve_chart'));

        chart.draw(data, options);
      }
    </script>
                </div>   
              </div>
            </div>
        </div>   
    </div>
    </div>
  </div>

  

