<?php 
       $fetchRow = $this->fetchRow;
       $row = $this->row;
       $listaAluno = $this->listaAluno;
       $recisaoRow = $this->recisaoRow;
       $rowEmpresa = $this->rowEmpresa;
       $rowListaAluno = $this->rowListaAluno;
       $rowAgente = $this->rowAgente;
          
       ?>
<html lang="pt-br">
<meta charset="utf-8">
 <body>
 <div class="navbar-collapse">
        <h3><i class=" glyphicon glyphicon-stats"></i> Relatórios</h3>
    </div>  
     <div class="thumbnail">
    <div class="caption">
        <div class="row" >
            <div>
                <div class="" style=" ">
                <div class="caption">
                    <ul class="nav  nav-tabs">
                        <li role="presentation"><a href="<?php echo $this->url('relatorio')?>">Relatório Geral</a></li>
                        <li  class="  active"  role="presentation" ><a href="#">Gráficos</a></li>
                        <li role="presentation" ><a href="#">Filtrar</a></li>
                    </ul>
                    <br/><br/>
                
                    
                </div>
                    
              </div>
            </div>
        </div>   
    
    </div>
        </div> 
    
  

    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">
      google.charts.load('current', {'packages':['bar']});
      google.charts.setOnLoadCallback(drawStuff);

      function drawStuff() {
        var data = new google.visualization.arrayToDataTable([
          ['Move', 'Estagiando'],
          ["Administração", <?php echo $this->administracaoOn;?>],
          ["Pedagogia", <?php echo $this->pedagogiaOn;?>],
          ["RH", <?php echo $this->rhOn;?>],
          ["Turismo", <?php echo $this->turismoOn;?>],
          ["GTI", <?php echo $this->gtiOn;?>],
          ["ADS", <?php echo $this->adsOn;?>],
          ["Contábeis", <?php echo $this->contabeisOn;?>],
          ["Economia", <?php echo $this->economiaOn;?>],
          ["Filosofia", <?php echo $this->filosofiaOn;?>],
          ["G. Pública", <?php echo $this->gestaoPublicaOn;?>],
          ["Com. Exter.", <?php echo $this->gestaoComercioOn;?>],
          ["Ges. Financ.", <?php echo $this->gestaoFinanceiraOn;?>],
          ["Letras", <?php echo $this->letrasOn;?>],
          ["PROFORM", <?php echo $this->proformOn;?>],
          ["Seg. da Inf.", <?php echo $this->segurancaInformacaoOn;?>],
          ["Seg. Pública", <?php echo $this->segurancaPublicaOn;?>]
        ]);

        var options = {
          title: 'Quantidade de Estágios por curso',
          width: 1150,
          legend: { position: 'none' },
          chart: { subtitle: 'Cursos Virtuais' },
          axes: {
            x: {
              0: { side: 'top', label: 'White to move'} // Top x-axis.
            }
          },
          bar: { groupWidth: "80%" }
        };

        var chart = new google.charts.Bar(document.getElementById('top_x_div'));
        // Convert the Classic options to Material options.
        chart.draw(data, google.charts.Bar.convertOptions(options));
      };
    </script>
    
 
    
  
    <div  id="top_x_div" style="width: 1000px; height: 400px;"></div>

  </body>
</html>
     
     
     
     <!--Fim -->
  

